politics-rewired/Spoke

- src/server/api/assignment.js
- src/server/api/schema.js
Also fixes minor transaction issues with https://github.com/assemble-main/Spoke/pull/185.
> reject request on failure, wrap all db modifications in transaction

- src/containers/AdminAssignmentRequest/index.jsx
- src/lib/index.js
- src/server/api/lib/twilio.js
- src/server/index.js
- src/workers/job-processes.js
- src/workers/lib.js
The first two commits are tidying up. The [final commit](https://github.com/politics-rewired/Spoke/commit/7217e1221706f98c57cd21a1a4f063523122a32c) is where the real changes are.
> Add delay to handling of delivery report

- .circleci/config.yml
- Dockerfile
- package.json
- readmestaging20180902
This adds a minimal Circle CI config file that runs only for commits on politics-rewored/deploy.
The job builds a Docker image, adds "latest" and the commit SHA as tags, and pushes it to GCR.
> ci: publish Docker image to GCR

- package.json
- src/api/organization.js
- src/api/schema.js
- src/containers/AdminCampaignEdit.jsx
- src/containers/Settings.jsx
- src/server/api/organization.js
- src/server/api/schema.js
- src/workers/jobs.js
> Add integration with assemble numbers

- package.json
- src/workers/jobs.js
This is easiest if you start from line 1261.
> Refactor campaign export

- src/api/schema.js
- src/components/App.jsx
- src/components/DisplayLink.jsx
- src/components/Login.jsx
- src/components/OrganizationJoinLink.jsx
- src/components/PasswordResetLink.jsx
- src/components/forms/GSForm.jsx
- src/components/forms/GSPasswordField.jsx
- src/containers/AdminPersonList.jsx
- src/containers/UserEdit.jsx
- src/routes.jsx
- src/server/api/lib/utils.js
- src/server/api/schema.js
- src/server/auth-passport.js
- src/server/index.js
- src/server/local-auth-helpers.js
- src/server/models/cacheable_queries/user.js
Port of MoveOnOrg/Spoke#658. This includes a refactor of how passport strategies are defined and
registered.
Port of MoveOnOrg/Spoke#1059. This includes a cosmetic improvements for the login page as well as
consolidating sign in logic.
> feat: local login

- package.json
- src/network/apollo-client-singleton.js
- yarn.lock
> feat: graphql operation metrics

- src/server/index.js
- src/server/routes/auth.js
- src/server/routes/graphql.js
- src/server/routes/index.js
- src/server/routes/nexmo.js
- src/server/routes/twilio.js
- src/server/routes/utils.js
This was initially for debugging datadog metrics reporting, but maybe not a bad thing to have anyway?
> refactor(routing): organize express app routing

- src/server/notifications.js
> fix: add is_archived check

- .circleci/config.yml
See politics-rewired/circleci-images#1 for further optimizations
> ci(docker): enable docker layer caching

- src/server/routes/graphql.js
This reverts commit 731c1e71e9121c2f7560ba4fe5d8b83a24a34e1e, reversing
changes made to a51b9d86423e5984e5a444d85d3a4e4a71f72015.
> revert: revert pull request #265 - feat/no-mocks-in-prod

- src/logger.js
> feat(logging): add timestamps to log format

- src/config.js
> feat(logging): use most verbose logging level in development

- Dockerfile
> build(docker): copy yarn.lock in dependencies Dokerfile build step

- .circleci/config.yml
> ci(gcloud): update gcr auth method

- src/containers/AssignmentTexterContact/ApplyTagDialog.jsx
- src/containers/AssignmentTexterContact/index.jsx
- refactors `ApplyTagButton` --> `ApplyTagDialog` to allow presenting from different sources
- adds overflow menu to mobile and switches from toolbar --> flexbox
- removes a bunch of dead styling rules
<details>
<summary>Screenshots</summary>
<br />
Layout on Desktop (large):
Layout on iPhone 6 (small-medium):
Layout on iPhone 5 (small):
Mobile Overflow Menu:
Full-width Tag Editor:
</details>
> feat(ux): add overflow menu to mobile texter view

- src/components/Login.jsx
- src/containers/UserEdit.jsx
- src/server/local-auth-helpers.js
The important changes just ended up being the ones to `local-auth-helpers.js`
> fix: password reset

- src/containers/UserMenu.jsx
I tested that Auth0 still works as well.
> fix(session): use passport for non-Auth0 logout

- src/api/schema.js
- src/containers/UserEdit.jsx
I have tested login, signup, admin password reset, edit user, and change password with these changes
> fix: user edit fields

- src/server/api/conversations.js
Note that this doesn't affect display order for incoming message review, which is still by `campaign_contact.updated_at` – I think we should keep that because it's what's displayed in the updated at column.
Because this is a 2 part query where the intermediate campaign contact ids are stored in JS memory for the next query (should probably be refactored later), the order by here is used to select the campaign ids to include on the page, so this fixes the problem users are having now where contacts that haven't really been updated are forcing them to scroll through too many pages.
> fix: order by last messaged at rather than updated_at

- package.json
- src/server/api/lib/assemble-numbers.js
- src/server/api/lib/message-sending.js
- src/server/api/lib/services.js
- src/server/api/lib/twilio.js
- src/server/api/schema.js
- src/server/index.js
- src/server/routes/assemble-numbers.js
- src/server/routes/index.js
- src/workers/jobs.js
- yarn.lock
> feat: Assemble Numbers SMS support

- src/server/api/conversations.js
> feat: use case insensitive search

- dev-tools/insert-invite.js
- migrations/20191021185945_add_invite_payload.js
- package.json
- src/server/api/schema.js
Tested using the following payload:
```json
{
"messaging_services": [
{
"messaging_service_sid": "SID",
"account_sid": "account_sid!!",
"encrypted_auth_token": "secure_stuff",
"service_type":"twilio"
}
]
}
```
> feat: invite payload

- src/containers/UserEdit.jsx
- src/server/auth-passport.js
- src/server/local-auth-helpers.js
Reverts politics-rewired/Spoke#334
> Revert "feat: show login errors"

- src/components/PasswordResetLink.jsx
This should have been part of #335
> feat: update password reset text

- src/components/CampaignTextersForm.jsx
- src/containers/AdminCampaignEdit.jsx
- src/containers/AdminCampaignStats.jsx
- src/containers/CampaignList/CampaignList.jsx
- src/server/api/assignment.js
- src/server/api/user.js
Manual assignment behaves incorrectly for campaigns past their due dates. Add big red warnings for this case.
Campaign List:
Campaign Stats Page:
Campaign Edit Page:
> feat: warn overdue campaign

- migrations/20191105145008_add-team-tag-escalations.js
- migrations/20191113095008_add-escalation-tags-to-assignment-views.js
- src/api/organization.js
- src/api/team.js
- src/containers/AdminAssignmentControl/AssignmentRow.jsx
- src/containers/AdminAssignmentControl/index.jsx
- src/server/api/assignment.js
- src/server/api/organization.js
- src/server/api/schema.js
- src/server/api/team.js
Reverts politics-rewired/Spoke#359
> Reapply feat: custom escalation tags

- src/server/api/conversations.js
> feat: optimize search by texter

- src/api/schema.js
- src/containers/CampaignList/CampaignList.jsx
- src/containers/CampaignList/OperationDialog.jsx
- src/containers/CampaignList/index.jsx
- src/server/api/schema.js
> feat: implement unmarkforsecondpass and deleteneedsmessage

- src/server/api/schema.js
The boolean check in this block was flipped
```js
if (config.OPTOUTS_SHARE_ALL_ORGS) {	
optOutJoinConditions["opt_out.organization_id"] =	
"campaign.organization_id";	
}
```
This also fixes a non-critical bug where the join on `opt_out` could produce multiple rows by
replacing the join with a `select exists (...) as is_opted_out`.
> fix: scope opt-out check correctly

- .dockerignore
- dev-tools/export-all-campaigns.js
- src/workers/exports/s3.js
- src/workers/jobs.js
It can be run with `./dev-tools/babel-run ./dev-tools/export-all-campaigns.js`
and requires envvar `NOTIFY_USER_ID`
> feat: sync script

- src/server/api/assignment.js
- src/server/api/lib/alerts.js
- src/server/api/schema.js
- src/server/index.js
> fix: external assignment management

- src/components/ContactToolbar.jsx
- src/containers/AssignmentTexterContact/TopFixedSection.jsx
- src/containers/TexterTodo.jsx
Mobile is not great but won't get much better until we have a better component library for responsiveness.
Closes #355
**Screenshots**
<details>
<summary>Desktop</summary>
</details>
<details>
<summary>Small Mobile</summary>
</details>
> feat: add campaign title to texter todo

- .circleci/config.yml
- Dockerfile
- src/client/VersionNotifier.jsx
- src/client/events.js
- src/components/App.jsx
- src/config.js
- src/network/apollo-client-singleton.js
- src/network/response-middleware-network-interface.js
- src/server/index.js
`SPOKE_VERSION` should evaluated at compile-time and not run-time, but this is a good start.
<details open>
<summary>Screenshot</summary>
</details>
ToDo:
> feat: notify client when Spoke is out of date

- package.json
- yarn.lock
> build(deps): update google-libphonenumber

- src/server/api/schema.js
- src/server/models/index.js
> fix: knex refactor issues

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Each of these sections should make reviewing the PR easier.
We have not been great about tracking changes that merit documentation updates so that is included as well.
> chore: add PR template

- package.json
- src/server/routes/graphql.js
- yarn.lock
See docs:
- [`ApolloServer`](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#apolloserver)
- [`applymiddleware()`](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#apolloserverapplymiddleware)
> build(deps): update apollo-server

- dev-tools/insert-invite.js
- src/server/api/schema.js
> feat: improve insert invite

- src/containers/AdminPersonList.jsx
This brings the mutation result in line with the personData query below.
> fix: refetch the current people page

- Dockerfile
- package.json
- webpack/config.js
- yarn.lock
See [comment here](https://github.com/JeffreyWay/laravel-mix/issues/790#issuecomment-365756483) for more information on the switch from `webpack.optimize.UglifyJsPlugin` to `uglifyjs-webpack-plugin`.
This runs locally fine and now builds in Docker
> build: fix building in docker context

- src/server/api/assignment.js
- src/server/api/campaign.js
- src/server/api/organization.js
- src/server/api/question.js
- src/server/api/schema.js
- src/server/api/user.js
- src/server/memoredis.js
Since we don't support `userCannedResponses`, we just return `[]` for them, always.
> feat: cache information for get contacts

- src/api/schema.js
- src/components/IncomingMessageList/MessageColumn/MessageResponse.jsx
- src/config.js
- src/containers/AssignmentTexterContact/index.jsx
- src/server/api/campaign-contact.js
- src/server/api/schema.js
- src/server/memoredis.js
This reverts commit 8ddab7e7220431bee63271a8d58867987b81a077, reversing
changes made to 96ead5c0745ef5b82f759a65450ead31193133e5.
> revert: fix/contact-fields-to-hide

- src/server/memoredis.js
To keep logs as standardized as possible
> chore: pass winston logger to memoredis

- src/components/Login.jsx
- src/components/UserPasswordReset.jsx
- src/routes.jsx
This is a band aid fix for simplifying the React side of local login. It adds a new component for password reset to sidesteps the `UserEdit` component.
> fix: use dedicated password reset component

- package.json
- src/components/ScriptEditor.jsx
- yarn.lock
> feat: add segment counter

- src/components/TexterRequest.jsx
> feat: shorten texter poll interval

- package.json
- yarn.lock
We should see a 50x speed up for Redis instances of our size
> feat: use sped up memoredis

- src/server/api/lib/assemble-numbers.js
- src/server/api/lib/message-sending.js
- src/server/api/lib/twilio.js
- src/server/api/schema.js
We were joining on the campaign, increasing planning time, to get the organization id, which we already knew!
> feat: optimize getContactMessagingService

- src/components/Empty.jsx
- src/containers/AssignmentTexterContact/index.jsx
Reverts politics-rewired/Spoke#559
> Revert "fix(ux): make pencil icon size dynamic"

- dev-tools/Procfile.dev
Mainly to remove noise in dev logs
> chore: switch from npm to yarn and remove unused

- src/containers/UserEdit.jsx
The editUser mutation was being accessed as if it were a query. Fetch it explicitly via mutation
and then pass that via state.
This also cleans up props a bit.
> fix: fix UserEdit

- package.json
- src/api/schema.js
- src/components/CampaignContactsForm.jsx
- src/components/styles/file-drop.css
- src/containers/AdminCampaignEdit.jsx
- src/lib/index.js
- src/network/apollo-client-singleton.js
- src/server/api/lib/edit-campaign.js
- src/server/api/schema.js
- src/server/routes/graphql.js
- yarn.lock
I tried using the existing `parseCSV()` but it was not completing, not erroring, nor would it print a log from the very first line. Hence the refactor introducing `validateCsv()`.
> feat: process contact CSVs server-side

- src/lib/index.js
- src/server/api/lib/edit-campaign.js
I thought this was handled in `validateCsv()` but it was actually handled in `AdminCampaignEdit.handleSave()`
> fix: handle custom fields properly

- package.json
- src/config.js
- src/server/index.js
- src/server/routes/utils.js
- yarn.lock
```
{"message":"Node app is running on port 8090","level":"info","timestamp":"2020-03-03T03:06:37.726Z"}
$ kill -SIGTERM <pid>
{"message":"Received kill signal, waiting 5000ms before shutting down...","level":"info","timestamp":"2020-03-03T03:06:55.629Z"}
{"message":"Done waiting","level":"info","timestamp":"2020-03-03T03:06:55.630Z"}
{"message":"Starting cleanup.","level":"info","timestamp":"2020-03-03T03:06:56.635Z"}
{"message":"Cleanup finished, server is shutting down.","level":"info","timestamp":"2020-03-03T03:06:56.652Z"}
```
See:
- Kubernetes best practices: terminating with grace ([cloud.google.com](https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-terminating-with-grace))
- Health Checks and Graceful Shutdown …
> feat: handle shutdown gracefully

- src/server/api/assignment.js
- src/server/index.js
https://github.com/Automattic/kue#graceful-shutdown
> feat: tear down kue on shutdown

- src/containers/PaginatedUsersRetriever.jsx
End fetch loop for outdated user queries.
Changing filter parameters caused simultaneous user fetches. Not good.
Tested locally.
N/A
N/A
> fix(message-review): prevent duplicate fetches of users

- migrations/20200306160524_trollbot.js
- src/api/schema.js
- src/api/trollbot.js
- src/components/AdminDashboard.jsx
- src/config.js
- src/containers/AdminTrollAlarms/components/TrollAlarmList.jsx
- src/containers/AdminTrollAlarms/index.jsx
- src/containers/Settings/components/General.jsx
- src/containers/Settings/components/TrollTokenSettings.jsx
- src/containers/Settings/index.jsx
- src/routes.jsx
- src/server/api/schema.js
- src/server/api/trollbot.js
- src/workers/cron/catch-troll-alarms.js
> feat: trollbot migrations and alert generation

- migrations/20200310222822_clean-up-indexes.js
This brings indexes and constraints in line with what our fork uses and needs.
This increases performs of inserts by removing unused indexes and of the todos query, which uses campaign_contact.assignment_id (which is now a smaller partial index).
> feat: clean up indexes and constraints

- src/server/routes/campaign-preview.js
Removing some noise from production logs.
Make production logs more meaningful.
Run locally.
N/A
N/A
> chore: remove debug log line

- src/api/schema.js
- src/containers/AdminIncomingMessageList/index.jsx
- src/server/api/message-review.js
- src/server/api/schema.js
Fix errors returned from message review assignment management actions.
This also removes two unused assignment management mutations.
Unassign and Reassign mutations would succeed but display an error due to a resolver issue.
This has been tested locally with each of the four action types.
N/A
N/A
> fix: message review action resolver errors

- src/components/TopNav.jsx
- src/routes.jsx
Add's the organization name the beginning of all top navigations and changes "Spoke Texting" to just "Texting".
Tested locally
> feat: add organization to topnav

- package.json
- src/server/worker.ts
- yarn.lock
Pass a separate `pg.Pool` to `graphile-scheduler`.
Also updates `graphile-worker` to v0.5.0.
Using the same worker pool resulted in no scheduled jobs being run and this error being thrown on shutdown:
```
{
"level": "error",
"message": "Failed task 1183 (release-stale-replies) with error Unable to acquire a connection (7.01ms):\n  Error: Unable to acquire aconnection\n      at Client_PG.acquireConnection (/Users/bchrobot/rewired/oss/spoke/node_modules/rethink-knex-adapter/node_modules/knex/lib/client.js:330:39)\n      at Runner.ensureConnection (/Users/bchrobot/rewired/oss/spoke/node_modules/rethink-knex-adapter/node_modules/knex/lib/runner.js:226:24)\n      at Runner.run (/Users/bchrobot/rewired/oss/spoke/node_modules/rethink-knex-adapter/node_modules/knex/lib/runner.js:33:41)\n      at …
```
> fix: fix graphile-scheduler jobs

- src/components/forms/GSForm.jsx
- src/components/forms/GSTextField.jsx
[mcverter](https://github.com/politics-rewired/Spoke/commits?author=mcverter)
This fixes the save buttons in the admin us to add a label so they are easily clickable.
The buttons to confirm settings in the admin UI, such as in the campaign configuration did not have the labels applying and therefor were very small and hard to click.
Tested and deployed on dev-spoke.checkupon.me
https://i.imgur.com/mRcuAjn.png
> fix: admin ui button react element

- src/server/api/assignment.js
Remove debug log statements
Noisey
Locally.
N/A
N/A
> chore: remove debug log statements

- src/server/api/schema.js
Users with `is_superadmin = true` will be added as owners to new organizations.
For instances managing many organizations it is a pain to have to add the core admin staff to each new organization.
N/A
See new Superadmin section in the [Organization](https://docs.spokerewired.com/article/79-organizations) topic.
> feat: add superadmins as owners to new organizations

- src/components/TexterRequest.jsx
Clarify Slack-specific language with a more general "no texts available" message.
The old message is confusing for everyone not using Slack.
This has not been tested.
The text changes.
N/A
> docs: clarify no texts available message

- src/server/api/schema.js
Perform SQL operations for copying a campaign within a transaction.
Individual steps (e.g. canned responses) of copying the campaign could fail while previous steps succeeded.
N/A
N/A
> fix: copy campaign in transaction

- src/api/schema.js
- src/api/types.ts
- src/containers/AdminCampaignStats/VanExportModal.tsx
- src/containers/AdminCampaignStats/index.jsx
- src/server/api/schema.js
- src/server/api/types.ts
- src/workers/exports/upload.ts
- src/workers/jobs/export-for-van.ts
- src/workers/jobs/index.js
Adds an export option tailored for uploading into VAN.
Stop-gap solution for full two-way sync.
Yes it does. @kohlee any thoughts on where it should live?
> feat: van export button

- migrations/20200715151038_load-external-id.js
- src/server/pg-compose/external-system.yaml
Quick fix to include external_id from VanID in the column config passed to van-fetch-saved-list, and to extract it from the resulting json array.
Fixes an earlier oversight.
Tested locally with live client credentials and database.
- [ x Bug fix (non-breaking change which fixes an issue)
> fix: include external id on van fetch saved list

- package.json
- src/workers/exports/gs-json.js
- src/workers/exports/s3.js
- src/workers/exports/upload.ts
- src/workers/jobs/index.js
- yarn.lock
Reverts politics-rewired/Spoke#704 until we can debug some of the data consistency issues
> Revert "fix: handle very large exports"

- src/workers/jobs/index.js
Somewhere in our refactors of exports we took out progress updates - this brings them back.
> fix: export progress

- src/server/routes/campaign-preview.js
Exclude soft-deleted interaction steps from the Script Preview.
This has been a long standing source of confusion.
N/A
N/A
> fix(script-preview): exclude soft-deleted interaction steps

- src/workers/jobs/index.js
Small refactor left over from debugging campaign export problems.
This is a little cleaner.
N/A
N/A
> refactor(export-campaign): use inline query over CTE and join

- src/server/api/errors.js
- src/server/api/schema.js
Fixes a bug where an admin trying to end a conversation from Message Review that they are not assigned fails with an authorization error.
Locally
> fix(end-conversation): auth error for non assigned admin

- migrations/20191001115601_use_timezone_for_assigment.js
- migrations/20191113095008_add-escalation-tags-to-assignment-views.js
- migrations/20191115161047_archive-campaign-contact-CAREFUL-INDEX-MODIFICATION.js
- migrations/20191210144116_add_campaign_contact_tag_indexes.js
- migrations/20200215125018_add-texter-level-to-user-organization.js
- migrations/20200510204235_external_list.js
Fix buggy migrations.
Quick look through for where an index got dropped. Nothing was dropped, we did a table -> view switcheroo.
Locally:
```sh
yarn knex migrate:down && yarn knex migrate:up && yarn knex migrate:up
```
> fix: fix up/down migrations

- migrations/20200923075051_trollbot_graphile_job.js
- src/config.js
- src/containers/AdminTrollAlarms/index.jsx
- src/server/api/schema.js
- src/server/tasks/troll-patrol.ts
- src/server/worker.ts
Manage TrollBot with `graphile-worker`.
This is another step towards centralized job management and provides better error reporting.
N/A
N/A
> refactor(trollbot): manage trollbot with graphile worker

- src/workers/jobs/index.js
Delete assignment breaks the opt out foreign keys! We can just leave them hanging around at 0.
> fix(assignment): dont delete assignments, breaks opt out foreign keys

- src/components/AssignmentTexter.jsx
- src/containers/AssignmentTexterContact/index.jsx
- src/network/utils.ts
This PR changes the way tags are added to contact conversations, refactoring the handleApplyTags method in the AssignmentTexterContact component so that it runs the tagContact mutation when the user clicks the 'save' button, as opposed to running it as an async function when the user clicks the 'send' button
Currently, tags are added to conversations when a user clicks send message within the AssignmentTexterContact component. If a user applies a tag and navigates away from the component without sending a message, the tag isn't applied.
Behaviorally. 
- [ x] Bug fix (non-breaking change which fixes an issue)
> Fix: Add Tag to Contacts on Save

- src/server/index.js
Structured logging for Express errors with context.
Turn un-actionable log clutter into maybe-actionable logs. It also cuts down on DataDog billing because `console.log()` produces one log event for each line of the message while Winston creates just one.
Specifically to debug:
```
BadRequestError: request aborted
```
Spoke runs fine with this addition. I have not been able to throw an error that would get caught, however.
```js
// From: https://expressjs.com/en/guide/error-handling.html
app.get('/', function (req, res) {
throw new Error('BROKEN')
})
```
results in an uncaught exception rather than a winston log:
```
uncaughtException: this.socket.cork is not a function","stack":"TypeError: this.socket.cork is not a function
```
This could just be a local config/dev mode issue though.
N/A
> feat: log express errors with winston logger

- src/server/api/schema.js
This pr restores soft delete function for tags
This will allows users to re-create tags with the same title as tags that had previously been created and deleted, which still exist in the database and are constrained by the tag_title_organization_id_unique index. 
See this [request](https://secure.helpscout.net/conversation/1319477803/2931?folderId=4118236)
Behaviorally.
> feat(tags): restore soft delete

- src/server/tasks/export-campaign.ts
A pr to remove catches in helper functions for campaign export jobs
We've been swallowing errors in a handful of helper functions used when exporting campaigns. Removing the catch will allow the job to fail gracefully and close streams correctly
BDD
- [ x] My commit messages follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).
> fix(exports): rm catches in helper functions

- src/components/AssignmentTexter.jsx
- src/config.js
Allow configuration of client send delay via envvar.
Better control over rate limiting.
N/A
N/A
N/A
> feat: configurable send delay

- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm.jsx
Adds the ability to "Paste Block" on an initial message, which overwrites the whole script. This is behind a warning modal.
Closes https://github.com/politics-rewired/Spoke/issues/745.
Locally, all good!
> feat(campaign-edit): add copy block on root

- src/components/ScriptEditor.jsx
- src/components/ScriptLinkWarningDialog.tsx
- src/components/forms/GSScriptField.jsx
- src/components/forms/GSScriptOptionsField.jsx
- src/components/forms/lib.ts
- src/components/forms/utils.ts
This pr adds a ScriptLinkWarningDialog component that is displayed when a user tries to insert a generic link or short link into an interaction script. The dialog points the user towards the relevant docs, and prompts them to confirm and save the draft script, or close the dialog and re-edit the interaction script.
Per [ticket](https://www.notion.so/Add-bit-ly-warning-to-Script-Builder-2541c3eb0fde4c74b36dff579726f36d), this is part of our Final Spoke Features sprint
Behaviorally
- [x ] New feature (non-breaking change which adds functionality)
- [ x] My change requires a change to the documentation.
> feat(scripteditor): add short link warning

- src/api/types.ts
- src/components/IncomingMessageList/ConversationPreviewModal.jsx
- src/components/IncomingMessageList/MessageColumn/MessageList.tsx
- src/components/IncomingMessageList/MessageColumn/MessageOptOut.tsx
- src/components/IncomingMessageList/MessageColumn/MessageResponse.tsx
- src/components/IncomingMessageList/MessageColumn/index.jsx
- src/components/IncomingMessageList/MessageColumn/index.tsx
- src/components/IncomingMessageList/SurveyColumn/index.tsx
- src/global.d.ts
This PR switches from mixing CSS `height` directives with flexbox styling to using just flexbox.
This also converts some files adjacent to the changes to TypeScript.
The mix of flexbox and height styles cause display issues on some browsers (reported on Safari). This fixes those display issues.
Closes #778 
N/A
N/A
> fix: fix message review display in safari

- src/server/tasks/sync-campaign-contact-to-van.ts
Sync a canvass response with no `responses` for campaign contacts who have been texted but do not have associated question responses.
Messaging a contact is a canvass attempt and should be synced to VAN as such, even if no response was recorded.
Closes #784
Behavior of the updated query has been tested locally.
N/A
N/A
> fix(van): sync messaged contacts without question responses

- src/containers/AdminExternalSystemDetail/index.tsx
- src/containers/AdminExternalSystems.tsx
- src/routes.jsx
Adds an integration detail page linked to from the main integration list page.
This sets the stage for #773 and #797
None yet (future PRs will require documentation changes).
> feat: add integration detail page

- README.md
This PR adds two steps to the "Getting Started" instructions, one to install and start Postgres and one to create the `spokedev` database.
Before installing Postgres or creating the `spokedev` database, I got an error on the "Run the migrations" step about `spokedev` not existing. Before starting Postgres, I got an error on the  "Run in development mode" steps:
```
{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":5432,"level":"error","message":"unhandledRejection: connect ECONNREFUSED 127.0.0.1:5432","stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)"}
```
I added these steps while following the "Getting Started" instructions on my Mid 2012 MacBook Pro. I previewed the …
> docs(readme.md): add Postgres steps to "Getting Started" instructions

- src/containers/AdminAssignmentControl/AssignmentRow.jsx
Per [ticket](https://secure.helpscout.net/conversation/1386454285/3616?folderId=4118236), custom escalation tags aren't being fetched and can't be applied. 
It looks like the issue was introduced in this [commit](https://github.com/politics-rewired/Spoke/commit/238c468425e128f17bfa50f6a2e9d74b1f3bce95#diff-e662d8ec24e20d8a66a32a511cb5a72c815c3083acf495431cbbb7e76bc25d36L35-L118), where the linter overwrote some previous code. 
Fixes custom escalation tag application in the Assignment Control module.
- [ x] My code follows the code style of this project.
> fix(tags): restore escalation tag functionality in assignment row

- src/api/campaign.ts
- src/containers/AdminCampaignStats/CampaignStat.jsx
- src/containers/AdminCampaignStats/DeliverabilityStats.tsx
- src/containers/AdminCampaignStats/index.jsx
- src/lib/utils.js
- src/server/api/campaign.js
Add a simple summary of topline deliverability stats to the campaign detail page.
Should provide some quick answers for easy deliverability problems.
Locally.
> feat(campaign-detail-page): add message errors

- src/lib/utils.js
- src/server/api/campaign.js
Reduce `{ count: number }` object.
We were encountering the following error in production:
```json
{
"content": {
"message": "GraphQL error: Int cannot represent non 32-bit signed integer value: [object Object]",
"attributes": {
"path": [
"campaign",
"deliverabilityStats",
"errorCount"
],
"extensions": {
"code": "INTERNAL_SERVER_ERROR"
},
"level": "error",
"locations": [
{
"line": 7,
"column": 7
}
]
}
}
}
```
N/A
N/A
> fix: fix error count summation

- migrations/20210122105635_upsert-secrets.js
- package.json
- src/server/api/schema.js
- yarn.lock
Per @ben-pr-p, fix for an error introduced in #813, it removes writing to the non-existent operation_mode column in the database. Van Operation Mode is handled by the External System Resolver, but the write wasn't removed from the mutation after the change was implemented in the original PR.
Bug fix
> fix(vanoperationmode): remove operation mode key from external system mutations

- __test__/testbed-preparation/core.ts
- knexfile.env.js
- src/server/api/campaign.js
- src/server/api/lib/campaign.spec.ts
- src/server/api/lib/campaign.ts
- src/server/api/types.ts
- src/server/knex.js
Parse the `count` column returned by knex as an integer.
#863 fixed the shape mismatch in the reducer but didn't catch this string concatenation bug when there are multiple rows to reduce. Knex returns the count column as a string so the reducer was concatenating the numbers as strings rather than adding as integers. This resulted in very large numbers that surfaced via the GraphQL error:
```
GraphQL error: Int cannot represent non 32-bit signed integer value: 0135210601335033362
```
I believe this may also be related to the reports of the "Sync to VAN" button no longer working though I haven't been able to reproduce locally. Using React dev tools on production it seems like clicking the button is changing state correctly but the uncaught error is preventing the modal from rendering. The …
> fix: parse count as integer

- src/server/api/lib/interaction-steps.spec.ts
- src/server/api/lib/interaction-steps.ts
Mark any old interaction step trees as deleted when saving an entirely new tree (e.g. pasting a block at the root level).
Multiple live interaction step trees have caused a variety of problems. See #880 and #878
This has been tested locally and with unit tests.
N/A
N/A
> fix: delete old interaction step tree on save of new tree

- src/components/ScriptLinkWarningDialog.tsx
Update the article we link to on sending links in messages.
A more complete article has been added.
N/A
N/A
> docs: update 'sending links' article

- src/api/organization.ts
- src/api/schema.js
- src/containers/Settings/components/EditName.tsx
- src/containers/Settings/components/General.jsx
- src/containers/Settings/components/queries.ts
- src/server/api/schema.js
Allow organization owners to change the name of the organization.
This will cut down on many support tickets.
N/A -- self-explanatory.
> feat: support changing organization names

- README.md
pg-compose uses the prokind column, introduced in Postgres v11.
Ref: https://www.postgresql.org/docs/11/catalog-pg-proc.html
See https://github.com/politics-rewired/Spoke/issues/960#issuecomment-842665231
N/A
N/A
This PR is the documentation change.
> docs: document minimum postgres version

- schema-dump.sql
- update-dump.sh
Adds a dump of the Spoke schema.
This makes it easier to track changes to function bodies, among other SQL things.
`schema-dump.sql` was created, wasn't it?
N/A
N/A
> chore: add schema dump

- package.json
- yarn.lock
Use page size of 200 rather than 50.
See politics-rewired/pgc-ngp-van#8
N/A
N/A
N/A
> fix(van): update pgc-ngp-van for larger page size

- src/server/api/campaign.js
Boolean fix for Texters section readiness check.
N/A
> fix: fix texters section readiness check

- src/server/tasks/assign-texters.spec.ts
Fix invocation of test util.
`texterContactCount()` was updated in `master` after #973 branched.
See Circle CI results.
N/A
N/A
> test: fix test util usage

- src/containers/AdminBulkScriptEditor/index.jsx
Remove a duplicate word.
Duplicate words don't look so good.
N/A
N/A
N/A
> fix(copy): remove duplicate 'run'

- .versionrc.js
Sign Spoke releases  by default.
This can be disabled with:
```sh
yarn release --sign=false
```
Git signing is good practice and easy to set up automatically.
N/A
N/A
> chore: sign releases

- src/components/NotificationCard.tsx
- src/containers/Settings/components/Review10DlcInfo.tsx
10DLC registration deadlines have been pushed back by carriers. Update the customer-facing notice accordingly.
Incorrect/past dates may be confusing.
N/A
N/A
> fix: update 10dlc registration dates

- src/server/tasks/filter-landlines.ts
Filter landlines filter voips as well. 
Although some voips are textable, many are not, and it seems as compliance becomes more of an issue and entities seem to be paying attention to overall error rate it's better to err on the safe side.
> fix: filter landlines remove voips

- src/server/models/index.ts
Fix the typing of `r.knex`.
Proper typing is important.
N/A
N/A
N/A
> chore(ts): fix knex typing

- package.json
- src/global.d.ts
- src/lib/attributes.ts
- src/lib/charset-utils.ts
- src/lib/scripts.ts
- src/server/api/lib/send-message.ts
- src/server/api/schema.js
- src/server/tasks/retry-interaction-step.ts
- src/server/worker.ts
- yarn.lock
Add task for retrying interaction step server-side.
Provide a targeted way of addressing user errors.
This has not been tested.
N/A
N/A
---
- https://app.asana.com/0/0/1201606896748811
> feat: add retry-interaction-step task

- src/containers/AdminCampaignEdit/sections/CampaignContactsForm/components/SelectExcludeCampaigns.tsx
Update campaign upload exclusion disclaimer copy.
Dialing it in a little bit more.
N/A
N/A
N/A
> fix: update disclaimer copy

- src/server/api/assignment.js
- src/server/lib/graphql.ts
Limit the fields fetched from the database to only those requested by the GraphQL query.
[`getTexterAssignmentContactIds`](https://github.com/politics-rewired/Spoke/blob/a0e8faf3e4f45342d7e3d02e354146b72252d354/src/containers/TexterTodo.jsx#L178-L189) only requires contacts' IDs but must transfer the entire `campaign_contact` row over the wire from the database. This is slow and ties up a database connection during data transfer.
This change looks at the GraphQL query's selection set and, if only "simple" fields are requested, limits the database query's `SELECT`.
Interestingly, it seems like `getTexterAssignmentContactIds` is the only place this resolver is ever actually invoked. Using regex `/^[ ]*contacts[\( ].*\{/` we find two results. The `AdminReplySender` result is …
> perf: limit contact field selection

- src/components/AuthzProvider.tsx
- src/containers/AdminCampaignEdit/components/SectionWrapper.tsx
- src/containers/AdminCampaignEdit/index.jsx
- src/containers/AdminCampaignList.jsx
- src/containers/AdminCampaignStats/index.jsx
- src/containers/CampaignList/CampaignList.tsx
- src/containers/CampaignList/CampaignListLoader.tsx
- src/containers/CampaignList/CampaignListRow.tsx
- src/containers/CampaignList/index.jsx
- src/server/api/lib/send-message.ts
Adds checking permissions of all current user roles to [`AuthzProvider.tsx`](https://github.com/politics-rewired/Spoke/blob/main/src/components/AuthzProvider.tsx)
Components that reference [`AuthzProvider.tsx`](https://github.com/politics-rewired/Spoke/blob/main/src/components/AuthzProvider.tsx) to check permissions currently can only access permissions for the Admin user role. To check other permissions, a separate GraphQL query is needed.
> chore: expand authz context for all user roles

- src/components/AuthzProvider.tsx
Fixes page render when using the new hook added in [`AuthzProvider.tsx`](https://github.com/politics-rewired/Spoke/blob/main/src/components/AuthzProvider.tsx)
This restores previous functionality. #1081 introduced an error on render due to the use of a hook with an early return.
> fix: fix authzprovider hook

- src/api/campaign-contact.ts
- src/components/IncomingMessageFilter.jsx
- src/containers/AdminIncomingMessageList/index.jsx
- src/lib/attributes.ts
- src/lib/phone-format.ts
- src/schema.graphql
- src/server/api/conversations.js
Allow searching for a contact using phone number, just number, first name + number, full name +
number are all valid and acceptable input values
Fixes #1067 
Tested with multiple different names, and styles. 
Requires a small change in user doc, letting the user know they can search using numbers.
> feat(message filter): allow searching using cell phone number

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/lint-pr.yml
Drop steps from template that are taken care of by the `lint-pr.yml` workflow.
If the PR adheres to the semantic PR spec then we already know the type of change.
From the Husky commit hook we know that the commit messages follow the conventional commit standard.
From the ESLint commit hook we know that the code follows the repository's code style.
N/A
N/A
N/A
> chore: update pr template

- src/components/AssignmentSummary/index.tsx
- src/components/SendButton.tsx
- src/containers/AssignmentTexterContact/NoMessagesIcon.tsx
- src/containers/Home/index.tsx
This fixes the use of custom contexts within Spoke. Included this are a few fixes to custom theming.
We should be using common pattern for accessing contexts. 
N/A
N/A
> fix: fix use of react contexts

- src/server/api/lib/message-sending.js
Before updating status of an assignment, check if message contains
common optout language, if found, close the conversation, and optout
the cell number
Fixes #1089
Tested locally
NA
NA
> feat(optout): automatically optout for common optout language

- src/containers/AdminCampaignEdit/sections/CampaignContactsForm/components/UploadResults.tsx
- src/containers/AdminCampaignList.jsx
- src/server/api/lib/campaign.ts
Fixes #678 
Fixes #678 
Tested locally
> fix: don't create a contacts upload job if contacts doesn't exist 

- migrations/20210227101808_instance-settings.js
- migrations/20210526012107_add-phone-object-to-van-sync.js
This fixes errors preventing two down migrations from running.
Down migrations should run.
N/A
N/A
> fix: fix errors in down migrations

- .eslintrc.js
- src/containers/AdminAssignmentControl/AssignmentRow.tsx
- src/containers/AdminTagEditor/ConfirmationStepsEditor.jsx
- src/containers/AdminTagEditor/TagEditorList.jsx
- src/containers/CampaignList/AssignmentHUD.tsx
- src/containers/CampaignList/CampaignListRow.tsx
Upgrade chips to MUI v4.
Closes #1166.
N/A
N/A
> chore(mui): upgrade chips

- src/containers/AdminCampaignEdit/components/SectionWrapper.tsx
- src/containers/AdminCampaignEdit/index.jsx
- src/containers/UserMenu/index.tsx
- src/styles/mui-theme.ts
Tidy up console deprecation warnings for MUI.
It's easier to debug when there is less noise in the console.
N/A
N/A
> chore: tidy up mui deprecation warnings

- src/containers/AdminCampaignEdit/sections/CampaignContactsForm/index.tsx
- src/server/api/lib/edit-campaign.js
This PR does two things:
1. Trims whitespace around column names
2. Fixes error display in the client
Closes #1133.
N/A
N/A
> fix: fix csv header validation

- src/containers/CampaignList/AssignmentHUD.tsx
This fixes how the label is passed to the Chip component in MUI v4.
#1166 missed this.
N/A
N/A
> fix: fix how label is passed to chip

- src/containers/AdminIncomingMessageList/components/IncomingMessageActions.tsx
Replace the Select component with an Autocomplete.
Being able to search for texters by name/email is important for larger organizations.
N/A
> fix: use autocomplete for texter select

- migrations/20220516035046_template-campaigns.js
- schema-dump.sql
This adds schema changes to support template campaigns.
This also includes a fix for `assignable_campaign_contacts`, which was never updated after the tag -> all_tag transition, as a side effect.
Part 1 of _n_ for #1181.
N/A
N/A
> chore(template-campaigns): add schema changes

- src/components/forms/GSScriptOptionsField.jsx
This updates tooltip use for MUI v4.
This was missed in #1159.
N/A
N/A
> fix: fix scripts tooltip

- src/server/tasks/queue-autosend-initials.ts
This preserves `run_at` for autosend message tasks so they cannot continually be pushed into the future.
On conflict approach taken from https://stackoverflow.com/a/42217872
`UNION` does not work with JSON so this also limits the returned table to only required columns.
Closes #1246
This has been tested locally to ensure result set is the same and `run_at` is not modified.
N/A
N/A
---
- https://app.asana.com/0/0/1202377870515168
> fix(autosending): preserve run_at when queuing messages

- src/containers/AdminExternalSystems.tsx
This fixes display of errors from external system-related mutations.
The apollo-client upgrade changed behavior for GraphQL errors. They're no longer thrown automatically client-side. Instead we must check the response object for `errors` property.
N/A
N/A
> fix(external-system): fix displaying errors

- src/server/tasks/queue-autosend-initials.ts
This fixes an issue causing autosend initials tasks to be queued further into the future than they should be.
The math for setting `run_at` on the `retry-interaction-step` tasks assumes that row_number will return a value less than or equal to the number of messages to queue in a minute.
However, row_number is a window function and any ordering must be specified in the `OVER` clause, not the `select`'s. This meant that row_number ran on all matching campaign contacts _before_ the result set was ordered, meaning that while the CTE returned the correct number of rows, the row number values it returned could be as high as the total number of matching campaign contacts.
To fix this, this PR first selects and orderers matching contacts and _then_ calculates the row_number on that CTE.
Another …
> fix(queue-autosend-initials): fix row_number order by conflict

- src/containers/AdminIncomingMessageList/components/IncomingMessageFilter.tsx
Manually setting a timeout and clearing it managed to stay a letter better. Instead use `useDebounce` that's used in other parts of message filter
Fixes #1221
> fix: fix contact filters being a letter behind

- src/components/AssignmentTexter.jsx
- src/containers/AssignmentTexterContact/index.jsx
- src/styles/mui-theme.ts
This reverts commit beb7287c0d7aa860de2390281f0fd39ae7c415f1.
Additional texter-facing documentation is required.
n/a
n/a
@politics-rewired/organizing will update documentation ahead of new merge.
> revert(texter conversation): revert update button in line with design doc

- libs/spoke-codegen/src/graphql/session.graphql
- libs/spoke-codegen/src/graphql/super-admin-people.graphql
- libs/spoke-codegen/src/graphql/texter-dashboard.graphql
- src/components/AdminDashboard.jsx
- src/components/AuthzProvider.tsx
- src/components/Navigation.tsx
- src/components/SuperAdminDashboard.tsx
- src/components/TexterDashboard.jsx
- src/components/TopNav.tsx
- src/containers/AdminPeople/AdminPeople.tsx
- src/containers/SuperAdminPeople.tsx
- src/containers/UserMenu/index.tsx
- src/routes.jsx
Add a superadmin page where a superadmin can manage people from all orgs.
Fixes #783 
Tested Locally
Documentation will be required for this page. 
---
- https://app.asana.com/0/0/1202732920779586
> feat: add a superadmin page, add people management

- package.json
- src/config.js
- src/server/app.ts
Add CORS policy.
Best practices.
N/A
N/A
> feat: add cors

- src/client/offline.html
This updates the offline page with @politics-rewired/organizing feedback
Update #1411
Rendered page locally.
> feat: update offline page text

- .versionrc.js
List chore tasks in changelog, more visibility on changes that need to be looked out for.
Listing chores add more visibility on invisible changes that have happened allowing people testing to look out for those changes.
Tested locally using `--dry-run`
> chore: list chore in changelog and release docs

- src/containers/AdminTrollAlarms/index.tsx
This fixes filtering trollbot alarms by a specific token.
Trollbot is significantly easier to use when token filtering is possible.
> fix(trollbot): fix token search

- schema-dump.sql
Update schema following #1446.
The schema dump should be up to date.
N/A
N/A
N/A
> chore: update schema dump

- src/server/api/campaign.js
- src/server/routes/campaign-preview.ts
This fixes generating a script preview URL for template campaigns.
Closes #1450.
N/A
N/A
---
- https://app.asana.com/0/0/1203111210578372
> fix: support script preview for template campaigns

- package.json
- yarn.lock
This removes the `pgc-ngp-van` package.
This should have been removed in #1403 .
N/A
N/A
> chore: remove pgc-ngp-van package

- src/server/tasks/ngp-van/sync-campaign-contact-to-van.ts
> fix: fix van truncated date alias

- libs/spoke-codegen/src/graphql/campaign-builder.graphql
- migrations/20221007115438_default-messaging-service.js
- schema-dump.sql
- src/api/messaging-service.ts
- src/containers/AdminCampaignEdit/sections/CampaignMessagingServiceForm.tsx
- src/schema.graphql
- src/server/api/lib/campaign.ts
- src/server/api/messaging-service.ts
- src/server/api/schema.js
This adds support for setting a default messaging service.
Closes #1287.
**Migration backfill correctness**
Pre-migration:
```
spoke_temp# select messaging_service_sid, organization_id, active from messaging_service order by organization_id;
┌─────────────────────────┬─────────────────┬────────┐
│  messaging_service_sid  │ organization_id │ active │
╞═════════════════════════╪═════════════════╪════════╡
│ foobar                  │               1 │ t      │
│ old-telnyx-service      │               1 │ f      │
│ why-not-have-two        │               2 │ t      │
│ a-second-active-service │               2 │ t      │
└─────────────────────────┴─────────────────┴────────┘
(4 rows)
```
Post-migration
```
spoke_temp# select messaging_service_sid, …
```
> feat: support setting default messaging service for organization

- .eslintrc.js
Prevent any new FloatingActionButtons from coming from MUI v0.
@ajohn25 already upgraded the components as part of #1228.
Closes #1381.
Linting passes -- no other changes.
N/A
N/A
---
- https://app.asana.com/0/0/1202879016350914
> chore(mui): upgrade floating action buttons

- .eslintrc.js
Prevent any new Tabs from coming from MUI v0.
Closes #1391
Linting passes.
N/A
N/A
---
- https://app.asana.com/0/0/1202879049312720
> chore(mui): upgrade tabs

- .eslintrc.js
Prevent any new Badges from coming from MUI v0.
Closes #1374.
Linting passes.
N/A
N/A
---
- https://app.asana.com/0/0/1202879013876877
> chore(mui): upgrade badges

- .eslintrc.js
- libs/spoke-codegen/src/graphql/session.graphql
- src/api/user.ts
- src/components/QuestionResponseConfig/index.tsx
- src/components/TopNav.tsx
- src/containers/AdminCampaignEdit/sections/CampaignContactsForm/components/ExternalSystemsSource.tsx
- src/containers/UserMenu/components/OrganizationItem.tsx
- src/containers/UserMenu/index.tsx
- src/schema.graphql
This updates `Avatar` and `Popover` components to MUI v4. 
It also includes conversion from class-based to functional React components where necessary for styling Avatars via `useStyles()` hook.
Closes  #1378
Closes #1392
</td><td>
N/A
---
- https://app.asana.com/0/0/1202879106865551
- https://app.asana.com/0/0/1202879117473855
> chore(mui): update avatar and popover

- migrations/20220608191014_faster-get-trollbot-matches.js
- migrations/20220930011755_add-organization-autosending-mps.js
This names four currently unnamed knex migrations.
For consistency with the rest of the migrations and to clean up eslint warning.
Migrations run.
N/A
N/A
> style: fix no-unnamed-functions eslint warnings

- .eslintrc.js
> fix: fix eslint config

- src/server/api/lib/campaign.ts
Use partial index `campaign_contact_partial_assignment_id_index`
**Before**
Plan: https://app.pgmustard.com/#/explore/39fef656-fff4-47a2-9be8-69d6f35e8b7f
Total time: 1,195ms
Sum of buffers: 485 MB
**After**
Plan: https://app.pgmustard.com/#/explore/fc00b8d4-a10a-4e3b-87cd-d4a8ea6a74ce
Total time: 30ms
Sum of buffers: 304 KB
N/A
N/A
> perf: use partial index for deliverability stats

- .versionrc.js
This adds refactor and perf commits to the backend changes section of the changelog.
Increase visibility for backend changes. See the empty changelog for [5.0.0-rc.1](https://github.com/politics-rewired/Spoke/releases/tag/v5.0.0-rc.1) that included an important performance improvement.
Tested locally using --dry-run
> chore(changelog): add refactor and perf commits to backend section

- src/server/api/campaign.js
This excludes opted out contacts from the "Initials to Send" count.
Fixes #1495.
N/A
N/A
---
- https://app.asana.com/0/0/1203231755887337
> fix: exclude opt outs from initials to send count

- src/containers/AdminCampaignEdit/sections/CampaignContactsForm/components/CSVForm.tsx
This fixes grammar in the contact upload copy.
Closes #1493.
This has been tested locally; see screenshot
N/A
---
- https://app.asana.com/0/0/1203231217688806
> fix: add missing space and period

- libs/gql-schema/campaign-contact-tag.ts
- libs/gql-schema/campaign-contact.ts
- libs/gql-schema/schema.ts
- libs/spoke-codegen/src/graphql/message-review.graphql
- package.json
- src/components/TagSelector/index.jsx
- src/containers/AdminIncomingMessageList/components/IncomingMessageList/SurveyColumn/ManageSurveyResponses.tsx
- src/containers/AdminIncomingMessageList/components/IncomingMessageList/SurveyColumn/ManageTags.jsx
- src/containers/AdminIncomingMessageList/components/IncomingMessageList/SurveyColumn/ShowTags.tsx
- src/containers/AdminIncomingMessageList/components/IncomingMessageList/SurveyColumn/index.tsx
- src/containers/AssignmentTexterContact/ApplyTagDialog.jsx
- src/containers/AssignmentTexterContact/index.jsx
- src/containers/TexterTodo.jsx
- src/schema.graphql
- src/server/api/campaign-contact-tag.ts
- src/server/api/campaign-contact.js
- src/server/api/schema.ts
- src/server/api/types.ts
Show tags applied, and the tagger details in the conversation preview window
Fixes #1143 
Tested locally
> feat(message review): show tag and tagger details

- src/server/app.ts
Move metrics middleware earlier in the stack to capture more of the call cycle
For [SLOs](https://www.notion.so/rewiredcoop/v1-0-Spoke-Switchboard-SLOs-dfaa26f588c0461992c9ab41805355e4), we should capture as closely as possible the behavior of the app as a whole; this will prevent failures such as `bodyParse` or `passport` failures not showing up in request & SLO metrics.
https://app.asana.com/0/1203400245623227/1203684096178791/f
No.
N/a.
N/a.
> fix(instrumentation): move metrics middleware earlier in the stack to capture more of the call cycle

- src/components/QuickSearchToolbar.tsx
- src/containers/AdminAssignmentControl/components/AssignmentRow.tsx
- src/containers/AdminAssignmentControl/index.tsx
- src/containers/AdminAssignmentControl/types.ts
- src/server/api/root-mutations.ts
Fixing an issue that showed up in helpscout and fixing other small issues in the same area. See commit messages for more detail.
- Root cause fix for https://secure.helpscout.net/conversation/2252793441/8846/ https://rewiredcoop.slack.com/archives/C02L56CP92A/p1684939561227669
- Also realized there's no way to clear escalation tags while fixing this, so fixed that, too. 
- Some small styling changes, see screenshot
locally
OLD:
NEW:
> fix: cannot save assign control max count

- src/components/Registration10DLCWarningText.tsx
This updates copy for the 10DLC warning
Mid June @politics-rewired/spoke-client feedback on #1620
> chore(10dlc): mid june notification update

- libs/gql-schema/campaign.ts
- migrations/20221125080945_add_column_mapping_to_campaign.js
- package.json
- src/containers/AdminCampaignEdit/index.jsx
- src/containers/AdminCampaignEdit/queries.ts
- src/containers/AdminCampaignEdit/sections/CampaignContactsForm/components/ConfigureColumnMappingDialog.tsx
- src/containers/AdminCampaignEdit/sections/CampaignContactsForm/index.tsx
- src/schema.graphql
- src/server/api/campaign.js
- src/server/api/lib/campaign.ts
- src/server/api/lib/contact-list.ts
- src/server/api/lib/edit-campaign.js
- src/server/api/lib/opt-out.ts
- src/server/api/types.ts
- yarn.lock
Allow uploading arbitrary CSVs and allowing column remapping 
Fixes #1156 
Tested locally with different variants of CSVs
---
- https://app.asana.com/0/0/1203491785595177
> feat!: allow uploading arbitrary csvs

- migrations/20230317094055_update_default_notification_frequency.js
Update the default notification frequency to DAILY. Also update the default for all existing users to be DAILY.
Fixes #1561 
Tested locally
> chore(notification frequency): update default to DAILY

- README.md
This adds instructions on how to create a new knex migration to the README
Easier developer onboarding
N/A
> docs(readme): update migration instructions

- src/containers/AdminCampaignEdit/sections/CampaignContactsForm/components/ConfigureColumnMappingDialog.tsx
This updates the csv mapping dialog to reference the "cell phone" header consistently
Slack discussion https://rewiredcoop.slack.com/archives/C04L6F00LLA/p1690312820761159
N/A
> chore(csv mapping): update required headers copy

- CHANGELOG.md
> chore: Add changelog for missing 6.1.3 release

- src/containers/AdminCampaignEdit/sections/CampaignCannedResponsesForm/index.tsx
This restores the default sorting for adding new canned responses to alphabetical sorting.
Texters and admins who aren't aware of the canned response reordering feature still expect alphabetical sorting by default.
> fix(canned responses): default to alphabetical sorting

- src/containers/AdminCampaignEdit/sections/CampaignContactsForm/components/ConfigureColumnMappingDialog.tsx
This adds a label to the autocomplete for csv mapping
The function of the field isn't clear to users without a label
See screenshots from the original PR - looks the same now 😁 #1540
> fix(csv mapping): add autocomplete label

- schema-dump.sql
just ran update-dump.sh off of main to get us up to date
> chore: run update schema dump

- src/containers/AdminDashboard/components/NotificationCard.tsx
This reverts commented blocks of code to simply unreachable code.
This makes diffs for future work cleaner.
N/A
N/A
> style: prefer unreachable code to comment blocks
