politics-rewired/Spoke

- dev-tools/reapply-message-reports.sql
- src/server/api/lib/twilio.js
- src/server/index.js
I have tested the select and update queries limited to the last 20 minutes within transactions that were then rolled back.
> Clean up Twilio's message report handler

- package.json
- src/components/App.jsx
- src/components/CampaignInteractionStepsForm.jsx
The upgrade was to allow case-sensitive type names. The upgrade introduced multiple bugs, specifically around how onChange was passed.
> Revert react-formal upgrade

- README.md
- docs/HOWTO_MIGRATE_FROM_MOVEON_MAIN.md
These docs include the main differences up to this point and the migration steps themselves.
Rendered doc [here](https://github.com/politics-rewired/Spoke/blob/politics-rewired/add-moveonorg-migration-doc/docs/HOWTO_MIGRATE_FROM_MOVEON_MAIN.md).
> Add docs for migrating from MoveOnOrg/Spoke.

- src/server/api/schema.js
The replaceAll approach produced incorrect outputs in certain conditions. Say we have two domains: adomain.com domain.com and our target domain is adomain.com. Using the replaceAll approach, the text "Go to https://adomain.com/link" will have both matching domains replaced with the target domain and will end up as "Go to https://aadomain.com/link". Instead, we want to use a more targeted regex to match on and replace the extact host portion of the URL.
> Reduce scope of regex to specific domain

- src/server/api/schema.js
The previous RegEx mixed syntax for raw RegEx construction and construction using `Regex()`.
With the new RegEx there are only two match groups (as it should be): the text before the domain
and the text after the domain.
> fix: construct and use RegEx correctly

- package.json
- src/server/index.js
This requires 2 new environment variables to actually run: `DD_AGENT_HOST` and `DD_DOGSTATSD_PORT`.
> Add datadog support via dogstatsd

- src/api/schema.js
- src/components/IncomingMessageList/MessageColumn/MessageList.jsx
- src/components/IncomingMessageList/index.jsx
- src/components/MessageList.jsx
- src/containers/AdminIncomingMessageList/index.jsx
- src/server/api/campaign-contact.js
- src/server/api/conversations.js
- src/server/api/lib/twilio.js
- src/server/api/lib/utils.js
- src/server/api/message.js
- src/server/api/schema.js
The `conversations()` doesn't use the `utc` argument so I just removed it.
> fix: use timezone-aware logic everywhere

- .ebextensions/03_fix_eb_permissions.config
node-gyp now fails to run with the file permissions on EB. This script will set ownership of /tmp
to allow node-gyp to run.
See https://stackoverflow.com/a/49986304
> build(elastic-beanstalk): fix eb dir permissions

- src/containers/AssignmentTexterContact/ApplyTagButton.jsx
- src/containers/AssignmentTexterContact/index.jsx
Changes:
- Automatically open tags dropdown on focus so texter can see available tags
- Add an escalate button that adds the Escalate tag, identified via title = 'Escalate(d)'
- Persist tag state between dialog open and closes
- Apply tags when skip reply is clicked
- Add option to apply tags without sending the message if a not assignable tag is added
> Fix texter tags ui

- src/config.js
- src/server/knex.js
This officially drops support for other database engines. It has been tested with DATABASE_URL as
well as DB_HOST, DB_PORT, DB_NAME, DB_USER, and DB_PASSWORD.
> chore: support only postgres

- package.json
There is no reason it should be pegged to 8.10.
> build: relax node version requirements

- yarn.lock
This was missed in 9701d1ebc30287c96f74eb404106adde95c20b21
> build: add missing slack entries to yarn.lock

- migrations/20190822080351_immutable_quesiton_responses.js
This migration implements immutable question responses
by renaming question_response to all_question_response,
creating a view named question_response, and binding
triggers such that queries against question_response
such that updates, inserts, and deletes at the question_response
view leave a record of modification in the all_question_response
table.
Importantly, the migration can be run and rolled back without any
loss of fresh data, but rolling back a migration will delete
the historical records of previous question responses, since
it deletes the columns that allow one to distinguish between an old
and new question response.
In the future, if the number of old question responses begins to
slow down queries, modifying indexes on question_response to
be partial – only on is_deleted = …
> feat(immutable-question-response): migration

- src/server/routes/graphql.js
This moves the `!isProduction` check before the graphqlExpress route is mounted
> feat(graphql): add mocks only in non-production environments

- src/containers/AdminCampaignEdit.jsx
- src/server/api/schema.js
This was perhaps due to how lodash difference handles string vs int differences
> fix(teams): assign teams to campaign

- src/server/api/lib/twilio.js
Null characters are [already stripped from the message text itself](https://github.com/politics-rewired/Spoke/commit/26bbe6007fee737bb03ae4b2aaeaaa80d9cb6e2d), but not the raw service response. Add a
defensive fix to remove null characters there as well.
> feat(twilio): add defensive fix for null characters in database

- migrations/20190918124706_fix_default_service_response.js
- src/server/api/lib/message-sending.js
- src/server/api/lib/nexmo.js
- src/server/api/lib/twilio.js
- src/server/api/schema.js
The `service_response` field should be a stringified array of service response payloads (each a JSON
object itself). However, this field is used differently throughout the codebase. This standardizes
its usage.
Query to find find sent messages:
```sql
select
REGEXP_REPLACE(service_response, 'undefined(.*)', '[\1]') as new_response_array
from message
where service_response like 'undefined%'
limit 1;
```
Query to fix sent messages:
```sql
update message
set service_response = REGEXP_REPLACE(service_response, 'undefined(.*)', '[\1]')
where service_response like 'undefined%';
```
Untested query to fix single-element records (only happens if using the `/send-replies` admin debug route):
```sql
update message
set service_response = REGEXP_REPLACE(service_response, '{(.*)}', '[{\1}]')
where …
```
> fix: standardize service_response

- src/server/routes/utils.js
Currently, Datadog network availability monitors do not catch application errors due to database inaccessibility as `/` does not require any database queries if there is no user session.
> feat(monitoring): add healthcheck endpoint

- src/containers/AssignmentTexterContact/index.jsx
Commit ecb2280f535ba7c47bc9d809f35b54ad2a131310 had a typo, using `lenth` instead of `length`.
> fix: prevent empty tagConversation mutations

- dev-tools/backfill-timezones.js
- migrations/20191001111008_add_contact_timezone.js
- migrations/20191001115601_use_timezone_for_assigment.js
- package.json
- src/server/api/assignment.js
- src/server/api/campaign-contact.js
- src/server/api/schema.js
- src/server/knex.js
- src/server/models/campaign-contact.js
- src/workers/jobs.js
Replace use of timezone_offset with named timezone, moving offset computation to trusted, DST aware implementations like Postgres's time zone functions and `moment-timezone`.
This one is a bit tricky to migrate – in order to be deployed without downtime, the first migration needs to be run (add the new column), then the backfill script, and then the code deploy, and then the second migration (remove the old column).
The backfill script could take a while if campaign_contacts is large, and several things could be done to make it faster. Specifically, `zip` is currently unindexed on `campaign_contact`, which means that each update as written will require a full table scan on `campaign_contact`.
Does that merit adding an index on zip concurrently and removing it when the backfill script is …
> refactor: use named timezone field instead of timezone_offset

- src/workers/jobs.js
The message export loop was exiting early because campaign_contact.id was not ordered. This was fixed in the `processContactsChunk()` query a while ago, but not `processMessagesChunk()`.
> fix(exports): order cte

- migrations/20191007135724_messaging_service_type.js
- package.json
- src/server/api/lib/twilio.js
- yarn.lock
This is part one of a set of changes to add Numbers SMS/Switchboard support. The next phase will add service selection logic (replacing use of `DEFAULT_SERVICE` alone) and the final phase will add the SMS/Switchboard service.
A few things to note:
- Knex 0.18+ uses native Promises and no longer passes a Promise argument to migrations/seeds.
- The additional index on messaging_service_stick allows us to replace a few unions with a join
- Message sending has been tested with this on a staging server using Twilio
> feat: switchboard

- src/server/api/lib/twilio.js
Fixes error:
```json
{"status":400,"message":"Error sending message 32Media urls:  are invalid. Please use only valid http and https urls","code":21620,"moreInfo":"https://www.twilio.com/docs/errors/21620","level":"error","timestamp":"2019-10-11T19:03:13.550Z"}
```
https://www.twilio.com/docs/sms/send-messages#include-media-in-your-messages
> fix(twilio): pass emtpy array rather than undefined to twilio

- src/server/api/assignment.js
If we are outside of a campaign's texting hours, and a contact's zip is null, `contact_is_textable_now` will return null. 
This fixes it by checking for distinction with true
> fix: contact_is_textable_now can return null

- src/lib/timezones.js
- src/server/api/assignment.js
For test campaign:
```
spoke_prod=> select count(*), timezone, message_status from campaign_contact where assignment_id = 75689 group by 2, 3;
┌───────┬─────────────────┬────────────────┐
│ count │    timezone     │ message_status │
├───────┼─────────────────┼────────────────┤
│    14 │                 │ needsMessage   │
│     1 │ America/Chicago │ messaged       │
│     9 │ America/Chicago │ needsMessage   │
└───────┴─────────────────┴────────────────┘
(3 rows)
```
On production, `Send Later: 9`
With changes, `Send Later: 23`
> fix: timezone issues

- src/config.js
- src/server/api/lib/message-sending.js
This addresses two problems:
1. fakeservice was being used whenever DEFAULT_SERVICE was unset
2. fakeservice was returning an incorrectly formed service record
For clients with DEFAULT_SERVICE unset, fakeservice was being used and was failing.
> fix: fix service selection behavior

- src/containers/UserEdit.jsx
- src/server/auth-passport.js
- src/server/local-auth-helpers.js
There are two differences between this PR and #334 
- Use `reject(new Error(...))` within the `AuthHasher` callbacks rather than throwing the error.
- Fix "Change Password" functionality from user's profile page. The change password dialog contains a nested `UserEdit` component that causes a previously-unaccounted-for `props.data` refresh in the parent
I have tested this locally with as many combinations of login, signup, password reset, and change password as I can think of.
> feat: display local login errors

- src/server/api/schema.js
Looks like the global flag is respected in the cacheable data sections for create / remove opt out queries – this was the only place opt outs were invariantly organization scoped
> fix: send message opt out query should respect global opt out toggle

- src/components/TexterRequest.jsx
- src/server/api/schema.js
Previously, we squashed errors from an external assignment request service. We now throw those
up the call stack. The client now handles GraphQL errors correctly as well.
> feat: improve assignment request error handling

- src/workers/jobs.js
The messages export was turning up blank in situations where the first 1000 contacts, ordered by id, had not been messaged yet – the loop then returned 0 rows and thought it was time to stop.
This fixes the problem by ensuring we only look for messages for contacts that have been messaged
> fix: messages export blank

- src/workers/exports/s3.js
When using AWS S3 exports authenticated by an EC2 role (as is the case with Elastic Beanstalk), we
need to use the async version of getSignedUrl. The sync version does not wait for credentials to be
fetched asynchronously (as is the case when assuming a role) and the operation fails.
See aws/aws-sdk-js#2166 for more information.
> fix(s3): use async method to support role-based auth

- src/server/api/conversations.js
This shows some modest but not really enough improvements – although it's now using the partial index, it's running that large partial index scan `n` times, where `n` is the number of campaigns that match the campaign criteria
We can figure out more substantial improvements later
> feat: include archived condition on incoming message review query

- src/server/api/assignment.js
- src/server/api/lib/alerts.js
- src/server/api/schema.js
Making external HTTP requests within a PG transaction can lead to program deadlock if the remote
service does not respond in a timely manner.
> feat: add timeouts to outbound http requests

- src/server/api/lib/assemble-numbers.js
Spoke should return a 200 for inbound messages it successfully processes, even if that message
could not be matched to an existing conversation and is dropped. For a large campaign it is fairly
common to receive unsolicited texts.
> feat: silence expected errors

- src/config.js
- src/server/api/assignment.js
- src/server/api/schema.js
This:
- adds missing `preferredTeamId` argument in `schema.js`
- allows knex context to be passed to `allCurrentAssignmentTargets()` to ensure we are looking at current state
- adds team-scoped assignment complete notifications
> feat: team scoped assignment complete notifications

- src/server/api/interaction-step.js
GraphQL wants `null`, not `undefined`
> fix: return null rather than undefined

- src/server/notifications.js
This resolves the error:
```
Error sending assignment notification emailCannot read property 'email' of undefined
```
It does not address a potential issue where notifications are sent from within a transaction and thus before `r.reader` will have access to any modified/created data. In this case it is a non-issue as the `assignment` insert payload is passed with the notification.
> fix: assignment notifications

- src/server/api/schema.js
Made this change this while debugging a reported bug of role not updating in the list. The bug turned out to be operator error but might as well clean up knex usage.
> refactor: use pluck over mapping the result

- src/server/api/schema.js
I'm not sure why passing the error like we were wasn't working, but this should.
> fix: pass error object to winston correctly

- src/server/api/campaign-contact.js
- src/server/api/schema.js
This should reduce the number of database round trips from 50+ to 2-4 per request to `getAssignmentContacts`
> feat: optimize get assignment contacts

- src/workers/cron/update-sms-spanish-speakers.js
The CronJob just hangs otherwise
> fix: exit the process when script has completed

- src/api/schema.js
- src/containers/AdminCampaignList.jsx
- src/containers/CampaignList/index.jsx
- src/server/api/schema.js
This PR
– adds an option to releasing all replies that toggles whether to include campaigns that have have limit assignment to teams on or not
– adds loading indicators to releasing all replies, since it could take a bit
– makes ageInHours accept decimal hour interfaces!
> feat: improve release all unnhandled replies

- migrations/20200210161722_better-todos-index.js
- src/server/api/assignment.js
This should allow this query:
```
select 
count(*), 
assignment_id,
campaign_id,
message_status,
is_opted_out,
coalesce(
contact_is_textable_now(
campaign_contact.timezone,
campaign.texting_hours_start,
campaign.texting_hours_end,
extract('hour' from current_timestamp at time zone campaign.timezone) < campaign.texting_hours_end
and 
extract('hour' from current_timestamp at time zone campaign.timezone) > campaign.texting_hours_start
),
false
) as contact_is_textable_now
from campaign_contact
join campaign on campaign.id = campaign_contact.campaign_id
where archived = false
and assignment_id in (
select id
from assignment
where user_id = ?
and campaign_id in (
select id
from campaign
where campaign.is_started = true
and organization_id = ?
and is_archived = false 
)
)
group by 2, 3, 4, 5, …
```
> feat: optimize get todos

- src/components/Empty.jsx
- src/containers/AssignmentTexterContact/index.jsx
When sending initial messages on mobile, the pencil icon would often push the Send button off the screen.
This adjusts component hierarchy and styling to ensure that nothing is pushed off and that it is
solely the middle section that grows/shrinks.
<table>
<tr>
<th>Initial</th>
<th>Reply</th>
<th>Convo</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td></td>
<td></td>
</tr>
</table>
> fix(ux): make pencil icon size dynamic

- dev-tools/insert-invite.js
There is no unique constraint on `invite.hash` (and I'm not sure there has to be) so for k8s jobs we want to explicitly check for an existing invite with the same hash as `insert-invite` Jobs may be re-run
> fix: make insert-invite idempotent

- src/server/api/lib/assemble-numbers.js
- src/server/api/lib/nexmo.js
- src/server/api/lib/twilio.js
- src/server/models/cacheable_queries/opt-out.js
- src/server/routes/assemble-numbers.js
- src/server/routes/twilio.js
- src/workers/cron/deliverability-report.js
- src/workers/cron/release-old-unsent-messages.js
- src/workers/cron/slack-teams-update.js
- src/workers/job-processes.js
- src/workers/jobs.js
Winston handles .error(message, err) okay, but not .error(err) by itself. For reability we also
want to make sure the provided message ends with a space so that the concatenated message from the
error is separate.
Due to a winston regression introduced in 3.x, we cannot pass other meta information after the error
without passing error.message and error.stack explicitly. This means we may lose additional error
properties. We cannot destructure the error either (non-iterable properties).
A better fix would be to write a custom log formatter that is error-aware. There are a few examples
on GitHub, but none that looked straightforward. We don't want to break JSON logging and parsing.
https://medium.com/@stieg/winston-3-and-logging-error-stacks-cf70b2111289 …
> chore: clean up logging

- Dockerfile
Yarn intercepts kill signals and screws up graceful shutdown.
Stock yarn:
```
$ docker run --env-file .env gcr.io/spoke-rewired/spoke:fadb9c3c6003d185ebfd53c6997a812b37937932
yarn run v1.21.1
$ node ./build/server/server
{"message":"Node app is running on port 8090","level":"info","timestamp":"2020-03-03T21:52:46.307Z"}
#> docker stop <pid>
{"message":"Received kill signal, waiting 5000ms before shutting down...","level":"info","timestamp":"2020-03-03T21:52:58.931Z"}
$
```
Node directly
```
$ docker run --env-file .env gcr.io/spoke-rewired/spoke:fadb9c3c6003d185ebfd53c6997a812b37937932 node --no-deprecation ./build/server/server
{"message":"Node app is running on port 8090","level":"info","timestamp":"2020-03-03T21:51:49.535Z"}
#> docker stop <pid>
{"message":"Received kill signal, …
```
> build: execute node directly

- src/components/IncomingMessageActions.jsx
- src/components/IncomingMessageList/index.jsx
`DataTable` pagination was a red herring (though this means there's a different bug there I haven't been able to reproduce tonight).
This was likely a regression introduced by #517 wherein the new `loadData` fixes how loading state after the initial load is handled and branches to `<LoadingIndicator />`. This means that `IncomingMessageList` is recreated rather than updated more often than not and so the conversation count also needs to be passed up from `componentDidMount()`.
> fix: message review actions

- src/lib/index.js
- src/server/api/lib/edit-campaign.js
The check for a valid 10-digit US phone number was happening before `libphonenumber` had sanitized the input phone number.
This prevents premature filtering of valid phone numbers.
N/A
N/A
> fix: validate phone number in the correct place

- .circleci/config.yml
- README.md
- commitlint.config.js
- package.json
- yarn.lock
Adds conventional commit tooling and pre-commit checks.
Adds conventional commit tooling and pre-commit checks.
Standardizes commit messages on the conventional commits standard. Address #471 
The new package.json scripts have been tested locally.
The Husky pre-commit hook has been tested locally.
N/A
> chore: enforce conventional commits

- src/components/CampaignContactsForm.jsx
- src/containers/AdminCampaignEdit.jsx
- src/server/api/lib/edit-campaign.js
- src/server/api/schema.js
- src/workers/jobs.js
Result messages that had previously been exposed to the user became hidden when the CSV processing moved to the backend. This exposes those messages to the user.
Admins should be informed of how many contacts were removed due to invalid or missing numbers, etc.
N/A
> fix(edit-campaign): expose validation stats to user

- src/containers/PaginatedUsersRetriever.jsx
The UI should be updated to reflect when the texter list is being reloaded in response to changed in campaign filter settings.
It is unclear to the user that the list is being updated in the background and that they are working from a stale user list.
This change has been tested locally.
N/A
N/A
> fix: reset texter loading UI state on refetch

- src/components/AdminDashboard.jsx
- src/components/AuthzProvider.jsx
- src/components/CampaignInteractionStepsForm.jsx
- src/components/Chip.jsx
- src/components/Navigation.jsx
- src/containers/AdminIncomingMessageList/index.jsx
- src/containers/AdminPersonList.jsx
- src/containers/AssignmentTexterContact/index.jsx
Reduce client bundle size from ~4MB to ~2.9MB by limiting the scope of imports.
This removes `lodash` and `google-libphonenumber` as modules included in the bundle. `google-libphonenumber` is no longer needed on the client as CSVs are processed on the backend. The entire `lodash` library is not needed, only a few of functions which are imported directly.
The bundle size is very big! And it doesn't need to be.
I have run Spoke locally and confirmed that each of the affected components still works.
N/A
N/A
> build: tightly scope imports to reduce client bundle size

- src/server/api/user.js
Optimize the query to fetch users for the `people()` query.
~Ignore sorting options and checking for campaign membership if `archived = true`.~
Making the index a full index addresses the issue. This is now just a refactor.
For a very large number of users and archived campaigns, the `people()` query times out if limited to archived campaigns
Run locally against database with large user and archived campaign counts.
N/A
N/A
> fix(message-review): optimize people() query

- migrations/20200310222822_clean-up-indexes.js
This fixes up/down behavior on a clean database.
See above.
I have run this up and down a few times on clean local database.
N/A
N/A
> fix: fix index cleanup migration

- src/containers/AssignmentTexterContact/index.jsx
This reduces the visual impact of the loading state between texts.
The background flashing to gray between texts is very hard on texters' eyes and dangerous for anyone with epilepsy.
It is only css changes and has been tested locally.
N/A
> fix(ux): avoid flashing background between texts

- src/api/organization-membership.js
- src/api/organization.js
- src/api/pagination.js
- src/api/schema.js
- src/api/user.js
- src/containers/AdminPersonList.jsx
- src/server/api/lib/pagination.js
- src/server/api/organization-membership.js
- src/server/api/organization.js
- src/server/api/schema.js
- src/server/api/user.js
Add user-facing management of texter auto-approval status.
This adds the ability to view and change a user's auto-approval status from the people page.
A later PR will add new actions to the Assignment Requests page to update the status from an approval/denial.
The functionality has been there on the backend for a while but never exposed. A few larger organizations are reporting that manually approving requests is getting tedious with the volume they are doing.
This has been tested manually.
A "Auto-approve texter requests" section has been added to the draft topic "Assignment control".
> feat: expose texter auto-approval status

- src/api/schema.js
- src/containers/AdminAssignmentRequest/AssignmentRequestTable.jsx
- src/containers/AdminAssignmentRequest/index.jsx
- src/server/api/schema.js
Add button for admins to both approve a request and update that user's organization membership record to be auto approve all future assignment requests.
While this can be done from the people page, that requires a few extra steps when you come across a manual approval request from a texter that should be be getting auto approved.
<table border="1">
<tr><td>
</td></tr>
<tr><td>
</td></tr>
</table>
> feat: add promote-on-assign

- src/api/organization-membership.js
- src/api/organization.js
- src/components/IncomingMessageActions.jsx
- src/components/IncomingMessageFilter.jsx
- src/containers/PaginatedUsersRetriever.jsx
- src/server/api/lib/apollo.js
- src/server/api/lib/pagination.js
- src/server/api/organization.js
Switch to using the new cursor-based pagination to fetch users from the Message Review page.
This query was timing out with offset/limit based pagination for large datasets.
I have tested this change locally
N/A
N/A
> refactor: user cursor pagination for message review

- migrations/20200327130102_enforce_one_role_per_org.js
- src/api/organization-settings.js
- src/api/organization.js
- src/api/schema.js
- src/containers/AdminPersonList.jsx
- src/containers/Settings/components/General.jsx
- src/lib/attributes.js
- src/server/api/organization-settings.js
- src/server/api/organization.js
- src/server/api/schema.js
Adds editable `defaulTexterApprovalStatus` to organization features. Use this value as the default for new organization memberships.
If an organization wants to default all texters to a status other than `approval_required` they must edit every new user manually via #610. That could be a lot of overhead.
The "Assignment control" draft topic has been edited to document this new setting.
> feat: default texter approval status

- src/containers/Settings/components/TrollTokenSettings.jsx
- src/containers/Settings/index.jsx
This completely hides TrollBot UI if the feature is not enabled. It also hides the floating action button when not on the TrollBot tab.
The TrollBot tab in Settings was previously visible regardless of the `ENABLE_TROLLBOT ` envvar.
The "add trigger token" FAB escaped the active tab and would display on the General tab.
These changes have been tested locally.
N/A
N/A
> improvement(trollbot): completely hide trollbot UI if disabled

- src/config.js
Go (nearly) straight to teardown in development environment by default.
There's no need to wait for current express requests to complete before tearing down in a development environment.
Running locally with different values for `NODE_ENV` gives the desired shutdown behavior for each value.
N/A
N/A
> chore: limit shutdown grace period in development

- Dockerfile
Use multi-stage build to reduce image size and pod update times.
The spoke image was nearing 700MB (and I was interested in multi-stage builds).
This has been built and run locally.
N/A
N/A
> build: use multi-stage docker build

- src/components/Empty.jsx
- src/containers/AssignmentTexterContact/index.jsx
When sending initial messages, the pencil icon would often push the Send button off the screen.
This adjusts component hierarchy and styling to ensure that nothing is pushed off and that it is
solely the middle section that grows/shrinks.
Reimplements #559
> fix(ux): make pencil icon size dynamic (take 2)

- package.json
- src/components/LargeList.tsx
- src/containers/AdminCampaignEdit/sections/CampaignCannedResponsesForm.jsx
- yarn.lock
Show the complete text of a canned response script.
The current implementation uses ListItem which truncates the test at 2 lines. Copying-and-pasting canned responses between campaigns would be easier if the entire text were visible/selectable without a massively wide screen.
N/A
> fix: show all canned response text

- src/lib/scripts.js
Leave placeholder first name values lowercase.
Placeholder names are often used when the a contact's name is not known. These common placeholder
names should not be capitalized.
The [Contact lists](https://docs.spokerewired.com/article/64-contact-lists) article has been updated to include a note about the capitalization behavior.
> improvement(texter): leave placeholder first name values lowercase

- src/workers/cron/catch-troll-alarms.js
Escape trigger tokens when building the tsquery.
Triggers containing single quotes (ex. `c'mon`) would cause a syntax error to be thrown.
I have verified that the new query generates the same tsquery result without breaking on single quotes.
N/A
N/A
> fix(trollbot): escape trigger tokens

- src/components/Empty.jsx
- src/containers/AssignmentTexterContact/index.jsx
This fixes a height calculation issue in Safari.
I think this is because setting the `<TextArea />`'s value was not triggering a layout/repaint. Opening the Elements inspector and toggling a flexbox CSS property off and then back on displays it correctly.
The height calculation issue pushed the send button off the screen.
Extensively in Safari.
<table border="1"><tr><th>Safari Mobile</th><th>Safari Desktop</th></tr><tr><td>
</td><td>
</td><tr></table>
N/A
> fix: fix flexbox height calculation in Safari

- src/server/api/schema.js
Consolidate permission checks, require `ADMIN` permission across the board, and only ever perform permission check using organization ID from the database record.
Using user-provided values for security verification is a no-no.
N/A
This is part of ongoing updates to User Roles page. See draft.
> fix: fix permission check

- src/server/api/organization.js
Require `OWNER` role to get organization settings.
The only sensitive information there is the Numbers API key, which is already obfuscated. But still better to enforce security boundaries correctly.
N/A
Draft "User Roles" topic.
> fix: require owner permissions to query settings

- src/config.js
- src/server/auth-passport.js
When `SLACK_CONVERT_EXISTING=true` (default) the Slack login handler will try to find an existing local auth user with a matching email address before creating a new Spoke user altogether.
This allows for transitioning from the local or Auth0 Passport strategy to the Slack Passport strategy.
N/A
N/A
> enhancement: allow matching slack users by email

- src/components/ScriptEditor.jsx
Removes the `auth` query param from the link to the "Segments and encoding" helpdesk article.
This query param was breaking the URL for some clients.
N/A
N/A
N/A
> fix: remove auth query param from segments helpdesk url

- src/server/api/organization.js
This ensures that the same knex client is used throughout the `formatPage` query building.
Using `r.knex.raw()` within a `r.reader()` query with `DATABASE_READER_URL` set causes problems. It did not seem like there was another way to access `.raw()` within a subquery. However, this.client.raw() works as expected.
I was able to reproduce the bug locally with `DATABASE_READER_URL` set and this change solves the problem. This has also been tested in production using one-off builds.
N/A
N/A
> fix: use the same knex client throughout query builder

- src/server/knex.js
Removes the now-unnecessary `afterCreate` hook.
This hook is redundant as `idle_in_transaction_session_timeout` is already set in the pool config:
```js
pool: {
idleTimeoutMillis: config.DB_IDLE_TIMEOUT_MS
}
```
But also because a more robust solution is to set this at the Postgres role level and not during session creation.
~~For a still-unknown reason, this is causing issues in production. Possibly due to a Typescript compilation error, but have not been able to reproduce locally.~~
The bug this was supposed to address was fixed in #640. Removing the `afterCreate` hook is still a good idea, however.
N/A
N/A
> fix: remove afterCreate hook

- Dockerfile
Ensures that non-dependency changes to `package.json` don't invalidate the cached `yarn install` image layers.
Node deps caching should only depend on the `dependencies` and `devDependencies` properties of `package.json`. Prior to this change, bumping the package version would invalidate the `yarn install` layers and require full installs on the next build.
This reduces build time by 40%.
1. Built image -- full installation happened
2. Built image again -- every step, including `yarn install`, cached
3. Changed version in `package.json`
4. Built image -- `yarn install` steps were cached, only the build step ran again
N/A
> build: restore Docker layer caching of node deps

- src/server/api/schema.js
This fixes capitalization of default texter autoapprove level.
The type of `user_organization.request_status` must be lowercase, but the way resolvers are set up for
organization settings, `defaulTexterApprovalStatus` must be uppercase.
I have tested the invite flow locally.
N/A
N/A
> fix(settings): fix capitalization of auto-approve type

- src/config.js
- src/server/notifications.js
Allows setting instance-wide Reply-To address.
Without this, an owner's email is used (now sorted by ID) which is not always the preferred behavior.
N/A
Added a [Notifications](https://docs.spokerewired.com/article/92-notifications) article.
> feat: reply-to address

- src/containers/AdminCampaignEdit/components/SectionWrapper.tsx
- src/containers/AdminCampaignEdit/index.jsx
- src/containers/AdminCampaignEdit/sections/CampaignAutoassignModeForm.tsx
- src/containers/AdminCampaignEdit/sections/CampaignBasicsForm.tsx
- src/containers/AdminCampaignEdit/sections/CampaignTextingHoursForm.tsx
- src/containers/hoc/with-operations.jsx
Only poll jobs for sections with job queues. Increase frequency of this polling. Pass the job, if found, to the Component.
The main types of changes are:
- Moves intermediate logic of props out of SectionWrapper `render()` and into a `withProps` HOC
- Simpler type definitions. While many of the prop types are related, trying to use `extends` for this just muddies the water.
- Only use one HOC `compose()`. This gives the section Component access to the pending job and just simplifies `asSection()`.
- Skips the pending jobs query entirely if the section does not use jobs. This required a change to with-operations to handle the empty-query possibility.
The section Component may need to access the result message of the job (e.g. contact upload). Passing that down required reworking the …
> refactor: pass section pending job

- migrations/20200413115931_add-replies-stale-at.js
- package.json
- src/api/campaign.js
- src/api/schema.js
- src/containers/AdminCampaignEdit/sections/CampaignAutoassignModeForm.tsx
- src/server/api/campaign.js
- src/server/api/schema.js
- src/server/index.js
- src/server/tasks/release-stale-replies.js
- src/server/worker.js
- yarn.lock
Add campaign.release_stale_replies, UI controls for it, and a cron job to release the stale replies
This adds an attribute `replies_stale_after_minutes` to campaigns, which, if not null, means that their replies will auto-release (the assignment_id becomes null) after `replies_stale_after_minutes` minutes.
This automates the constant unassignment of old replies that many admins have to do.
The cron job has been tested on some locally generated data and the scheduler setup locally running the server. 
The UI changes were tested locally.
> Feat: release stale replies

- src/server/api/schema.js
Fix campaign creation error.
This fixes the error creating campaigns where Spoke gets stuck loading by passing the complete argument list to `editCampaign()`.
Previously, creating a campaign would cause Spoke to get stuck loading the campaign list and would require a page refresh to see the new campaign.
N/A
N/A
> fix: fix campaign creation error

- src/server/worker.ts
Pass our custom Graphile Logger to the scheduler.
We want standardized structured logging.
N/A
N/A
> improvement: pass Spoke's logger to scheduler

- Dockerfile
- knexfile.env.js
- package.json
- seeds/zip_codes.js
- src/logger.js
- src/server/knex.js
- yarn.lock
Import modules required by Knex CLI in a context-flexible manner.
This also sneaks in passing our winston logger to knex.
The knex CLI files expect `./src` to exist. Only the build artifacts exist in our Docker image, however. Rather than including the entire chain of files required by Knex, we have the imports fall back to the `./build` directory.
This has been tested locally:
- running Spoke with `yarn dev`
- running `yarn knex [migrate|seed]`
- running `docker container run --env-file=.env spoke:copy-changes yarn knex [migrate|seed]`
N/A
N/A
> build: fix production migration scripts

- src/config.js
- src/server/worker.ts
Add envvar to set max Postgres pool size for the worker.
Finer grained control over connection usage.
This runs locally.
N/A
N/A
> chore(worker): add max pool size envvar

- src/api/organization-settings.js
- src/components/AssignmentTexter.jsx
- src/components/ContactToolbar.jsx
- src/containers/AssignmentTexterContact/TopFixedSection.jsx
- src/containers/AssignmentTexterContact/index.jsx
- src/containers/Settings/components/General.jsx
- src/server/api/organization-settings.ts
- src/server/api/organization.js
Allow organization owners to show the contact's last name and/or cell phone.
This is a much requested feature for the membership contact use case (e.g. unions).
Closes #483
<table border="1"><tr><td>Settings</td><td>
</td></tr><tr><td>Texter</td><td>
Added "Contact Information Display" section to the [Settings](https://docs.spokerewired.com/article/78-settings) article.
> feat: contact detail display settings

- src/containers/TexterTodo.jsx
This fixes the bugs where a texter will a) get stuck on a loading screen indefinitely and b) gets kicked out of a conversation.
This breaks up the GraphQL query that fetches campaign data (script, canned responses, etc.) and the list of campaign contact IDs. We want to poll for changes to the campaign data but do not want the list of campaign contact IDs to shift underneath us.
A change to a campaign contact's status will cause it to be excluded from the next polling of
contacts. This causes at the least the two following problems:
1. When a reply comes in the current contact index changes and the texter is booted out of the
reply they are crafting.
2. When a message is sent and then navigated back to the texter can view the past conversation
for a moment but is booted to a permanent …
> fix: texter stuck loading

- src/components/AssignmentTexter.jsx
Update the custom client-side cache of contact data that Spoke maintains after sending a message.
Spoke maintains a cache separate from the Apollo cache of contact data for the texter workflow. Requesting the updated `messages` list in the `sendMessage` mutation will update the Apollo cache, but not the custom Spoke cache. This means the texter will see a stale message list when they navigate backwards to a conversation they just sent a message on.
N/A
N/A
> fix: update client-side messages cache after sending

- src/workers/jobs.js
Handle the termination condition of the addPhoneNumbers loop. Also add a limit to the query.
`nextBatch[nextBatch.length - 1].id` throws an error when nextBatch is an empty list.
N/A
N/A
> fix: filter landlines

- src/components/IncomingMessageList/SurveyColumn/ManageSurveyResponses.jsx
Prevent React from crashing when a campaign does not have any interaction steps.
This is unlikely to be case outside of development campaigns, but it should be handled nonetheless.
N/A
N/A
> fix: handle case where campaign has no interaction steps

- src/components/IncomingMessageList/ConversationPreviewModal.jsx
- src/components/IncomingMessageList/MessageColumn/MessageList.jsx
- src/components/IncomingMessageList/MessageColumn/index.jsx
This fixes content overflow problems in message review detail by using a full screen modal with working flexbox settings.
Dialog's `autoDetectWindowHeight` setting was causing height calculation tension with flexbox.
This has been test locally with a few different window sizes.
N/A
> fix: use fullscreen modal to fix overflow

- src/workers/jobs.js
Prevent trying to add an empty array of phone numbers.
Switchboard will accept an empty array but the will try to execute malformed SQL.
```sql
insert into lookup.accesses (request_id, phone_number)
values  -- empty here!
on conflict on constraint unique_phone_number_request do nothing
```
N/A
N/A
> fix: prevent passing empty array to addPhoneNumbers

- src/config.js
- src/containers/Home.tsx
- src/global.d.ts
Display an icon next to organizations that have available assignments.
This makes it easier for texters to know where to head to when an instance has many organizations.
N/A
> feat: display icon next to organizations with available assignments

- src/server/index.js
Log the unhandled promise rejection and exit 1 on unhandled promise rejection.
This fixes the issue of pods not restarting on database connection errors. It will also provide
much better visibility into a variety of other unhandled promise rejections we get in Spoke.
Ref: https://github.com/nodejs/node/issues/9523#issuecomment-453505625
The current node warning suggests
```
To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict`
```
(see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode)
The added behavior will have the same effect.
Locally:
1. `brew services stop postgresql`
1. `git checkout master`
1. `yarn build:server`
1. `node --no-deprecation ./build/src/server`
1. Observed that we get raw …
> fix: log and exit on unhandled promise rejection

- src/server/index.js
Pass `logger` argument of expected type.
Terminus only logs errors and as such takes a specific logger argument expecting only an error message and error object.
I have tested this locally.
N/A
N/A
> fix: pass expected error logging function to terminus

- src/config.js
- src/server/api/assignment.js
- src/server/api/lib/alerts.js
- src/server/api/schema.js
- limit sending webhook to requests requiring manual approval
- add config option for whether webhook error fails the entire request
- include Slack user ID in webhook payload, if applicable
- fix request status typo causing postgres constraint to fail
For most users the value of assignment request notification webhooks is to notify admins they need to approve/deny a request. Notifications for auto assigned requests are noisy and can dramatically increase cost of services such as Zapier at high volume.
This has been tested locally with a combination of envvars and user assignment request modes.
N/A
We do not currently document envvar webhooks anywhere. We probably should? Or continue to use those on a request-only basis?
> feat: improve assignment request webhook

- src/server/routes/campaign-preview.js
Prevent Spoke crashing when provided a bad preview token.
A bad preview token throws an unhandled `error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt`. This results in an unhandled promise rejection, killing the process.
N/A
N/A
> fix: prevent crash on bad script preview token

- src/config.js
- src/server/auth-passport.js
Default to sourcing first and last name from Slack profile.
Slack provides these values, why not use them?
N/A
How Spoke names are determined for Slack should probably be documented as this is heavily used in script building.
> improvement: source first_name, last_name, cell from Slack profile

- package.json
- src/server/api/schema.js
- yarn.lock
Prevent clearing a campaign's logo image URL on save.
The logo was being cleared on every save unless it was explicitly being set to a valid URL in that
save. This removes the valid URL check (this should, if anything, be happening on the client) and
fixes the issue.
N/A
N/A
> fix: prevent clearing campaign logo image url

- src/server/api/lib/message-sending.js
Ensure that existing messaging service actually contains values.
The SQL function `get_messaging_service_for_campaign_contact_in_organization()` will always return a record. That record may be a real record, or it may consist of all null values. We must check for these null values in addition to just the presence of a record.
N/A
N/A
> fix: check if returned record is an empty record

- src/server/api/schema.js
Set the default request type for the General team at organization creation time.
If this is not set, the General team will not pick up autoassignment targets. Fixing this currently requires toggling the general team request type and saving after each switch.
N/A
> fix: set default text request type for General team

- migrations/20200625084204_trigger_delivery_report_job.js
- src/server/api/lib/assemble-numbers.js
- src/server/api/lib/twilio.js
- src/server/api/lib/types.ts
- src/server/tasks/handle-delivery-report.ts
- src/server/worker.ts
Handle delivery reports in a `graphile-worker` job rather than a delayed promise.
Logs show many Postgres connection errors when trying to handle delivery reports. The problem seems to be related to the 5 second delay as a) the code is standard knex no different from elsewhere and b) we are not seeing a similar rate of connection errors elsewhere in the application.
N/A
N/A
> fix: delivery report handling

- src/server/api/lib/utils.ts
- src/server/api/schema.js
Adds the organization ID as part of the Graphile Secrets reference name.
This allows using the same external system API key in multiple organizations.
N/A
N/A
> fix: per-org graphile secret refs

- migrations/20200723072159_backfill_superadmin_roles.js
Making a user a superadmin now backfills `user_organization` memberships as `'OWNER'` for all organizations.
This previously needed to be done manually.
N/A
N/A
> chore: backfill org memberships for superadmins

- migrations/20200727165444_better-autovacuum-parameters.js
Better autovacuum parameters for larger (50-100 million+ message) databases.
The default `autovacuum_scale_factor` of 0.2 leads to too infrequent autovacuum's of heavily updated tables, particularly campaign_contact. This makes many queries very CPU intensive with lots of scanning through dead tuples.
Many databases run these settings in production. This formalizes it to keep it standard across all deployments.
> feat: better auto vacuum parameters

- migrations/20200801094746_clear_external_list_cache_on_refresh.js
- src/server/api/schema.js
Clear cached external lists a) when the external system credentials have changed, and b) prior to re-fetching lists.
Many users have been confused by VAN permissions. A common path is to:
1. Create a Spoke API key
1. Share VAN folder with Spoke API key
1. Create Integration with Spoke API key
1. Sync lists from VAN
1. Attempt to load list, but fail due to wrong API key type
1. Create new Hustle API key
1. DO NOT share VAN folder with Hustle API key
1. Re-fetch VAN lists
- Hustle API key returns 0 lists (no shared folders)
- Existing external lists from Spoke API key persist
1. Attempt to load list, but fail due to "invalid savedListId in context" -- Hustle API key does not have access to the saved list that the Spoke key fetched
N/A
N/A
> fix: invalidate cached external lists

- src/server/api/organization.js
Use `id` as primary ID column for pagination.
`user_organization.id` is an invalid column name and thus all cursors were being set to base64-encoded `'undefined'`.
N/A
N/A
> fix: use id as primary column

- src/server/api/organization.js
Add a select statement for the case when no nested user information is requested.
We want to explicitly specify selecting everything from `user_organization` for `Memberships` list.
N/A
N/A
> fix: add default select statement

- migrations/20200804190149_deprioritize-handle-delivery-reports.js
When `handle-delivery-report` is queued now, it's priority is lower (a higher number) so that a build up of delivery reports doesn't affect more important jobs.
> feat: deprioritize handling delivery reports

- package.json
- src/workers/exports/gs-json.js
- src/workers/exports/s3.js
- src/workers/exports/upload.ts
- src/workers/jobs/index.js
- yarn.lock
Changes exportCampaign to stream the entire export process. I also included some progress logs, which I think will help debug production exports in the future.
Our previous export code loaded all of the contents of the CSV into memory before writing them to S3. This would crash the Node VM for very large (500k+ contacts) campaigns, even on my local machine with 8GB of RAM.
This has been tested locally with a very large campaign.
> fix: handle very large exports

- migrations/20200804192137_fix-van-list-loading-opt-outs.js
Filter out opt outs when loading a list in from VAN.
When originally creating VAN list loading, we forgot to filter out opt outs. Opt outs were not being texted because of additional runtime checks, but texters would get served these contacts and then get errors when trying to text them.
> fix(load-van-list): filter opt outs

- src/config.js
- src/server/api/campaign.js
Adds an environment variable that hides attributes from the campaigns list page that are expensive to compute for archived campaigns.
This allows the archived campaigns list to predictably load even for instances with very large (500k+ archived campaigns).
> feat: allow hiding of campaign tags on archived campaigns via env var

- src/components/IncomingMessageList/MessageColumn/MessageList.jsx
- src/components/IncomingMessageList/index.jsx
- src/server/api/conversations.js
Filter empty message records to fix UX issues.
Grouping by campaign contact ID will always return at least one row, regardless of whether there are any messages. This caused `conversation.updated_at` to always be set to `message.created_at` even if that was `null`. `new Date(null).toLocaleString()` prints a nicely formatted UNIX epoch.
N/A
> fix(message-review): filter out empty messages

- src/workers/jobs/export-for-van.ts
Fixes a bug in the export for VAN pagination
Because we were using campaign_contact.id based pagination, but the outer query was not ordered by campaign_contact.id, we were iterating over some batches of contacts multiple times.
The removal of the distinct on was necessary to overcome [the issue described here](https://stackoverflow.com/questions/9795660/postgresql-distinct-on-with-different-order-by) - there are other solutions if we want it back, but my understanding of the VAN import process is that if there are multiple survey responses for a contact, we actually want multiple rows for that contact.
> fix: export for van pagination error

- migrations/20200903111251_exclude-overdue-campaigns-from-autoassignment.js
This change prevents assignment to overdue campaigns. We had already intended this to be the correct behavior, but it appears had not implemented it.
I've tested the view definition locally as well as the correctness of the specific date_trunc / interval semantics on several production databases.
> fix(assignable_campaigns): add due_by clause

- src/api/schema.js
- src/containers/AdminCampaignEdit/sections/CampaignOverlapManager.jsx
- src/server/api/campaign-overlap.js
- src/server/api/schema.js
Allow filtering campaign contact overlap results by archived status.
Overlap query currently times out without additional backend campaign filtering.
N/A
> feat: allow filtering campaign overlaps by archived state

- src/components/IncomingMessageList/MessageColumn/MessageList.jsx
Invoke `scrollTo()` only if the `messageWindow` ref actually exists.
The introduction of the "No messages yet" render branch means that the `messageWindow` ref may be undefined.
N/A
N/A
> fix: invoke scrollTo only if conversation has messages

- yarn.lock
Update caniuse version to latest.
```sh
npx browserslist@latest --update-db
```
The list is out of date and the warnings on every yarn command are annoying.
N/A
N/A
> build: update caniuse list

- src/server/worker.ts
Slack sync jobs are erroring with `ratelimited` error. In the past we have been fine with a 10 minute window so revert back to that.
Slack's [rate limiting rules](https://api.slack.com/docs/rate-limits) for the requests we make:
- [`admin.users.list`](https://api.slack.com/methods/admin.users.list) - Tier 3 (50+ per minute)
- [`conversations.list`](https://api.slack.com/methods/conversations.list) - Tier 2 (20+ per minute)
- [`conversations.members`](https://api.slack.com/methods/conversations.members) - Tier 4 (100+ per minute)
It seems like we should be fine, but obviously we are not. A 10-minute sync window is plenty.
This has been tested in that it has worked previously.
N/A
N/A
> fix(slack): decrease sync rate to fix rate limiting

- src/lib/utils.js
- src/server/api/lib/assemble-numbers.ts
- src/server/lib/assemble-numbers.ts
- src/workers/jobs/index.js
Allow setting Switchboard base URL per-messaging profile.
This may be necessary for load balancing extremely high throughput Spoke instances.
N/A
N/A
> improvement: allow per-messaging service base url

- src/components/IncomingMessageList/MessageColumn/MessageOptOut.jsx
- src/components/IncomingMessageList/SurveyColumn/ManageSurveyResponses.jsx
- src/containers/AdminBulkScriptEditor/index.jsx
- src/containers/AdminShortLinkDomains/index.jsx
- src/containers/AdminTagEditor/index.jsx
- src/containers/AdminTeamEditor/index.jsx
- src/containers/hoc/with-operations.jsx
This pr removes the 'GraphQl Error:' prefix from graphql error messages
Per client request
Behaviorally.
- [ x] New feature (non-breaking change which adds functionality)
> feat: remove 'GraphQl Error:' from error messages

- migrations/20201004135336_fix_trollbot_pk.js
The primary key on `token` alone prevented the same token from being added to multiple organizations.
Token lists should be organization-scoped.
N/A
> fix(trollbot): make primary key compound

- src/config.js
- src/server/api/lib/alerts.js
- src/server/tasks/troll-patrol.ts
Extend string-only payload functionality to TrollBot alarm webhooks.
Slack webhooks only accept payloads with string values.
N/A
N/A
N/A
> feat(trollbot): support all-string payloads

- src/server/api/lib/assemble-numbers.ts
Pass `message.sendBefore` to `assemble-numbers`
Before, `sendBefore` param was not utilized by assemble-numbers service. With added support in https://github.com/politics-rewired/numbers-client for sendBefore, this change passes sendBefore times already being generated (in Spoke/src/server/api/schema.js:601) to the assemble-numbers/switchboard service wrapper.
> fix(assemble:sendmessage): add sendBefore support for assemble

- src/server/tasks/export-for-van.ts
Use the actual canvass date in "Export for VAN."
This was requested by client and brings behavior in line with VAN sync.
N/A
N/A
> fix(van-export): fix canvassed date

- src/server/api/schema.js
See title.
Otherwise the raw Moment object is passed as an argument and never string-ified.
N/A
N/A
> fix: format sendBefore as string

- src/containers/AdminTagEditor/TagEditorList.jsx
- src/containers/AdminTagEditor/index.jsx
- src/server/api/schema.js
This pr allows spoke admins to apply scripts, text and background color, and webhook urls to tags via the tagEditor ui.
Per #406, the backend functionality for applying tag scripts exists, we want to expose it to admins via the tagEditor UI
Behaviorally 
- [x ] New feature (non-breaking change which adds functionality)
- [ x] My code follows the code style of this project.
> feat(tags): expose script, color and webhook url editing in tag editor

- migrations/20201019133129_unique_canned_response.js
- src/server/api/schema.js
Replace potentially-problematic de-duplication query with Postgres constraint.
We do not allow texters to add canned responses from the UI. The GraphQL mutation could still be called, however. The previous delete duplicates query shouldn't have caused mass-deletion of canned responses as it was user-scoped but better to prevent duplicates using constraints.
This mutation is not currently used in our fork and thus was not tested.
N/A
> refactor: use unique constraint to prevent duplicates

- src/components/AdminDashboard.jsx
- src/config.js
Hides short link domains behind an envvar, a la the trollbot. Closes #769, part of Q4 feature freeze
I'm not sure if we want to include a toggle in settings that would allow owners to turn on the feature, or if this fix is good as-is
Per @bchrobot "The Short Link Domains feature is only useful for organizations sending at very high volume. For the vast majority of users this feature is unnecessary and confusing even."
Behaviorally 
- [x ] New feature (non-breaking change which adds functionality)
- [ x] My code follows the code style of this project.
- [ x] My commit messages follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).
- [x ] My change requires a change to the documentation.
> feat(shortlinkdomains): hide shortlink domains behind envvar

- src/containers/AdminAssignmentControl/AssignmentRow.jsx
This fixes an issue raised by this [ticket](https://secure.helpscout.net/conversation/1343368005/3413?folderId=4118236), where the Chip Input component allows creation of new tags via text input, which aren't currently being checked against escalationTagList. When the user tries to save the new tag, it generates an error - even if the user is entering a tag via text that should be selectable.
Chip Input default behavior is leading to confusion among users about how they can add tags within the AssignmentRow component, as well as what kind of tags they can add. This resolves that confusion in a minimal way.
Behaviorally
> fix(escalationtags): check tags in assignment row chip input component

- src/server/api/schema.js
- src/server/tasks/export-campaign.ts
- src/server/tasks/export-for-van.ts
- src/server/tasks/utils.ts
- src/server/worker.ts
Introduces a wrapper around transient Graphile Worker tasks to manage persistent `job_request` records.
Needs to be rebased on `master` after #726 is merged!
In the pre-Graphile Worker world the `job_request` table was used as both the queue and for recording client-facing status and result messages. We now use Graphile Worker to manage the queue but we also want to keep the client-facing status and result messages (as Graphile jobs are deleted upon completion).
The `job_request` record's lifecycle will be the same in most cases and should happen automatically.
Ref https://github.com/politics-rewired/Spoke/pull/738#pullrequestreview-501510937
This has been tested locally:
- Export Campaign still works
- Export for VAN still works
- Errors within campaign export jobs
1. Retry if `attempts …
> refactor: breakout task wrapper

- src/server/api/errors.js
- src/server/api/organization.js
- src/server/api/schema.js
- src/server/routes/graphql.js
This adds an authorization check to the organization.myCurrentAssignmentTargets resolver.
It also refactors authn/authz util methods to use `ApolloError`s rather than incorrectly using `GraphQLError`.
Closes #775 
This will need to be rebased on `master` after #726 is merged.
This resolver routinely logs `TypeError: Cannot read property 'id' of undefined` errors when `context.user === undefined`.
This has been tested locally, as in things continue to run fine with the changes. I have not been able to discover reproduction steps for triggering the error itself, however.
N/A
N/A
> fix: add authz check to myCurrentAssignmentTargets resolver

- src/components/forms/GSScriptField.jsx
This pr extends the ScriptLinkWarningDialog and the related logic from GSScriptOptionsField into GSScriptField
The script link warning is currently only displayed when users edit interaction steps - now it will be displayed when users add a script to a tag and edit canned responses as well 
- [x ] New feature (non-breaking change which adds functionality)
- [ x] My code follows the code style of this project.
> feat: add link warning to script field

- src/containers/AdminCampaignEdit/sections/CampaignFilterLandlinesForm.tsx
- src/server/api/schema.js
- src/server/tasks/filter-landlines.ts
- src/server/worker.ts
- src/workers/jobs/index.js
Use Graphile task for filtering landlines from campaign's contacts.
Needs to be rebased on `master` after #760 is merged.
Better error/retry handling and continued deprecation of `JOBS_SAME_PROCESS`.
This has _not_ been tested yet.
N/A
N/A
> refactor: use graphile task for filtering landlines

- src/server/api/schema.js
added `is_deleted: false` to the query that gets the interaction steps to copy to a newly copied campaign
just added another where clause
https://github.com/politics-rewired/Spoke/issues/772
in browser 
- [i think so ] My code follows the code style of this project.
- [i think so ] My commit messages follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).
- [i don't think so] My change requires a change to the documentation.
- [i think so] I have included updates for the documentation accordingly.
> fix: copy campaign deleted interactions

- src/api/schema.js
- src/containers/AdminIncomingMessageList/index.jsx
- src/server/api/schema.js
This adds the contact name filter to the payload sent for bulk assignment operations.
Bulk assignment operations should act on the conversations returned by the active filter set. Ignoring any of the displayed filters leads to unexpected behavior.
Closes #796
N/A
N/A
> fix: add contact name filter to bulk assignment action filter

- src/containers/CampaignList/CampaignList.jsx
closes #682, party of Q4 feature freeze
Campaign descriptions don't wrap, so long ones push the campaign actions toggle off the screen in the CampaignList component. Now the text wraps, so the toggles stay visible.
Locally
> fix(campaigns): wrap long campaign descriptions

- src/containers/AdminCampaignEdit/sections/CampaignBasicsForm.tsx
- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm.jsx
- src/containers/AdminCampaignEdit/sections/CampaignTeamsForm.jsx
- src/containers/AdminCampaignEdit/sections/CampaignTextersForm.jsx
- src/containers/AdminCampaignEdit/sections/CampaignTextingHoursForm.tsx
- src/containers/Settings/components/General.jsx
Closes #781, part of Q4 feature freeze
Unclickable buttons should be unclickable!
NB: For the edit campaign sections, It seems like there should be a better solution than extracting the form submit functionality into a button outside of the GSForm, but I spent a lot of time trying to properly disable the GSSubmitButton within the component itself and within the GSForm component, but couldn't crack it. 
Locally
- [ x] Bug fix (non-breaking change which fixes an issue)
> fix: make disabled buttons unclickable

- package.json
- src/server/auth-passport.ts
- src/server/local-auth-helpers.ts
- yarn.lock
Revert the incorrect throwing of an error within the local login flow.
This also downgrades `cookie-session` to the latest stable version.
The error thrown for falsey `uuidMatch` was added in #560 to fix a type complaint. This commit fixes typing in the correct way and reverts adding the error.
I was running into `TypeError: this.socket.cork is not a function` errors on every request with no useful traces after making the `uuidMatch` fix. Downgrading `cookie-session` to a stable version solved these issues (and may also solve some of the account lockout problems some users encounter).
N/A
N/A
> fix(auth): remove incorrect local login error

- package.json
Bumps `assemble-numbers-client` from 1.2.2 to 1.2.3
The `sendBefore` parameter was [added in 1.2.3](https://github.com/politics-rewired/numbers-client/pull/19). However, the client version was never bumped in Spoke and thus the `sendBefore` parameter being passed was ignored.
Closes #774
N/A
> fix(switchboard): update client lib to support sendBefore param

- src/server/api/campaign.js
Use optional `userId` argument from GraphQL for canned response query.
This fixes a regression from #726 (typescript eslint). A shadowed variable name error was incorrectly fixed by using the session user's ID instead of the GraphQL query argument.
GraphQL query signature looks like:
```gql
type Campaign {
cannedResponses(userId: String): [CannedResponse]
}
```
N/A
N/A
> fix: fix regression in canned response resolver

- __test__/AssignmentSummary.test.js
- package.json
- src/client/index.jsx
- src/components/AssignmentTexter.jsx
- src/components/BulkSendButton.jsx
- src/components/Chip.jsx
- src/components/ConfirmButton.jsx
- src/components/Navigation.jsx
- src/components/ScriptEditor.jsx
- src/components/ScriptList.jsx
- src/components/SendButton.jsx
- src/components/forms/GSScriptField.jsx
- src/components/forms/GSScriptOptionsField.jsx
- src/containers/AdminCampaignEdit/index.jsx
- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm.jsx
- src/containers/AdminCampaignEdit/sections/CampaignTextersForm.jsx
- src/containers/AdminCampaignList.jsx
- src/containers/AdminCampaignStats/index.jsx
- src/containers/AdminNavigation.jsx
- src/containers/AdminPersonList.jsx
- src/containers/AssignmentTexterContact/ContactActionDialog.jsx
- src/containers/AssignmentTexterContact/TopFixedSection.jsx
- src/containers/AssignmentTexterContact/index.jsx
- src/containers/AssignmentTexterSurveyDropdown.jsx
- src/containers/UserEdit.jsx
- src/containers/UserMenu.jsx
- yarn.lock
This removed the deprecated `react-tap-event-plugin` plugin.
Closes #417
This has been loosely tested locally.
N/A
N/A
> chore: remove deprecated touch-tap plugin

- migrations/20201216105636_van_sync_opt_out_configuration.js
- src/api/external-system.ts
- src/api/schema.js
- src/containers/AdminExternalSystemDetail/components/OptOutConfigurationCard.tsx
- src/containers/AdminExternalSystemDetail/index.tsx
- src/server/api/external-system.ts
- src/server/api/schema.js
- src/server/tasks/sync-campaign-contact-to-van.ts
Allows configuring a per-integration sync mapping for Spoke opt outs.
Closes #797 
This has been tested locally with a variety of combinations of opt out, messaged status, and question response mappings by looking at the payload to be sent to VAN.
The VAN sync documentation will need to be updated to include this configuration step.
> feat(van): sync opt-outs

- src/containers/AdminCampaignEdit/index.jsx
- src/containers/AdminCampaignEdit/sections/CampaignTeamsForm.jsx
previous code was imperatively mutating the teams array passed in as props
AdminCampaignEdit relies on comparison between props and server response to enable or disable the save button. When editing a campaign's teams, only toggling the non-teams-array related value (the flag for restricting texters to team) is the only way to allow this condition to be true, as the teams array (pulled from server response and passed as props) was being mutated on user input, so it was always in sync (regardless of database changes).
this should fix this issue: https://github.com/politics-rewired/Spoke/issues/820
only tried locally
> fix: remove mutation of props in CampaignTeamsForm

- migrations/20210104095122_unique_user_email_addresses.js
Changes user.email to citext and includes some data migration to make the constraint true. For details on the migration, see the comment in the issue: https://github.com/politics-rewired/Spoke/issues/782
See https://github.com/politics-rewired/Spoke/issues/782
I've tested that the migration is syntactically correct and up/downable and doesn't mess up a clean database locally.
The accuracy of the data modification has been tested on a client's production database with rollbacks.
> fix(user): unique email addresses with migration

- src/api/schema.js
- src/components/AssignmentTexter.jsx
- src/server/api/schema.js
- src/server/models/cacheable_queries/opt-out.js
This is a defensive fix to address issues likely responsible for https://github.com/politics-rewired/Spoke/issues/780 where some of `sendMessage`, `updateQuestionResponse`, etc. succeed and some do not.
It moves these operations to one mutation and runs them in a single transaction on the server.
See https://github.com/politics-rewired/Spoke/issues/780.
I've tested each code pathway locally - send a message while updating a question response, while deleting a question response, while opting out a contact, and all of the above while skipping a reply as well.
> refactor(send-message): add general handle conversation

- src/containers/AdminCampaignEdit/index.jsx
This PR addresses an error that prevented admins from creating or editing campaigns; attempting to
do led to an infinite spinner and a console error: `Uncaught TypeError: #<Object> is not a function
at Array.map (<anonymous>) at AdminCampaig nEdit.checkSectionSaved (index.jsx:331)`. `pick` was
being called without the object it's meant to "pick" from.
Fixes #851
1. Start the dev server from master.
2. Navigate to the "Campaigns" tab in admin mode.
3. Try to create a new campaign or try to edit an existing campaign.
4. Instead of seeing an infinite screen, see the usual campaign editing page!
OS: macOS Catalina
Browser: Chrome
Version: 87.0.4280.88
n/a
> fix(admincampaignedit): fix use of lodash/pick in checkSectionSaved

- migrations/20210112103258_monthly-org-message-limits.js
- src/components/AssignmentTexter.jsx
- src/config.js
- src/server/api/schema.js
- src/server/tasks/update-org-message-usage.ts
- src/server/worker.ts
Optionally restrict the amount of outbound messages an organization can send per month.
User request for cost controls
I checked locally:
> feat: per organization message limits

- src/lib/datetime.ts
Add a defensive fix for `null`/`undefined` time zone names passed to `parseIanaZone()`.
This resolves issue opened by user flagging an error with the `editCampaign` mutation.
The project is not typed enough to rely on TS to catch places where null/undefined is passed to
parseIanaZone() despite the required `string` argument.
N/A
N/A
> fix: add defensive fix for null/undefined zone name

- src/components/SendButtonArrow.jsx
- src/containers/AssignmentTexterContact/index.jsx
Before this change, the send arrow was positioned absolutely with respect to the entire screen, and it was "pinned" to the bottom right corner.
With this change, the send arrow is positioned absolutely with respect to the message field, and it is "pinned" to the top right corner.
This change also hides the send arrow when the screen width is greater than 450px. The existing CSS suggests this was the desired behavior, but it wasn't working as expected.
While I was working on #438 / #829, I realized that adding the character count below the text field would require moving the arrow up by an arbitrary amount (the height of the new component). It felt off to have the `SendButtonArrow` component so dependent on its sibling components.
I also noticed #711, which suggests the incremental change …
> fix(sendbuttonarrow): pin the send arrow to the top of the message field

- .circleci/config.yml
- jest.config.js
- src/lib/tz-helpers.spec.ts
- src/lib/tz-helpers.ts
- src/server/api/schema.js
Add a testable utility function for generating the `sendBefore` value for a campaign's messages.
The previous generation method was producing values in the past.
Switchboard also drops the timezone data so converting to UTC must be the final step.
This has been tested with included unit tests.
N/A
N/A
> fix: add getSendBeforeUtc util to fix sendBefore

- src/containers/AdminPeople/AdminPeople.tsx
- src/containers/AdminPeople/PeopleRow.tsx
- src/containers/AdminPeople/context.ts
Pass membership ID instead of user ID to `editOrganizationMembership` mutation.
The `editOrganizationMembership` mutation expects the ID of an `OrganizationMembership` (`user_orgranization` table) instance.
N/A
N/A
> fix(people): pass membership id to membership mutation

- src/components/IncomingMessageList/SurveyColumn/ManageSurveyResponses.jsx
- src/containers/hoc/with-operations.jsx
- src/lib/utils.js
- src/lib/utils.spec.ts
- src/server/api/schema.js
Update `formatErrorMessage()` to handle mixed arguments gracefully.
`formatErrorMessage()` gets passed `Error` and `string` type arguments in different places but previously only expected `Error` type. Passing a string would cause an `Uncaught TypeError: Cannot read property 'replaceAll' of undefined` error in the client rendering certain components unresponsive.
This has been tested locally and unit tests have been added.
N/A
N/A
> fix: handle mixed argument types

- package.json
- src/components/InfiniteRelayList.tsx
- src/components/WhenSeen.tsx
- src/containers/AdminPeople/AdminPeople.tsx
- src/containers/AdminPeople/PeopleTable.tsx
- src/containers/AdminPeople/context.ts
- yarn.lock
Use Apollo Client caching for pagination.
Managing pagination state manually means components will not get updates from the Apollo Client cache (e.g. mutation result). This uses the `<Query>` component from Apollo Client to push pagination state management up to Apollo.
N/A
N/A
> refactor: manage pagination result with apollo

- src/server/notifications.js
Restore email notifications on campaign start.
A user reported that starting a campaign did not trigger email notifications. Inspection of that clients settings showed that emails _should_ have been going out for campaign start events. Looking at logs I found:
```json
{
"content": {
"service": "spoke",
"message": "GraphQL error: Undefined binding(s) detected when compiling FIRST query: select * from \"campaign\" where \"id\" = ? limit ?",
"attributes": {
"path": [
"startCampaign"
],
"extensions": {
"code": "INTERNAL_SERVER_ERROR"
},
"level": "error",
"locations": [
{
"line": 2,
"column": 3
}
]
}
}
}
```
Turns out that Knex's `pluck()` only works for a single column (makes sense) and returns `false` otherwise, rather than throwing an error (does not make sense). This meant that the query …
> fix: fix email notifications on campaign start

- src/server/api/lib/campaign.spec.ts
- src/server/api/lib/campaign.ts
This ensures a) that `[]` and `null` error codes are grouped and b) that `null`, rather than `undefined`, is returned to the resolver.
GraphQL does not coerce `undefined` -> `null` so we must ensure we're returning `null` to avoid this error:
```
GraphQL error: Resolve function for "DeliverabilityErrorStat.errorCode" returned undefined
```
N/A
N/A
> fix(deliverability-stats): ensure consistent null return type

- src/lib/index.js
- src/lib/interaction-step-helpers.js
This removes dead code.
Removing dead code, especially utility functions with similar function other util functions, makes it easier to grok what's going on and removes the possibility of using the wrong/untested utility function elsewhere in the codebase.
N/A
N/A
> chore: remove unused sortInteractionSteps function

- package.json
- yarn.lock
This fixes the bug preventing changing a `<DataTable>`'s row size.
`material-ui-datatables` is no longer maintained. The last published version relies on an old version of `material-ui@v0` that in turn relies on the now-deprecated `react-tap-event-plugin` (removed from Spoke in #815). This PR uses `resolutions` to force `material-ui-datatables` to use the latest version of `material-ui@v0`.
Closes #858
Closes #869
N/A
N/A
> fix(datatables): force latest material-ui to fix rows per page dropdown

- src/api/interaction-step.ts
- src/containers/AssignmentTexterContact/index.jsx
- src/lib/interaction-step-helpers.js
- src/lib/interaction-step-helpers.spec.ts
- src/server/routes/campaign-preview.js
This makes it so that `makeTree()` returns a deterministic tree in the face of multiple root interaction steps based on the most recent root interaction step.
Non-deterministic Postgres result ordering is part the interaction step saving bug. Different loads of a page may show different trees when multiple root interaction steps exist.
This has been tested locally and unit tests have been added.
N/A
> fix: make makeTree() deterministic

- __test__/testbed-preparation/core.ts
- package.json
- src/server/api/lib/interaction-steps.spec.ts
- src/server/api/lib/interaction-steps.ts
- src/server/api/schema.js
- src/server/memoredis.ts
- yarn.lock
This adds unit tests for persistInteractionStepTree
Ruling out server-side problems with the current interaction step saving bug.
The relocation of `persistInteractionStepTree()` has been tested locally. `persistInteractionStepTree()` is now tested with unit tests.
N/A
N/A
> test: test persistInteractionStepTree

- package.json
- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/components/InteractionStepCard.tsx
- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/index.tsx
- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/resolvers.ts
- src/network/apollo-client-singleton.ts
- src/network/types.ts
This makes the Apollo cache the definitive source of truth for editing interaction steps.
Splitting state between the Apollo cache and React component state creates opportunities for DB state and client UI to diverge. Making Apollo the definitive source of truth ensures that all database updates from both queries mutations are reflected in the UI and removed the possibility for React component state to hold onto invalid stale values.
N/A
N/A
> fix: use single source of truth for interaction steps

- src/components/forms/GSScriptOptionsField.jsx
- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/index.tsx
Fix error thrown while saving interaction steps.
`<GSScriptOptionsField>` was  mutating props causing this error under some conditions, namely read-only values being passed as props:
```
Uncaught TypeError: Cannot assign to read only property '0' of object '[object Array]'
at GSScriptOptionsField.handleSaveScript (GSScriptOptionsField.jsx:61)
```
N/A
> fix(interaction-steps): fix edit script

- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/index.tsx
Add a new step when editing the default empty step in a brand new campaign.
Previously, editing the default empty step of a new campaign would try to update an existing step. Because it was the default empty step being edited, this update would fail silently. This is addressed by adding an interaction step if none exists.
N/A
N/A
> fix(interaction-steps): handle case of empty campaign

- dev-tools/migrate-worker.js
- package.json
- yarn.lock
This updates pg-compose to 0.0.25 which uses the logger provided to pg-compose for migration errors rather than always using `console.error`. It also ensures that the correct logger type is passed to `runMigrations`.
See politics-rewired/pg-compose#6
This has been tested locally to ensure that structured logging is used for a worker migration SQL error.
N/A
N/A
> fix: use structured logging for worker migrations

- src/server/worker.ts
The semaphore is now checked before acquiring. An early return is also added for better performance (no yaml parsing) on subsequent worker fetches.
Previously, the worker could be instantiated twice if two `getWorker()` calls both grabbed the semaphore before the other's `await run()` finished.
N/A
N/A
> fix(worker): fix lock on semaphore and add early return

- src/server/api/organization-membership.ts
Use the membership record's `role`.
The previously used query to get `role` wasn't scoped to the organization resulting in the wrong role being returned. We already have the organization-scoped `role`, however, as part of the `membership` -- the only reason we need a custom resolver for `role` is to check superadmin status.
This has been tested locally running against a production DB.
N/A
N/A
> fix: fix role resolver

- src/components/ScriptEditor.jsx
- src/components/forms/GSForm.jsx
- src/components/forms/GSScriptField.jsx
- src/components/forms/GSScriptOptionsField.jsx
- src/components/forms/GSTextField.jsx
- src/containers/AdminCampaignList.jsx
- src/containers/AssignmentTexterContact/ContactActionDialog.jsx
- src/containers/AssignmentTexterContact/MessageTextField.jsx
- src/containers/AssignmentTexterContact/index.jsx
Replace string refs with callback refs.
[String refs are deprecated](https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs).
This has been tested locally. Specifically:
- releaseAllReplies modal
- message textfield
N/A
N/A
> fix: update refs usage

- src/components/CannedResponseMenu.jsx
- src/components/ScriptList.jsx
- src/containers/UserMenu/components/OrganizationItem.tsx
- src/containers/UserMenu/index.tsx
Pass Apollo `client` and React Router `history` to components that exist outside of the React DOM tree.
Material UI v0's `<Popover>` component renders its children outside of the application's React DOM tree. This means the `<Popover>` children are not children of a context providers (e.g. `<ApolloProvider>`, `<BrowserRouter>`), a breaking issue in future versions of React.
N/A
N/A
> fix: pass props directly when HOC contexts are not available

- src/components/Login.tsx
- src/containers/AdminCampaignEdit/components/SectionWrapper.tsx
- src/containers/AdminCampaignEdit/index.jsx
- src/containers/AssignmentTexterContact/NoMessagesIcon.tsx
- src/containers/AssignmentTexterContact/index.jsx
- src/server/routes/settings.ts
- src/styles/mui-theme.ts
- src/styles/types.ts
Apply overridden styles to components missed in the first pass.
Requested by customer.
N/A
> feat: add additional styling

- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/resolvers.ts
Fix bug where `answerActions` was set to `answerOptions`.
This results in error messages like `Cannot find module '../action_handlers/NO they will not donate.js'`
N/A
N/A
N/A
> fix: set answer actions to correct value

- src/server/index.ts
Remove graceful shutdown delays if we're not running in production.
Foreman has trouble with this and we sometimes get dirty restarts where the old http server is still running on port 8090 and the new process fails to start.
N/A
N/A
> chore: remove shutdown delays outside of production mode

- package.json
- src/client/App.tsx
- src/components/SyncConfigurationModal/index.tsx
- src/containers/AdminCampaignStats/VanSyncModal.tsx
- src/styles/mui-theme.ts
- yarn.lock
This fixes the context provider/consumer bug impacting the VAN sync modal.
`material-ui@~0` renders dialog content outside the primary React DOM tree. This is fine for one level of dialogs when a `<Dialog>`'s child component consumes a React context (e.g. `react-apollo`).
`@latest` uses React portals to avoid this bug altogether.
This adds v0 and @latest side-by-side as described in [Migration From v0.x to v1](https://material-ui.com/guides/migration-v0x/).
N/A
> fix: fix VAN sync modal

- src/components/AssignmentTexterSurveys.jsx
- src/containers/AssignmentTexterContact/index.jsx
This fixes a crash in the texter application caused by passing `null` instead of an empty string.
`md5()` and `<MessageLengthInfo>` both break on `messageText = null`.
N/A
N/A
> fix: fix texter crash when clearing a survey response

- src/components/ScriptEditor.jsx
- src/components/forms/GSScriptOptionsField.jsx
This fixes a crash caused by editing TextField content rather than ScriptEditor content.
The field's default onChange behavior (updating the GSForm value) was being attached to the
read-only TextField. Clicking into this TextField opens the script editor pop-up but if changes are
made to the script while the TextField has focus then onChange is incorrectly called with a string,
rather than an array of strings.
The script editor pop-up should steal focus as soon as it is opened, preventing/masking this bug,
but that functionality was broken. This PR restores focus-on-open behavior to the ScriptEditor
pop up.
N/A
N/A
> fix: fix crash editing interaction step

- src/client/lib/index.ts
- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/components/InteractionStepCard.tsx
- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/index.tsx
This disables the copy/paste block functionality with a warning message when `navigator.clipboard.readText()` is unavailable rather than crashing.
Firefox only supports `clipboard.read()` and `clipboard.readText()` in browser extensions that have specifically requested the permission ([ref](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText)). Crashing when we encounter this is bad UX.
Closes #854 
N/A
> fix: disable unsupported copy/paste block rather than crashing

- package.json
- src/components/ScriptEditor.tsx
- yarn.lock
Only move the cursor to end of the field's text on mount.
ScriptEditor.focus() is called from the wrapping div's onClick method. This was causing the curor
to move to the end any time the script field was clicked.
N/A
N/A
> fix: fix draft.js focus behavior

- src/client/index.tsx
Remove the 500ms timeout on the initial instance settings fetch.
Some users may have consistently slow internet connections that cause the settings fetch to timeout on every request.
This has not been tested.
N/A
N/A
> fix: remove timeout fetching instance settings

- src/workers/jobs/index.js
Some clients with larger `campaign_contact` tables reporting manual assignment failing - upon investigation, this query was responsible, sometimes taking over 30 seconds and causing the whole transaction to abort. 
The query could be optimized as:
```sql
select assignment.id as id 
from assignment 
where not exists (
select 1
from campaign_contact 
where campaign_contact.assignment_id = assignment.id
and campaign_contact.archived = false
)
and assignment.campaign_id =  $1;
```
but it wasn't being used anyways, so we can just remove it!
The query was originally part of a check to delete assignments which no longer had contacts associated with them, but we don't do that anymore since:
a) We might just end up recreating them in the future, and
b) It violated opt out foreign key constraints …
> fix(manual-assignment): remove unused expensive query

- src/config.js
- src/server/worker.ts
Allow overriding the default crontab schedule for the sync Slack teams job.
Some clients require more frequent syncs and have few enough Slack workspace members that this will not cause problems with Slack API rate limits.
N/A
N/A
N/A
> feat: make slack team sync crontab configurable

- src/api/campaign.ts
- src/api/external-activist-code.ts
- src/api/external-list.ts
- src/api/external-result-code.ts
- src/api/external-survey-question-response-option.ts
- src/api/external-survey-question.ts
- src/api/external-sync-config.ts
- src/api/external-system.ts
- src/api/schema.js
Use actual GraphQL `Date` type for dates.
`knex` returns Postgres `date` and `datetime`s as Javascript Dates. Previously, Apollo Server serialized these as strings. By default, Date.toString() uses a local format which is undesirable and causes bugs where client code expects to parse ISO-8601 strings.
The values remain as strings on the client because there is no parsing of custom scalars implemented client-side.
It seems like this broke with a recent knex upgrade but I can't find anything in knex's changelog to confirm that. A different option would be to force knex to return dates as strings:
```ts
// src/server/knex.js
const stringifyDates = (records) =>
(records || []).map((record) =>
Object.fromEntries(
Object.entries(record).map(([columnName, value]) => [
columnName,
value …
```
> fix: serialize dates using ISO-8601 format

- src/server/api/schema.js
Prevent adding tokens that will throw an error in `to_tsquery()`.
Invalid tokens will otherwise fail silently at runtime.
This has been tested locally using `c'mon` (valid) and `'c'mon'` (invalid).
N/A
N/A
> fix(trollbot): prevent adding invalid tokens

- src/containers/AdminCampaignEdit/sections/CampaignCannedResponsesForm/components/CannedResponseDialog.tsx
Restore the canned response dialog to full width.
This is how it was previously and is much easier to draft in.
N/A
N/A
> fix(canned-responses): restore dialog to full width

- src/api/schema.js
- src/containers/AdminPeople/AdminPeople.tsx
- src/containers/AdminPeople/Dialogs.tsx
- src/server/api/schema.js
Allow organization owners to remove all users from an organization.
This has become a semi-frequent source of help desk tickets.
N/A -- this is a self-documenting feature.
> feat: add button to remove all users from organization

- src/api/schema.js
- src/containers/CampaignList/CampaignListMenu.tsx
- src/containers/CampaignList/OperationDialog.jsx
- src/containers/CampaignList/index.jsx
- src/server/api/schema.js
This adds a new toggle to the "Mark for second pass" operation dialog. The toggle controls whether to exclude from the operation contacts that have been uploaded in a newer campaign.
Closes #935
The value of `updateSql` has been verified locally.
@kohlee has already drafted an update for documentation at https://docs.spokerewired.com/article/101-running-a-second-pass
> feat(p2): add toggle for excluding newer contacts

- migrations/20210414202903_backfill-num-segments.js
- src/server/api/lib/assemble-numbers.ts
This fixes `assemble-numbers.processDeliveryReport` to property write `num_segments` and `num_media` to the message when handling delivery reports.
The issue was that either `num_segments` or `num_media` was often 0, and 0 is falsy. As a result, that if statement that execute the update never ran.
This checks that at least one of them is a number instead.
This PR also adds a PostgreSQL procedure to easily backfill that data. After the included migration has run, just run:
```sql
call backfill_all_segment_info(0, 5000);
```
On the database, and the information will be backfilled.
In a local Node REPL with the external variables mocked.
> fix: assemble numbers process delivery report

- src/containers/AdminCampaignStats/DeliverabilityStats.tsx
This PR fixes the sorting of message error codes and removes the `.slice(0, 5)`, so all error codes are shown.
The previous use of `.sort((a, b) => -1 | 0 | 1)` was treating it like a `.sortBy` function, which had the effect of doing no sorting and leaving the elements in their server returned order.
Locally
> fix(deliverability-stats): show all errors in descending order

- package.json
- src/components/Navigation.tsx
- yarn.lock
Fix rotation of admin navigation menu in Firefox.
It seems like Firefox is the only browser to have implemented `writing-mode` correctly. This property was being used to rotate the menu button in the collapsed state but was also being used incorrectly on the expanded menu.
Element rotation is hard. This replaces the text buttons with icon buttons to alleviate the need for rotation entirely.
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>Chrome - Closed</td>
<td>Chrome - Open</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>Firefox - Closed</td>
<td>Firefox - Open</td>
</tr>
</table>
N/A
> fix: fix admin navigation menu rotation in firefox

- package.json
- src/client/App.tsx
- src/containers/AdminTrollAlarms/index.tsx
- src/server/api/schema.js
- yarn.lock
Store pagination state in query parameters and sort troll alarms by most recent first.
The number of troll alarms can quickly become unwieldy. Even with a page size of 500, it can be very time consuming to navigate to the correct page. Showing more recent alarms first and exposing the page number in the URL mitigate this.
N/A
> feat(trollbot): improve navigation of troll alarms

- src/config.js
- src/containers/AdminCampaignEdit/index.jsx
- src/containers/AdminCampaignEdit/queries.ts
Fix the start campaign button by fixing the legacy readiness check for the Contacts section.
The `contactsCount` field is used by the legacy readiness check. Once all sections are converted to standalone sections, these legacy section checks can be replaced with the new `readiness` fields.
N/A
N/A
> fix: fix start campaign button

- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/components/InteractionStepCard.tsx
Pasting over a block and its children should only be allowed for the root interaction step.
Closes #922
Depends on #955 
N/A
N/A
> fix: only show paste-over-block button for root step

- src/client/lib/index.ts
- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/index.tsx
- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/utils.ts
Add more defensive fixes for accessing the new asynchronous clipboard API.
This addresses new reports of application crashes in Safari due to attempted clipboard access.
Calling `updateClipboardHasBlock()` in a context outside of a user-initiated action (e.g. from `componentDidMount()`) may be the problem. If browsers widely adopt the requirement that clipboard API methods be called in response to user actions then we will need to drop `hasBlockCopied` and instead display an error if "Paste Block" is clicked without valid clipboard data.
This has not been tested with the latest Safari version yet.
N/A
N/A
> fix: harden clipboard usage

- src/containers/AdminCampaignEdit/sections/CampaignTextersForm/index.tsx
This forces the `GET_CAMPAIGN_TEXTERS` query to hit the server every time. 
This forces `refetch()` to hit the server for fresh data rather than the default fetch policy of `cache-first` (although this is not well documented for Apollo Client v2).
@kohlee observed that deleting texters appeared not to stick. This was because the execution of the `GET_CAMPAIGN_TEXTERS` query is performed by the `loadData()` HOC in 99% of cases, not the call to `refetch()`.
Apollo Client v2's documentation is lacking regarding fetch-policy, but it _seems_ like the default fetch policy is `cache-first`. Presumably `refetch()` uses a different cache policy, although this is neither documented nor configurable (only `variables` can be changed).
The completion of a pending `assign-texters` job causes a fresh …
> fix: force fetching fresh data

- .npmrc
- README.md
- package.json
Prevent `npm install`. Sadly, this does not prevent `npm install <package>` (see [npm issue](https://github.com/yarnpkg/yarn/issues/4895)).
Use of npm breaks the dependency resolutions in `yarn.lock`, creating its own in `package-lock.json`. This can result in unpredictable behavior (ref #960).
This has been tested locally with `npm install`.
N/A
N/A
> chore: force use of yarn package manager

- package.json
- yarn.lock
Update pgc-ngp-van for configurable VAN export webhook URL along with updated default webhook URL.
This allows inspection of the export payload for debugging.
N/A
N/A
N/A
> fix: update pgc-ngp-van for configurable webhook url

- src/server/tasks/assign-texters.spec.ts
- src/server/tasks/assign-texters.ts
- src/server/utils.ts
Consolidate the assignment steps to one query and add tests.
The current assignment queries are slow and untested.
See `assign-texters.spec.ts`.
N/A
> perf: consolidate texter assignment query

- migrations/20210526012107_add-phone-object-to-van-sync.js
- schema-dump.sql
- src/server/tasks/sync-campaign-contact-to-van.spec.ts
- src/server/tasks/sync-campaign-contact-to-van.ts
This sends the `phone` object in addition to the `phoneId` string;
From VAN support:
> Phone number will be required. Eventually, phoneid-only will not be sufficient.
See https://secure.helpscout.net/conversation/1517362472/4308.
N/A
N/A
N/A
> fix(van): send phone object

- src/api/external-result-code.ts
- src/components/AddMapping.tsx
- src/components/QuestionResponseConfig/components/ResultCodeMapping.tsx
- src/components/QuestionResponseConfig/index.tsx
Add deprecation warning to the "Disconnected" VAN result code.
VAN announced:
> Going forward, you should default to Deliverability Error when a call or SMS to a phone number cannot be completed but you are unsure if the phone number is truly disconnected. Only use Disconnected when you are very confident that the number is truly disconnected.
>
> [We] will be allowing our clients to restrict which vendors can apply Disconnected contact results and your API keys may lose this permission.
See attached screenshots.
<br />
<center><i>New Mappings</i></center>
</td></tr>
<tr><td>
<br />
<center><i>Existing Mappings</i></center>
I think this is self-documenting. Others may disagree.
> fix(van): add deprecation warning for disconnected result code

- src/api/assignment.ts
- src/api/schema.js
- src/containers/AdminCampaignEdit/sections/CampaignTextersForm/index.tsx
- src/server/api/schema.js
- src/server/tasks/assign-texters.spec.ts
- src/server/tasks/assign-texters.ts
This fixes a bug causing more assignments to be zeroed out than expected.
The problem lies in how the `ANY` operator was inverted. The correct inversions are `not assignment_id = ANY($2)` or `assignment_id <> ALL($2)`; `assignment_id <> ANY($2)` is not a correct inversion.
The PR includes changes to tests and a small refactor to the GraphQL mutation to rule out payload issues.
See changes to `assign-texters.spec.ts`.
N/A
N/A
> fix(texters): fix assignment bugs

- src/server/tasks/assign-texters.spec.ts
- src/server/tasks/assign-texters.ts
Assign from pool of all unassigned conversations rather than just `needsMessage`.
The Texters section UI shows counts for Assigned and Unassigned but does not scope these numbers to
needsMessage conversations. The assignment query is limited to needsMessage, however, resulting in
behavior where assigning n messages to a texter in the frontend results in 0 assigned converations
because while there are n unassigned conversations none of them are needsMessage.
See changes to `assign-texters.spec.ts`.
N/A
N/A
> fix(texters): assign from pool of all unassigned conversations

- src/containers/AdminCampaignEdit/sections/CampaignFilterLandlinesForm.tsx
Updates the Filter Landlines copy to be more precise.
Our original calculations for this did not take into account common message segment length distributions. @curtries looked into this a bunch more and found 10-20% to be a much more accurate threshold for when filter landlines saves a campaign money.
Closes #965
Big spreadsheet.
@curtries does this need to be updated anywhere on docs.spokerewired.com?
> fix: update copy for filter landlines section

- src/server/tasks/assign-texters.ts
Dramatically improve performance of `assignPayloads` query for clients with a large number of `campaign_contact` rows.
There is only a partial index on `campaign_contact.assignment_id` so the `assignment_counts` CTE was doing a full scan
on `campaign_contact` for that stage. Adding the `campaign_id` condition turns that into an index scan
with `assignment_id` as a filter condition.
It could be further improved by limiting the use of the Texters section to unarchived campaigns: https://explain.depesz.com/s/fvsH
The `ensureAssignments` query being blocked by the `assignPayloads` query can likely be explained by:
1. User saves Texter section
2. `assignPayloads` takes a long time to run
3. User cancels the job; `assignPayloads` query continues to run in the background (see #981)
4. User saves …
> perf: fix sequential scan on campaign_contact

- migrations/20210608211851_unsolicited_messages.js
- src/server/api/lib/assemble-numbers.ts
Store unsolicited inbound messages.
Logging `Could not match inbound assemble message to existing conversation` as an error-level log is an incorrect use case for error-level logs. Rather than just changing the log level, this plops them into a table for a later feature to do something with.
This has been tested by overriding the `from` value on the inbound message to force it not to match an existing conversation. No test suite for this, however.
N/A
N/A - nothing user-facing in this PR.
> feat: store unsolicited inbound messages

- src/server/tasks/sync-campaign-contact-to-van.ts
Pass the "SMS Text" contact type for VAN canvass responses.
Closes #988 
Nikki at NGP VAN confirmed that contact type IDs are consistent across VAN instances.
N/A
N/A
> feat(van): use 'SMS Text' contact type for canvass responses

- src/server/tasks/sync-campaign-contact-to-van.spec.ts
- src/server/tasks/sync-campaign-contact-to-van.ts
Fix edge case where canvass result with both result code _and_ responses is sent to VAN by recording responses and opt-outs separately.
This was prompted by a customer ticket regarding sync errors. Inspecting the Spoke logs showed a few 400 responses from VAN:
```json
{
"errors": [
{
"code": "INVALID_PARAMETER",
"text": "'resultCodeId' must be null when responses are specified.",
"properties": [
"resultCodeId"
]
}
]
}
```
The only code path that allows a `resultCodeId` _and_ `responses` is if the contact is opted out. Spot checking the `campaign_contact` records for these failed syncs confirmed this hypothesis.
See changes to `sync-campaign-contact-to-van.spec.ts`.
N/A
N/A
> fix(van): fix sync for contacts with both opt out and responses

- src/components/AssignmentSummary/index.tsx
This fixes the date format by using the correct [tokens for Luxon](https://moment.github.io/luxon/#/formatting?id=table-of-tokens).
The previous format "works" but looks ugly and unprofessional.
N/A
> fix: use correct date format for luxon

- src/api/campaign.ts
- src/containers/AdminCampaignStats/DeliverabilityStats.tsx
- src/containers/AdminCampaignStats/index.jsx
- src/server/api/lib/campaign.ts
Specify that deliverability stats only include outbound messages to avoid confusion.
This also bundles `SENDING` and `SENT` statuses for accuracy.
The difference between the deliverability counts and full message export counts can seem like a discrepancy if you don't know that deliverability only includes outbound messages. The copy change in this PR aims to make this clear.
This has been tested locally/
The section title has been updated here:
https://docs.spokerewired.com/article/121-campaign-metrics
> fix: disambiguate deliverability stats

- __mocks__/assemble-numbers.ts
- __mocks__/twilio.ts
- __test__/testbed-preparation/core.ts
- package.json
- src/server/api/lib/assemble-numbers.ts
- src/server/api/lib/twilio.js
- src/server/api/types.ts
- src/server/tasks/handle-delivery-report.spec.ts
- src/server/tasks/handle-delivery-report.ts
- yarn.lock
Delete records from `log` after `handle-delivery-report` completes.
There is no need to keep a log record around once it has been successfully processed. A large log
table only makes it more difficult to debug when delivery reports have _not_ been processed
correctly.
See `src/server/tasks/handle-delivery-report.spec.ts`.
N/A
N/A
> feat: delete log record after processing

- src/components/forms/GSForm.jsx
Fix handling of errors in GSForm so that error messages are actually displayed.
Closes #934.
N/A
> fix: display gsform errors

- src/server/auth-passport.ts
Replace empty string phone numbers from Slack with `'unknown'`.
Slack profiles without a phone number send an empty string, not null. Using the null coalescing
operator, ??, results in saving this empty string. That in turn prevents editing user records.
Related to #934.
```sh
$ node
> console.log('' ?? 'unknown');
> console.log('' || 'unknown');
unknown
```
N/A
N/A
> fix(slack): set unknown phone number for empty string

- src/components/Login.tsx
- src/server/auth-passport.ts
Preserve the `nextUrl` query param through the Slack OAuth flow.
The `nextUrl` query param is very important for user experience (e.g. only needing to visit the join link once). Preserving it through the login process allows us to redirect the user to the correct location post-Slack login.
N/A
N/A
> fix: preserve nextUrl through slack login flow

- migrations/20210902145452_improve-trollbot-perf.js
- schema-dump.sql
This improves the performance of `get_trollbot_matches` by only running a ts_query for each token if we have already determined that the message matches at least one token for that stemming mode.
We think the long running query times of trollbot may have been negative impacting some other queries, particularly delivery report handling.
Running the query directly on production - just a select.
> feat(trollbot): improve query perf

- migrations/20210902181911_add-missing-primary-keys.js
- schema-dump.sql
Ensure every table has a primary key or a replica identity set.
Clickhouse's MaterializedPostgreSQL engine requires that every synced table have a primary key or a replica identity set.
Replica identity seemed like the easiest approach for `messaging_service_stick` after attempting the following:
```sql
alter table public.messaging_service_stick
add constraint messaging_service_stick_pkey primary key using index messaging_service_stick_cell_organization_unique_constraint;
```
but getting error:
```
- index "messaging_service_stick_cell_organization_unique_constraint" is already associated with a constraint
```
Tables without primary keys were identified using:
```sql
select tab.table_schema,
tab.table_name
from information_schema.tables tab
left join information_schema.table_constraints …
```
> fix: add missing primary keys

- src/server/api/lib/assemble-numbers.ts
- src/server/tasks/resend-message.ts
- src/server/worker.ts
This adds a resend message task + inline instructions to re-queue it.
Sometimes, we have to resend messages. This makes it possible from a running Spoke deployment, which is much easier than any alternative.
I've run this before locally.
> feat: add resend-message task

- src/api/notice.ts
- src/api/schema.js
- src/components/AdminDashboard.jsx
- src/components/NotificationCard.tsx
- src/server/api/schema.js
- src/server/lib/notices.ts
- src/server/lib/notices/index.ts
- src/server/lib/notices/register-10dlc-brand.ts
- src/server/lib/notices/types.ts
Add a notice prompting organization owners to provide their 10DLC registration information.
ToDo:
10DLC registration needs to happen.
<p align="center"><i>Owner notification</i></p>
</td></tr>
<tr><td>
<p align="center"><i>Admin notification</i></p>
The 10DLC page needs to be updated with latest updates, cost, etc.
> feat: add 10dlc registration notice

- src/api/messaging-service.ts
- src/api/organization.ts
- src/api/schema.js
- src/containers/Settings/components/General.jsx
- src/containers/Settings/components/Review10DlcInfo.tsx
- src/containers/Settings/components/queries.ts
- src/server/api/messaging-service.ts
- src/server/api/organization.js
- src/server/api/schema.js
Add Settings section with link to 10DLC registration form.
Users must otherwise bookmark the registration form page in order to come back and make changes.
<p align="center"><i>10DLC Registration Form Section</i></p>
> feat(10dlc): add registration link to settings

- src/components/NotificationCard.tsx
- src/server/lib/notices/register-10dlc-brand.ts
Handle errors when fetching 10DLC registrations.
Spoke Portal schema is fluid and errors in the GraphQL request should not break Spoke.
N/A
N/A
> fix(10dlc): handle graphql errors

- migrations/20211026163248_troll-mode-text.js
- schema-dump.sql
Store mode as `text` instead of `regconfig`.
`pg_upgrade` does not support upgrading of databases containing table columns using these reg* OID-
referencing system data types, including regconfig.
N/A
> fix: change mode column type to text

- src/server/api/notice.ts
- src/server/api/schema.js
Add resolver for GraphQL `Notice` type.
For completeness and to silence server warning.
N/A
N/A
> chore: add resolver to Notice

- src/server/api/lib/campaign.ts
- src/server/api/lib/interaction-steps.ts
- src/server/api/schema.js
- src/server/contexts.ts
Include all campaign properties when copying a campaign.
Copying a campaign previously missed:
- Due date
- Logo image url
- Primary color
- Campaign groups
- Teams
This is very frustrating.
Closes #1030 
N/A
N/A
---
- https://app.asana.com/0/0/1201586497754434
> fix: copy complete campaign

- src/api/campaign-contact.ts
- src/api/campaign.ts
- src/api/canned-response.ts
- src/api/interaction-step.ts
- src/api/schema.js
- src/server/api/lib/campaign.ts
- src/server/api/schema.js
This pulls up the editCampaign method into a typed file.
I thought this made sense as part of a different change. It did not, but still good to do.
Breaking up schema.js is good.
Typing things is good.
This has been tested manually by going through each section of the campaign builder, making changes, saving, and verifying the correct result.
N/A
N/A
> refactor: pull up editCampaign

- src/containers/AdminCampaignEdit/sections/CampaignContactsForm/components/SelectExcludeCampaigns.tsx
- src/containers/AdminCampaignEdit/sections/CampaignContactsForm/index.tsx
- src/server/middleware/app-renderer.js
- src/styles/theme.ts
This moves the campaign exclusion selector below the contact upload file drop and adds the word "**optionally**" to the instructions.
It is easy to interpret the campaign exclusion feature in contact upload as required, rather than
optional. This leads to confusion and support tickets for why a campaign has zero contacts.
Closes #1044.
N/A
> fix: clarify that contact filtering is optional

- src/lib/scripts.spec.ts
- src/lib/scripts.ts
Use title case instead of uppercase for name fields.
Names like 'Anne Marie' should be title cased not uppercase (e.g. 'Anne marie').
Closes #1038
See `scripts.spec.ts`.
N/A
N/A
---
- https://app.asana.com/0/0/1201668494519507
> fix: use title case for name fields in scripts

- src/server/api/lib/campaign.ts
Ensure autoassign is disabled for all copied campaigns.
Like starting a campaign, enabling autoassign should be a conscious decision.
Closes #1039 
N/A
N/A
N/A
---
- https://app.asana.com/0/0/1201668628977620
> fix: leave autoassign disabled for copied campaigns

- __test__/lib/session.ts
- src/api/organization-settings.ts
- src/api/organization.ts
- src/api/schema.js
- src/client/App.tsx
- src/client/spoke-context.tsx
- src/components/OrgSettingsFetcher.tsx
- src/containers/Settings/components/queries.ts
- src/server/api/organization-settings.ts
- src/server/organization-settings.spec.ts
This is a bandaid fix to allow organization settings request to succeed for texters.
A full fix depends on #1027 in order to better support partial success responses. Current `apollo-client` tooling is all-or-nothing. We want to attempt to fetch all organization settings fields knowing that we may not have permission for all of them and handling that as it comes.
`organization-settings.spec.ts` and local testing.
N/A
N/A
> fix: fix read permissions for organization settings

- src/containers/AdminBulkScriptEditor/index.jsx
- src/containers/AdminCampaignEdit/index.jsx
- src/containers/AdminCampaignEdit/sections/CampaignTextersForm/components/TexterAssignmentHeaderRow.tsx
- src/containers/AdminCampaignStats/CampaignStat.jsx
- src/containers/AdminCampaignStats/index.jsx
- src/containers/AssignmentTexterSurveyDropdown.jsx
- src/server/middleware/app-renderer.js
Remove bolding introduced by #1045.
Spoke had a number of places using bold that were not actually visible because only the regular weight font was loaded. #1045 added the bold weight font and suddenly these sleeping bold segments reared their heads.
N/A
N/A
> fix: remove undesired bolding

- .github/workflows/ci-cd.yml
Pass the `SPOKE_VERSION` build argument to the image build step.
This was lost in #1001.
See https://github.com/docker/build-push-action/blob/4222161e3eb8351d8999164540f8c32116f921fa/UPGRADE.md#simple-workflow
N/A
N/A
> ci: add spoke version docker build arg

- yarn.lock
Update the `caniuse` browsers list.
Resolve the yarn warning.
```sh
yarn browserslist --update-db
```
N/A
N/A
N/A
> chore: update caniuse browsers list

- src/server/api/schema.js
Create Organization was pulling in the incorrect types, and the server would fail trying to create a new org, this fixes it.
Created multiple new organizations to test.
NA
> fix: fix create org using the wrong types

- src/containers/AdminCampaignList.jsx
Fix GraphQL operation variable type mismatch.
Newer versions of Apollo are strict about types matching and will not coerce values for you.
This resulted in the following error:
This has been verified locally.
N/A
N/A
> fix: convert string to float

- src/components/AuthzProvider.tsx
Navigate to login page only when there is an error fetching a user's roles for an organization.
This restores previous functionality. #1063 mistranslated [this](https://github.com/politics-rewired/Spoke/pull/1063/files#diff-8f17a437bd717cb709cda1a6bbdce2b6dc27b3a5124fbab1af2a9147f9670529L29-L46).
N/A
N/A
> fix: navigate to login only on error fetching roles

- package.json
- src/components/ScriptEditor.tsx
- src/lib/scripts.ts
- yarn.lock
Fixes #874 
Add an indicator indicating if a message is going to possibly be sent as an SMS or MMS. 
Also add a warning if the attachment is not of the content type image.
This PR also adds axios as a full dependency, it's currently installed as a sub dependency of a different library. 
Fixes #874 
This shows the user the type of message being sent, also shows a warning about potentially sending incorrect image or other attachments. 
Tested locally using multiple image and non image URLs
NA
> feat(script): add indicator of message type, check if attachment is image

- src/server/tasks/export-campaign.ts
Fixes #1068 
Luxon DateTime was unable to properly parse a valid datetime object, falling back to parsing with
node Date, works better since the ORM returns a valid date type object, and not a string
Fixes #1068 
Tested locally with multiple exported campaigns
NA
> fix(export-campaign): fix attemptedAt being empty in export

- src/containers/AdminCampaignEdit/index.jsx
- src/containers/AdminCampaignEdit/sections/CampaignBasicsForm.tsx
- src/server/api/assignment.js
- src/server/api/campaign.js
Make Due Dates optional, also add a button to delete the due date, the current date selector doesn't allow putting in a null value, adding the delete button makes it so that you can remove the due date during campaign edit.
Fixes #1056 
Tested working locally. Contacts are pulled as expected.
NA
> feat: make due dates for campaigns optional

- src/server/api/lib/send-message.ts
Only replace short links in messages if environment variable is set.
If the short link rotation feature is disabled after a period of use, there may be stale records in `link_domain` table. Once the feature is disabled, these domains are still being swapped but the user has no access to the link domain records to control this.
N/A
N/A
N/A
> fix: enable link replacement only if envvar is enabled

- src/api/campaign.ts
- src/api/external-system.ts
- src/api/organization.ts
- src/api/schema.ts
- src/components/AssignmentTexter.jsx
- src/components/TexterRequest.jsx
- src/containers/AdminPeople/AdminPeople.tsx
- src/containers/UserEdit.jsx
- src/schema.graphql
- src/server/api/organization.js
- src/server/api/schema.js
- src/workers/jobs/index.js
Use string type for all client-side IDs.
This also fixes a separate bug in changeUserPassword where `db` context was not passed to helper.
This also fixes a separate bug where assignment team dropdown did not render correctly if the team did not have a maxRequestCount set.
GraphQL uses string-type IDs. All handling of IDs on the client side and over the networks should be strings.
Manual testing of:
N/A
N/A
> fix: convert client-side id args from int to string

- src/components/IncomingMessageActions.jsx
Disable the "Reassign all matching" button unless at least 1 reassignment target texter has been selected.
Fixes #1093
N/A
> fix: disable reassign all without target texter(s)

- .github/workflows/ci-cd.yml
Use the [new `gha` cache type](https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#cache-backend-api).
Using a GitHub Actions-native cache type improves build times.
The ci-cd workflow for this PR.
N/A
N/A
> ci: use gha cache type

- src/server/api/assignment.js
Handle early return from `getContacts()` that returns an empty array instead of a Knex query object.
Otherwise this causes `contactsQuery.select is not a function` error.
N/A
N/A
> fix: handle overdue early return case

- src/containers/AdminCampaignEdit/sections/CampaignBasicsForm.tsx
Read the current pending changes, and change due date in that, instead of overriding pending changes
Fixes #1101
Tested locally with creating new, and editing old campaigns
> fix: delete due date button clearing up other fields

- src/api/campaign.ts
- src/containers/CampaignList/CampaignListRow.tsx
- src/schema.graphql
This fixes the campaign list page for the Supervolunteer role.
The `campaignGroups` resolver requires at least Admin role. This means it returns `null` for Supervolunteer. The field was not previously nullable, however, so this resulted in an error and broken page.
N/A
N/A
> fix: handle null campaign groups for supervolunteer role

- migrations/20220115111920_support-superadmin-campaign-approval.js
- src/server/api/campaign.js
This ensures a non-null value for the `isApproved` GraphQL property added in #1050.
The migration in #1050 added a default of `false` for the `is_approved` column but did not set `not null` so there may still be null values in production.
TBD
N/A
N/A
> fix: ensure non-null value for campaign isApproved

- src/components/AssignmentTexterSurveys.jsx
This fixes conditional logic for displaying past survey questions.
It also sets the dropdown width to auto, addressing some user complaints, and makes expand/collapse icons more intuitive for vertically-expanding card.
Previous logic did not handle the case of a single already answered survey question.
Closes #1115 .
This as been tested locally.
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
N/A
> fix: fix display of survey questions

- migrations/20220223123406_add_suspended_user_type.js
- src/api/organization-membership.ts
- src/api/schema.ts
- src/containers/AdminCampaignEdit/sections/CampaignTextersForm/components/TexterAssignmentRow.tsx
- src/containers/AdminCampaignEdit/sections/CampaignTextersForm/index.tsx
- src/containers/AdminCampaignEdit/sections/CampaignTextersForm/queries.ts
- src/containers/AdminCampaignEdit/sections/CampaignTextersForm/types.ts
- src/containers/AdminIncomingMessageList/index.jsx
- src/containers/AdminPeople/AdminPeople.tsx
- src/containers/AdminPeople/Dialogs.tsx
- src/containers/AdminPeople/PeopleRow.tsx
- src/containers/PaginatedUsersRetriever.jsx
- src/lib/permissions.ts
- src/schema.graphql
- src/server/api/lib/send-message.ts
- src/server/api/organization.js
- src/server/api/schema.js
- src/server/api/user.js
Allow users to be marked as suspended, not giving them access to the organization anymore
Marking a user as suspended does the following:
1. Not allowed to be assigned texts to from the campaign edit screen
2. Cannot see any texts on the todo page
3. Cannot be assigned any texts in the message review page
4. Cannot login (will get an access denied error)
Fixes #899 899
Tested locally for the above scenarios
Probably needs some changes talking about suspended users, will ask Ben for help updating this
> feat: allowing suspending users

- src/server/api/campaign.js
Fix permission checks in resolver for `Campaign.previewUrl`.
Message Review uses the `loadData()` HOC which does not allow for ignoring expected GraphQL errors. We must explicitly return `null` for `previewUrl` if the permissions check fails.
The permissions check also needs to look at the organization setting to determine which role is sufficient.
N/A
N/A
> fix: fix permissions in script preview url resolver

- .github/workflows/ci-cd.yml
When building container images for feature branches the branch name is used for the image tag. This change replaces `/` in branch names with `-`.
`/` is not allowed in container image tags.
This has been tested in #1128 .
N/A
N/A
> ci: replace / with - in image name

- libs/spoke-codegen/src/graphql/message-review.graphql
- src/api/campaign-contact.ts
- src/components/IncomingMessageList/ConversationPreviewModal.tsx
- src/components/IncomingMessageList/MessageColumn/index.tsx
- src/components/IncomingMessageList/SurveyColumn/index.tsx
- src/schema.graphql
This updates the conversation modal to:
- be fully typescript
- use material ui v4 components
- use functional components and hooks over stateful class components
All three of these are goals for the entire codebase.
This also serves as the foundation for additional work on message review.
N/A
N/A
> refactor: convert conversation modal to ts, muiv4, functional components

- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/components/InteractionStepCard.tsx
- src/server/routes/campaign-preview.js
This adds the ability to collapse interaction step children.
Managing large scripts can get complicated. The ability to collapse a section of it makes navigating the script much easier.
Closes #912.
<table>
<tr><td>
</td></tr>
</table>
N/A
> feat: allow collapsing interaction steps

- package.json
Require Node compatible with v16.
#1097 updates package.json to allow Node versions greater than v16 LTS. However, we are still using packages that rely on deprecated methods, which produces errors if using current release (v17) in local development. Additionally, we would expect similar errors if using v18 when it is released (soon) and later becomes LTS.
> build: use node compatible with v16

- src/components/CampaignNavigation.tsx
- src/containers/AdminCampaignEdit/index.jsx
- src/containers/AdminCampaignStats/index.jsx
This adds a button to the campaign edit page that allows navigation to the campaign stats page.
To navigate to the campaign stats page from the campaign edit page, users must currently edit the url directly (ex. admin/1/campaigns/1/edit → admin/1/campaigns/1).
> feat: allow navigation to campaign stats page from campaign edit page

- src/api/campaign-contact.ts
- src/components/IncomingMessageList/ConversationPreviewModal.tsx
- src/schema.graphql
Adds contact's name and campaign title to the message review conversation modal.
This is important information when reviewing conversations.
Closes #831.
N/A
> feat: add contact name and campaign title to message review

- src/components/IncomingMessageList/index.jsx
Display campaign IDs in the message review table.
Closes #831
N/A
> fix: add campaign id to conversation rows

- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/components/InteractionStepCard.tsx
Restore the previous styling to interaction step card headers.
#1137 updated the card components to material ui v4, changing the typography of the header in an undesirable way.
N/A
> fix: remove header element styling from interaction step titles

- libs/spoke-codegen/src/graphql/canned-responses.graphql
- src/api/assignment.ts
- src/components/CannedResponseMenu/hooks.ts
- src/components/CannedResponseMenu/index.tsx
- src/components/CannedResponseMenu/types.ts
- src/containers/AssignmentTexterContact/index.jsx
- src/schema.graphql
This fixes the permission error introduced by #1142.
Texters do not have access to Campaign resources directly. Instead they must go through Assignment resources they do have access to.
So in Texter view we only have access via `assignment` and in Message Review we are only guaranteed to have access to campaign resource (conversation may be unassigned). So we support fetching canned responses via assignment or campaign (but not both).
This has been tested locally with Texter and Owner role in Texter and Message Review, respectively.
N/A
N/A
> fix: fix fetching canned responses by texters

- package.json
- yarn.lock
Upgrades react v17
MUI v5 relies on React V17, and upgrading to v17 allows us to use the nicer Data Grid from MUI v5
Tested locally
> chore(react): upgrade react to v17

- package.json
- src/components/ApplyTagConfirmationDialog.jsx
- yarn.lock
This upgrades [`react-markdown`](https://github.com/remarkjs/react-markdown) to v8.
Yarn complains about v4 compatibility with React 17.
N/A
N/A
> chore: upgrade react-markdown to v8

- src/server/routes/campaign-preview.js
Remove quotes around script values on campaign  preview page.
Script values are often copied from the campaign preview into a different campaign. The user building the campaign must remember to remove the quotes, a step which can easily be missed.
<table>
<tr><td>
<p>before</p>
</td><td>
<p>after</p>
</tr></table>
N/A
> fix: remove quotes around campaign preview script values

- package.json
- src/containers/AdminCampaignEdit/sections/CampaignContactsForm/components/CSVForm.tsx
- yarn.lock
This updates [`react-file-drop`](https://github.com/sarink/react-file-drop) to v3.
Yarn complains about v0.2 compatibility with React 17.
N/A
N/A
> chore: upgrade react-file-drop to v3

- src/server/lib/templates/notification.tsx
- src/server/mail.ts
- src/server/tasks/queue-pending-notifications.ts
- src/server/tasks/send-notification-email.ts
This adds retry behavior to notification email sending.
It may be the case that generating email content is either
1. not being awaited correctly (see [SO post]), or
2. returning empty content some of the time
We should throw an error and retry in both these cases.
We should also throw an error for unrecognized notification template types rather than returning a an empty `<div />` as content.
[SO post]: https://stackoverflow.com/a/54484820
I was able to reproduce the empty message error locally only once but was not able to capture enough detail to debug why the content is empty.
N/A
N/A
---
- https://app.asana.com/0/0/1202266689193943
> fix: throw error and retry on empty email

- src/containers/AdminAutosending/components/AutosendingTargetRow.tsx
- src/containers/AdminAutosending/index.tsx
- src/server/tasks/queue-autosend-initials.spec.ts
- src/server/tasks/queue-autosend-initials.ts
- src/server/tasks/retry-interaction-step.ts
This PR makes 4 changes to autosending:
- Changes the status header to clarify that it's the Autosend Status instead of the campaign status
- Changes the "Waiting to Send" count to exclude opted out contacts
- Modifies the behavior of `queue-autosend-initials` to autosend unassigned messages as well
- Unassigns contacts after they've been autosent
Feedback from user testing.
Locally, + test
Need to update autosending HelpScout page to clarify the 2 behavioral changes above.
> fix: cleanup autosending

- src/components/forms/GSForm.jsx
This fixes a crash when using Tooltip within GSForm.
The `children` prop of a Tooltip must be a single element [1]. GSForm recursively maps all child
elements, turning all `children` props into arrays.
[1] https://github.com/mui/material-ui/issues/25163
N/A
N/A
> fix(mui): ignore tooltips within gsform

- src/server/app.ts
Temporarily disable the secure option for `express-session` cookies.
Sessions do not work in production otherwise.
`ingress-nginx` is not setting the correct `X-Forward-Proto` header, breaking `secure`.
https://github.com/kubernetes/ingress-nginx/issues/8195
This has been tested on stagingenv.
N/A
N/A
**To-do**
> fix: disable secure option for session cookies

- src/containers/AdminTeamEditor/index.jsx
Pass `assignmentPriority` as a number, matching the GraphQL schema.
Currently, saving a team throws a generic 400 error.
N/A
N/A
> fix: pass assignmentPriority as Int

- libs/spoke-codegen/src/graphql/autosending.graphql
- src/api/campaign.ts
- src/containers/AdminAutosending/components/AutosendingTargetRow.tsx
- src/schema.graphql
- src/server/api/campaign.js
- src/server/memoredis.ts
- src/server/tasks/queue-autosend-initials.ts
This PR makes 3 changes to autosending:
- Changes the "Waiting to Send" count to exclude opted out contacts (using a query)
- Prevents starting autosending on a campaign where there are no more initials
- Modifies the behavior of queue-autosend-initials to mark a campaign as complete if there are no more contacts with 0 sending attempts for the campaign
Feedback from user testing.
> fix: cleanup autosending counts

- src/server/api/assignment.js
This treats escalated tags the same way within assignLoop as it does fetching assignment targets.
Currently, `assignLoop()` will try to assign conversations for a given target with custom escalation tags before other conversations for that target (`if myEscalationTags.length > 0`). Escalation tags are currently only included in `myEscalationTags` if auto-assignment is enabled for the custom escalation team.
This means a campaign with only custom escalation conversations can be picked as the preferred assignment target via `myCurrentAssignmentTargets()`, which does not care whether auto-assignment for custom escalation team is enabled or not, but then not have any conversations to assign within `assignLoop()`, which does care if the custom escalation team is enabled.
This standardizes on …
> fix: bring assign loop into alignment with assignment targets

- src/containers/AdminIncomingMessageList/components/IncomingMessageFilter.tsx
Use path-style import.
See https://github.com/politics-rewired/Spoke/pull/1180#pullrequestreview-968560860
Part 1 for [`fix-texter-select-autocomplete`](https://github.com/politics-rewired/Spoke/compare/fix-texter-select-autocomplete?expand=1) (#1201).
N/A
N/A
> style: prefer path import

- libs/spoke-codegen/src/graphql/general-settings.graphql
- libs/spoke-codegen/src/graphql/spoke-context.graphql
- src/api/organization-settings.ts
- src/api/schema.ts
- src/containers/AdminCampaignEdit/index.jsx
- src/containers/Settings/components/CampaignBuilderSettingsCard.tsx
- src/schema.graphql
- src/server/api/organization-settings.ts
This adds Basic / Advanced (default) campaign builder modes.
Closes #1183 
Campaign builder modes should be documented, but are not yet.
> feat(campaign-builder): add basic mode

- src/server/auth-passport/auth0.ts
- src/server/auth-passport/local.ts
- src/server/auth-passport/slack.ts
- src/server/models/cacheable_queries/user.ts
Check `is_suspended` in a safe way.
Evaluating `user.is_suspended` throws a TypeError when user is undefined.
N/A
N/A
> fix(session): handle suspension check when no user is found

- libs/spoke-codegen/src/graphql/template-campaigns.graphql
- src/api/campaign.ts
- src/api/organization.ts
- src/api/schema.ts
- src/components/AdminDashboard.jsx
- src/containers/AdminCampaignEdit/index.jsx
- src/containers/AdminCampaignEdit/queries.ts
- src/containers/AdminTemplateCampaigns/components/TemplateCampaignRow.tsx
- src/containers/AdminTemplateCampaigns/index.tsx
- src/routes.jsx
- src/schema.graphql
- src/server/api/campaign.js
- src/server/api/lib/campaign.ts
- src/server/api/organization.js
- src/server/api/schema.js
- src/server/api/types.ts
- src/server/models/cacheable_queries/campaign.js
- src/server/models/index.ts
This adds management of Template Campaigns.
It also fixes a small bug in how `editCampaign()` handles editing `texters` and brings it in line with how other sections are handled.
Part 2 of 3 for #1181.
<table>
<tr><td>
Template Campaign management.
</td><tr>
<tr><td>
Campaign Builder
</td><tr>
</table>
This is user-facing and should be documented, but is not yet. Documentation will be added as part of part 3 (creating campaigns from templates).
> feat: add template campaigns

- src/server/api/types.ts
- src/server/app.ts
- src/server/auth-passport/auth0.ts
- src/server/auth-passport/local.ts
- src/server/auth-passport/slack.ts
- src/server/auth-passport/util.ts
- src/server/models/cacheable_queries/user.ts
This PR does a few things:
- Standardizes return type of Passport strategies on Spoke user record. This involves moving all Spoke user checking and creation into all Passport strategies (as Passport examples show it is intended to be done).
- Consolidates all post-authentication logic into a single `passportCallback`.
This is the intended Passport flow: the strategy callback processes the authentication result and returns an _application_ user. That application user, standardized across all strategies, is what we store in the session.
This fixes an issue where `auth0Id`-based sessions (`auth0` and `slack` strategies) couldn't be stored because `express-session` expected a Spoke user's _integer_ ID, not text.
This has been tested locally:
N/A
N/A
> fix(passport): standardize on spoke user

- libs/spoke-codegen/src/graphql/campaign-list.graphql
- package.json
- src/api/campaign.ts
- src/containers/CampaignList/CampaignList.tsx
- src/containers/CampaignList/CampaignListLoader.tsx
- src/containers/CampaignList/CampaignListMenu.tsx
- src/containers/CampaignList/CampaignListRow.tsx
- src/containers/CampaignList/index.jsx
- src/containers/Settings/components/General.jsx
- src/schema.graphql
- yarn.lock
This removes the intermediate React state layer between the Apollo cache and the component. It also refactors as a functional component and simplifies infinite scrolling.
The intermediate React state layer renders Apollo cache side effects useless and leaves a full page refresh as the only option for updating campaign list data.
Part 3 of 4 for #1181.
N/A
N/A
> chore: use apollo-native pagination

- src/api/campaign.ts
- src/schema.graphql
This changes the campaign stats type to have only non null fields.
All of these stats should be valid numbers and not null.
> fix: require returning non null campaign stats

- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/index.tsx
- src/containers/AssignmentTexterContact/index.jsx
This updates the save button on the campaign edit page to be contained, and adds margins to buttons on the texter assignment page.
Closes #1199
<table>
<tr>
<th>Admin</th>
<th>Texter</th>
</tr>
<td>
</td>
<td>
</td>
</table>
> fix: match mui v0 styling with v4 buttons

- src/server/api/schema.js
This adds the resolver for the `createTemplateCampaign` mutation.
I was not careful enough with my `git add --patch` scalpel in #1214.
N/A
N/A
> fix(template-campaigns): add missing resolver

- libs/spoke-codegen/src/graphql/template-campaigns.graphql
- src/api/schema.ts
- src/components/CreateCampaignFromTemplateDialog.tsx
- src/containers/AdminCampaignList.jsx
- src/schema.graphql
- src/server/api/lib/campaign.ts
- src/server/api/schema.js
This adds the ability to create a campaign (or campaigns) from a template campaign.
Closes #1181.
<table>
<tr><td>
Create from Template
</td>
<td>
Create blank
</td></tr>
<tr><td colspan="2">
Creating many from template
</td></tr>
</table>
This feature will need to be documented.
> feat: add option to create campaign(s) from template

- src/components/ScriptOptionBlock.tsx
- src/components/forms/GSScriptOptionsField.jsx
- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/index.tsx
- src/lib/scripts.ts
This brings variable highlighting to the script field displayed on interaction step cards.
It also adds script tokenization utils to use for future work.
Script variable highlighting was previously only available in the script draft editor.
N/A
N/A
> feat: add script styling to interaction step

- libs/spoke-codegen/src/graphql/campaign-variables.graphql
- migrations/20220519111425_add-campaign-variables.js
- package.json
- schema-dump.sql
- src/api/campaign-variable.ts
- src/api/campaign.ts
- src/api/schema.ts
- src/containers/AdminCampaignEdit/components/SectionWrapper.tsx
- src/containers/AdminCampaignEdit/index.jsx
- src/containers/AdminCampaignEdit/sections/CampaignVariablesForm.tsx
- src/containers/AdminCampaignEdit/types.ts
- src/lib/scripts.ts
- src/schema.graphql
- src/server/api/campaign-variable.ts
- src/server/api/campaign.js
- src/server/api/lib/campaign.ts
- src/server/api/schema.js
- src/server/api/types.ts
- yarn.lock
This adds management of campaign variables.
Part 1 of 2 for #1184.
This has been tested locally and in beta channel releases.
TBD
> feat: add campaign variable management

- src/server/tasks/queue-autosend-initials.ts
This orders contacts eligible for autosend to be ordered by campaign id first. It also changes ordering to send unassigned initials first, then assigned initials. 
Possibly a cause of marking autosent campaigns as complete before all initials have been queued.
This has been tested locally (fix for marking campaigns complete early is not confirmed).
> fix: order autosend contacts by campaign id first

- src/server/tasks/queue-autosend-initials.ts
This updates autosending completion to be marked once all initials for a campaign have been sent.
Campaigns that were autosending were marked as complete early if multiple campaigns were queued at the same time.
> fix: fix early marking of autosend campaign as complete

- src/containers/AdminAssignmentControl/AssignmentRow.tsx
This updates the MUI v4 chips upgraded in #1166 to the previous centered styling. This also removes inline styles and replaces them with Grid component layout.
Users were thrown off by the non centered styling introduced in #1166.
> fix: fix assignment control layout

- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/components/InteractionStepCard.tsx
This adds a badge with a count of child interaction steps to the collapsed interaction step card.
Collapsed interactions steps don't clearly indicate how large the tree below them is. This also supports future work to simplify the basic campaign builder.
<table>
<tr>
<th>Collapsed</th>
<th>Unfurled</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/76596635/169943548-fb851c44-be88-45e8-bc00-c5fb76334798.png"/></td>
<td><img src="https://user-images.githubusercontent.com/76596635/169943552-e56c143f-94d4-47d2-b100-529031940d9b.png"/></td>
</tr>
</table>
> feat: add interaction step badge

- libs/spoke-codegen/src/graphql/general-settings.graphql
- src/api/campaign.ts
- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/index.tsx
- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/resolvers.ts
- src/containers/AdminCampaignStats/index.jsx
- src/containers/AdminIncomingMessageList/components/IncomingMessageList/SurveyColumn/index.tsx
- src/containers/Settings/components/General.jsx
- src/containers/Settings/components/ScriptPreviewSettingsCard.tsx
This adds a button to view script preview to the interactions section.
Users may want to view an outline of the script while building campaigns rather than having to scroll through the entire interaction step tree, particularly when they are using basic mode for campaign building.
> feat: add script preview to interactions section

- src/server/api/schema.js
This fixes updating credentials for an external system when the underlying graphile secret somehow does not exist.
graphile-secrets throws an error when the requested secret isn't found. Spoke expects an undefined value.
Ref: https://secure.helpscout.net/conversation/1905190944/6480/
N/A
N/A
> fix(external-system): fix saving credentials

- src/server/api/lib/send-message.ts
- src/server/send-message-errors.ts
- src/server/tasks/retry-interaction-step.ts
This updates the [`retry-interaction-step.ts`](https://github.com/politics-rewired/Spoke/blob/main/src/server/tasks/retry-interaction-step.ts) job to return on the common errors thrown when sending. Only incorrectly configured jobs are marked as errored intentionally.
Closes #1229. #1244 makes opt out errors less common, but this is still good to have for opt outs that occur after the contact has been queued for autosending on another campaign, or for contacts queued at the end of texting hours.
> fix(autosend): return on expected errors

- src/containers/UserEdit.jsx
This fixes post-login redirect behavior for local passport strategy.
The standardized post-login redirect handler only looks at state preserved during oauth flow, not the nextUrl query param.
Local auth login is an async client request so a redirect response doesn’t even make sense as the way to handle successful login. Instead we can just use browser history.
N/A
N/A
> fix: fix post-login redirect behavior for local auth

- src/containers/UserEdit.jsx
This changes the notification frequency save  result alert to only show after an edit user operation.
The alert was showing after all local auth methods, including those where notification settings are not touched (eg login).
N/A
N/A
> fix: show notification settings alert only on user edit

- src/containers/AdminIncomingMessageList/components/IncomingMessageActions.tsx
This uses the user ID rather than the user organization ID for the texters dropdown list.
This was likely missed in development where user and user_organization usually will have the same auto incrementing IDs.
N/A
N/A
> fix(message-review): fix user id

- __test__/testbed-preparation/core.ts
- migrations/20220605032850_add_messaging_service_names.js
- migrations/20220605033846_add_messaging_service_to_campaign.js
- src/api/campaign.ts
- src/schema.graphql
- src/server/api/campaign.js
- src/server/api/lib/campaign.spec.ts
- src/server/api/lib/campaign.ts
- src/server/api/lib/message-sending.js
- src/server/api/schema.js
Part 1 of 3 allowing campaigns to pick their own messaging service for that campaign
Part 1 of #1232 
Tested Locally.
> feat: allow campaign to pick messaging service

- libs/spoke-codegen/src/graphql/campaign-builder.graphql
- libs/spoke-codegen/src/graphql/message-review.graphql
- src/components/ScriptPreviewButton.tsx
- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/index.tsx
- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/resolvers.ts
- src/containers/AdminCampaignStats/index.jsx
- src/containers/AdminCampaignStats/queries.ts
- src/containers/AdminIncomingMessageList/components/IncomingMessageList/SurveyColumn/index.tsx
- src/containers/AdminIncomingMessageList/components/IncomingMessageList/index.jsx
This creates a reusable component for script preview.
Closes #1251
> refactor: extract script preview button

- migrations/20220608035530_campaign-group-functions.js
- schema-dump.sql
This updates the functions `campaigns_in_group` to return records from `all_campaign`
These functions previously had a return type error due to the schema changes in #1211
> fix: fix return type in campaign group functions

- src/containers/AdminIncomingMessageList/components/IncomingMessageFilter.tsx
This uses the user ID rather than the user_organization ID for the message filter texters dropdown list.
Finishes fix started in #1261.
N/A
N/A
> fix(message-review): fix passing user ID

- src/server/api/lib/message-sending.js
The check for the profileId / messaging service sid on campaign happened when `campaign` was not available
This fixes reply handling currently broken in main
Tested locally using OpenPhone Number + ngrok setup. 
Tested for both old campaigns with no messaging_service_sid set, and new campaign with messaging_service_sid set.
> fix(replies): messaging_service_sid check in the incorrect section

- src/containers/AdminCampaignStats/index.jsx
This adds the permissions context back to the campaign stats page. Without this, the admin only buttons never loaded for admins.
Regression introduced in #1251.
> fix(campaign stats): use authz for button rendering

- src/containers/CampaignList/CampaignListLoader.tsx
- src/containers/CampaignList/utils.ts
This PR fixes error handling for anticipated "Forbidden" errors for supervolunteers.
Supervolunteers do not have permission to query campaign groups on a campaign. This results in expected "Forbidden" errors alongside the rest of the campaign list data.
Previously, we tried to print the `error` object itself and React complained about `object` being an invalid child element.
This PR fixes two things:
1. Filters out anticipated permission errors to only show unexpected errors
2. Displays errors using valid React children (e.g. `string`)
I went down a little rabbit hole looking into best practices for error handling in GraphQL but created #1270 rather than trying to address in this PR.
N/A
N/A
> fix(authz): handle supervol permission errors

- src/server/auth-passport/index.ts
- src/server/routes/auth.js
This fixes superadmin login for the alternate passports strategies.
This is required for superadmin login to work with passport changes in #1215. Currently, superadmin login breaks except when using the local strategy.
> fix: fix superadmin login

- src/api/organization-settings.ts
- src/components/TexterRequest.jsx
- src/containers/Settings/components/General.jsx
- src/containers/Settings/components/RejectedTextersMessageCard.tsx
- src/schema.graphql
- src/server/api/organization-settings.ts
Display tailored message in texter todos for users with assignment status Do Not Assign. 
Before merging will need new copy from @kohlee and @bchrobot 
Fixes #828
Tested Locally
> feat: display tailored message for do not assign texters

- src/components/TexterRequest.jsx
This fixes the texter request form.
Organization record ID was being compared to the user_organization record's ID.
N/A
N/A
> fix: fix texter request form

- src/config.js
- src/server/tasks/export-campaign.ts
This allows overriding the default chunk size of 1000 used to break up campaign export jobs.
This can help for instances where campaign export jobs are consistently timing out.
N/A
N/A
> feat: support setting custom campaign export chunk size

- src/config.js
- src/server/tasks/sync-campaign-contact-to-van.ts
This adds support for overriding the van contact type (ex. to use "Paid SMS" instead of "SMS Text").
This partially addresses #1277.
N/A
N/A
> feat: support overriding van contact type

- src/server/api/lib/campaign.ts
This fixes setting messaging services when copying a campaign, by using the object that's returned directly.
Creating campaigns from a template did not work after changes to this mutation in #1260 
> fix: fix copy campaign mutation

- .github/workflows/release.yml
This checks if the semver release is a prerelease and flags the GitHub release as such.
General best practices.
Also, some customers have GitHub alerts set up for releases and GitHub adds helpful disclaimer language to these when the release is marked as a prerelease.
See actions run for these commits:
N/A
N/A
> ci(release): mark GH prereleases appropriately

- src/server/api/campaign.js
Include the campaign ID when searching for campaigns with a `campaignTitle` filter parameter.
Users are often presented with `{id}: {title}` as the campaign title. When filtering by campaign
title we should filter against this "effective title" for consistency.
Closes #1300
N/A
---
- https://app.asana.com/0/0/1202532092161138
> fix(message-review): include campaign id in title search

- src/containers/AdminIncomingMessageList/components/IncomingMessageActions.tsx
- src/containers/AdminIncomingMessageList/components/IncomingMessageFilter.tsx
This adds the onClick listener to the Filters and Actions card headers rather than just the action button.
Users expect to be able to click on the entire header (as was previously the behavior).
Initial work for addressing #1302
N/A
N/A
---
- https://app.asana.com/0/0/1202532271228785
> fix(message-review): listen for clicks on entire card header

- src/server/api/lib/campaign.ts
- src/workers/jobs/index.js
The change to landlines being filtered can be slow depending on the load on the server, making the change earlier resets the result.
This fixes #907 
Tested locally
> fix: mark landlines as unfiltered on new contacts upload

- __test__/testbed-preparation/core.ts
- src/server/api/lib/campaign.spec.ts
This adds tests for creating templates and copying campaigns.
Test coverage for these areas is good to have as noted in #1285 
New tests added in this PR.
> test: add tests for campaign templates and copies

- src/api/organization.ts
- src/schema.graphql
- src/server/api/organization.js
This changes the messaging services object to be null when the user is not an owner. This prevents a "FORBIDDEN" GraphQL error from being thrown.
Users who were not owners couldn't load the campaign edit page, due to the "FORBIDDEN" GraphQL error that was in the response.
> fix(campaign builder): return nullable messaging services

- src/components/AssignmentTexter.jsx
- src/network/utils.ts
errors is sent out as an array, trying to throw an error of an array converts it to an `[Object object]`, instead use the message from the error objects to throw an error.
Fixes #1155 
Test locally.
> fix: handle response errors correctly

- migrations/20220714022406_use-run-at-in-queue_sync_campaign_to_van.js
- schema-dump.sql
This PR changes `queue_sync_campaign_to_van` to use `graphile-worker`'s `run_at` instead of named queues to prevent us from overloading VAN's API.
We have frequently run into this issue (https://github.com/graphile/worker/issues/240) when `queue_sync_campaign_to_van` is run.
This hasn't been tested yet!
> fix(queue_sync_campaign_to_van): use run at

- src/api/team.ts
- src/containers/AdminTeamEditor/index.jsx
- src/schema.graphql
This prevents saving a team with a null priority value, and also adjusts the GraphQL schema to allow retrieving teams which have null priority values.
Due to the visual bug on the create team form that presents an empty string value as 500 to the user, the user can create a team with a null priority. If a team with a null priority exists, loading the teams page isn't possible, because the GraphQL schema expects non null assignment priority values.
We generally want teams to have assignment priorities, but there are a number of database functions that already expect this column to be nullable. Assigning default priorities for team creation, and allowing the loading of teams if the priority value is null feels like a good solution here for these reasons.
> fix: fix saving empty team priority

- package.json
- src/client/lib/index.ts
- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/index.tsx
- src/containers/AdminTrollAlarms/index.tsx
- yarn.lock
Use `react-hook-clipboard` to read and write clipboard contents
Fixes #1153
Tested on Safari on macOS 12.4
> fix(clipboard): fix safari paste popup

- package.json
- src/client/lib/index.ts
- src/containers/AdminCampaignEdit/sections/CampaignInteractionStepsForm/index.tsx
- src/containers/AdminTrollAlarms/index.tsx
- yarn.lock
This reverts commit a9b753cfbb7059074191f07f9826a44e46c463b7.
#1326 fixed the Safari UX bug but changed behavior for accessing the clipboard. Previously, a user would need to click anywhere on the page for the browser to grant access to read the clipboard. After #1326 users have to click specifically on the interaction step card header.
We've decided we should revert the Safari fix in favor of a better user experience for the majority of our users on Chrome.
N/A
N/A
N/A
> revert(clipboard): revert fix safari paste popup

- .dockerignore
Ensure all files necessary to build Spoke are included in the Docker context with their current file extensions.
`build-config` was converted to TS in 608b90309244063488c76beedcfaa2cdc4aa862b.
`tsconfig.json` was somehow never part of the Docker context.
Builds were still succeeding in CI but recently began failing when running locally.
This has been tested locally and in CI (see workflow executions and parent commit of 4be6aa0aba0787ff35a12203a9081df9c78b0532).
N/A
N/A
> build: fix dockerignore rules

- src/server/api/lib/campaign.ts
This fixes a query performance issue fetching campaign fields for a campaign.
Only the names of custom fields are used by `invalidScriptFields()`. Every campaign contact will have the same custom field names so it does not matter which campaign contact we select from for a given campaign. The where clause and `order by` were performance issues on large instances.
Partly addresses #1331.
This has been tested locally and as hot fix in select production instances.
N/A
N/A
> fix(perf): fetch campaign

- src/server/api/lib/campaign.ts
Don't show duplicate warnings for missing custom fields or campaign variables.
Fixes #1331 
Tested locally
> fix(interactions): dont show duplicate warnings

- src/server/api/organization.js
Change permission required for messaging services to `ADMIN`
Fixes #1330 
Tested locally
> fix: allow admins to enumerate messaging services

- src/containers/AdminExternalSystems.tsx
Set text overflow to clip, so it doesn't convert buttons to ellipsis. 
Fixes #1283 
Tested locally
> fix: fix refresh integration button hidden

- .eslintrc.js
- src/lib/datetime.ts
- src/server/api/lib/autosend-initials.spec.ts
- src/server/api/lib/bulk-script-editor.ts
- src/server/api/organization-settings.ts
- src/server/api/schema.js
- src/server/api/types.ts
- src/server/models/cacheable_queries/user.ts
- src/server/organization-settings.spec.ts
Import `DeactivateMode` from server-defined type rather than client-defined type.
`@spoke/spoke-codegen` is meant for use in the client application only and will fail to import in production.
N/A
N/A
> fix: import server-defined type

- .eslintrc.js
- src/components/CampaignNavigation.tsx
- src/containers/AdminCampaignEdit/components/ApproveCampaignButton.tsx
- src/containers/AdminCampaignEdit/components/StartCampaignButton.tsx
- src/containers/AdminCampaignEdit/index.jsx
- src/containers/Settings/components/CampaignBuilderSettingsCard.tsx
- src/containers/Settings/components/ScriptPreviewSettingsCard.tsx
Require importing codegen using alias rather than relative path.
Codegen is an internal library and should be used like one.
N/A
N/A
> style: import codegen using alias rather than path

- dev-tools/graphile-secrets-decrypt.js
- dev-tools/graphile-secrets-encrypt.js
Adds util scripts for encrypting and decrypting `graphile-secrets` values.
Necessary for debugging NGP VAN integration user issues.
N/A
N/A
> chore(util): add graphile-secrets crypto utils

- __test__/testbed-preparation/core.ts
- src/server/api/lib/interaction-steps.spec.ts
- src/server/api/lib/interaction-steps.ts
This fixes the deletion of interaction steps when using the superadmin approval feature.
When a non superadmin edits the script on a started campaign when using superadmin approval, the campaign is unstarted. Messaged contacts on an unstarted campaign were previously (mostly) impossible, and so we used the `is_started` status of the campaign to check whether interaction steps could be safely deleted.
However, in this case with superadmin approval, a campaign can be unstarted even if contacts are messaged. If survey responses have been applied, deletion of a record in `interaction_step` violates the foreign key constraint on `question_response`. This blocks any script edits from taking effect, after deleting an interaction step has been attempted.
> fix(campaign builder): fix deleting interaction steps

- src/client/App.tsx
- src/client/ErrorHandler.tsx
- src/client/events.ts
- src/network/apollo-client-singleton.ts
Emit errors on the eventbus when a graphql server error is encountered, and show a snackbar 
Fixes #1342 
Tested locally with a few scenarios. Will require some extra testing on staging.
> feat: show a snackbar on mulitple graphql server errors

- src/api/organization-membership.ts
- src/schema.graphql
- src/server/api/organization.js
This PR does two things:
1. Fixes a BAD_USER_INPUT Apollo error
2. Fixes the join on assignment to work when searching only on campaign, and not user
Searching by campaign expected the `user` table to have already been joined but that was not _necessarily_ the case.
N/A
N/A
> fix(people): fix searching by only campaign

- src/server/api/campaign.js
This removes the readiness check for the texters section by always returning `true` for the check.
Auto-assignment is the preferred way of assigning texters. We do not want to draw attention to the texters section, especially with the recent palette change (#1228).
<table>
<tr><td>
Unassigned
</td></tr>
<tr><td>
Closed style
</td></tr>
</table>
N/A
> fix: remove readiness check for texters section

- src/components/BadgeButton.tsx
- src/styles/mui-theme.ts
- src/styles/types.ts
This fixes badge colors for texter replies and active conversation buttons.
They were switched in #1228.
> fix: swap replies and convo colors

- src/containers/TexterTodo.jsx
- src/server/api/schema.js
- src/server/tasks/retry-interaction-step.ts
This fixes how `external_id` is handled when applying scripts.
The `external_id` field is special in that it is always snake-case, in both the database and in GraphQL. This was not being accounted for resulting in `applyScript()` trying to populate `external_id` variables with nonexistent `contact.externalId`.
This has been tested locally in `retry-interaction-step` and in the texter interface.
It has not been tested with bulk sending (disabled in our fork anyway).
N/A
N/A
> fix: handle external_id field correctly in scripts

- src/server/lib/notices/register-10dlc-brand.ts
This disables the 10DLC registration notices.
The notice text is out of date and this is not being enforced. The recent changes to support multiple messaging services per Spoke organization have also resulted in multiple notices per organization impacting usability of the application.
N/A
N/A
> feat: disable 10dlc notices

- src/containers/AdminExternalSystems.tsx
This fixes click handling when clicking cells on the Integrations page.
The MUI v4 [`<Table>`](https://v4.mui.com/api/table/) upgrade in #1360 prevented users from clicking on table cells to access the integration detail page, because the `onCellClick` event is no longer supported. The v4 [`<Table>`](https://v4.mui.com/api/table/) also doesn't support several other props we were using from v0, and are no longer required because of default behavior.
> fix: fix integration cell click handling

- src/server/tasks/queue-autosend-initials.ts
This deprioritizes autosending jobs, so that jobs related to message sending are prioritized in the following order: autoassignment, autosending, handling delivery reports.
On instances with high autosending throughput that also had autoassignment requests occur simulatenously, autoassignment requests could get "stuck in pending" because there were significantly more autosending jobs generated at a given time than autoassignment jobs, and workers never picked up the autoassignment jobs. When autoassignment has a higher priority, this should not occur so frequently.
This has been tested locally to ensure both autoassignment and autosending jobs are picked up by workers. We should also observe autosending performance on previously mentioned instances that have a high rate of autosending and …
> chore: deprioritize autosending

- package.json
- src/config.js
- src/server/api/lib/alerts.spec.ts
- src/server/api/lib/alerts.ts
- src/server/api/schema.js
- src/server/tasks/ngp-van/van-fetch-saved-list.ts
- src/workers/jobs/index.js
- yarn.lock
This adds support for sending webhooks when a large number of contacts are uploaded or a large campaign is started.
Closes #1405.
This depends on bringing VAN list import into Spoke Rewired in #1403.
See `alert.spec.ts`.
N/A
N/A
---
- https://app.asana.com/0/0/1202924564824464
> feat: send webhook on large campaign event

- src/lib/telco-error-codes.ts
Adds Bandwidth 4470 error code.
This is a frequently-occurring error code and should have a user-friendly description.
N/A
N/A
N/A
> fix: add bandwidth 4470 error code

- src/server/tasks/export-campaign.ts
Allow exports to work if `message.campaign_variables` is null, which appears to be the case if the message is a freely typed reply.
We're getting the following error in the wild uncertain conditions:
```
Failed task 179536 (export-campaign) with error Cannot read properties of null (reading 'redacted') (196.36ms):
TypeError: Cannot read properties of null (reading 'redacted')
at /usr/Spoke/build/src/server/tasks/export-campaign.js:410:201
at Array.reduce (<anonymous>)
at campaignVariableColumns (/usr/Spoke/build/src/server/tasks/export-campaign.js:407:69)
at /usr/Spoke/build/src/server/tasks/export-campaign.js:431:18
at Array.map (<anonymous>)
at _callee4$ (/usr/Spoke/build/src/server/tasks/export-campaign.js:414:51)
at tryCatch (/usr/Spoke/node_modules/@babel/runtime-corejs3/node_modules/ …
```
> fix(export-campaign): allow null campaign variables

- src/server/api/lib/message-sending.js
Add more common stop phrases to the list of auto-opt-out phrases.
This increases the amount of replies that can be handled automatically and leads to better user experience.
N/A
N/A
Do we have a knowledge base article on these, @politics-rewired/organizing?
> fix: add additional common stop phrases

- src/containers/AdminOptOutList/components/PasteNumbersDialog.tsx
- src/containers/AdminOptOutList/components/UploadCSVDialog.tsx
- src/containers/AdminOptOutList/index.tsx
In opt outs import/export, the dialog values don't reset. If page is open, opt ins are imported, and you go back to import more, it keeps the previous file / list of pasted numbers.
Also keep export opt outs section open by default 
Feedback from Organizing team
Tested Locally.
> fix: reset dialog values when submitting

- Dockerfile
This ensures that we build for the `linux/amd64` platform without the need to pass the `--platform` option to `docker buildx build`.
The Docker image is only being used on `linux/amd64` nodes in production so that is the only platform we care about currently. We did not need to specify the platform explicitly in the past as CI/CD and local builds were all happening on amd64 architectures. This is no longer the case as Apple M1 arm64 architectures are introduced into development workstations.
To avoid building an arm64 image that won't run in production we either need to remember to pass the `--platform amd64` option at build time or specify it in the Dockerfile. Specifying in the Dockerfile is less prone to error/forgetfulness.
N/A
N/A
> build(docker): specify platform explicitly

- src/server/api/schema.js
This adds the Switchboard profile IDs to the email, saving one step on the backend.
It also wraps the DB writes in a transaction.
This saves the step of looking up which Switchboard profiles need to be decommissioned based on the organization ID.
(https://secure.helpscout.net/conversation/2021272704/7351)
N/A
N/A
> fix: add messaging service sids to org shutdown email

- __test__/testbed-preparation/core.ts
- migrations/20220930011755_add-organization-autosending-mps.js
- src/config.js
- src/server/api/lib/autosend-initials.spec.ts
- src/server/api/schema.js
- src/server/tasks/queue-autosend-initials.spec.ts
- src/server/tasks/queue-autosend-initials.ts
- src/server/worker.ts
This PR does two things:
- Changes autosending speed to be controlled by a database column that lives on the organization table
- Allows multiple campaigns to concurrently autosend across multiple organizations
This accomplishes the following:
- Makes 10DLC compliance easier, since you can send at 30/sec on multiple campaigns
- Makes it easier for texters to simultaneously handle replies across multiple campaigns instead of sequentially dealing with big reply backlogs
See: https://github.com/politics-rewired/Spoke/issues/1441
Test suite
> feat: add database backed per organization autosending

- src/containers/AdminBulkScriptEditor/index.tsx
Fix spelling and grammar in the bulk script editor 
Spelling errors are the leading cause of bad grammar, fix both so we can fix the symptom and the root causes. Fixes #1284 
Tested extensively locally.
> fix(bulk script editor): grammar and spelling

- src/server/tasks/queue-autosend-initials.ts
This fixes a `could not determine data type of parameter $1` error in the `queue-autosend-initials` task.
Regression introduced in #1446.
Full error:
```
5:02:03 PM server.1         |  {"level":"error","message":"Failed task 373053 (queue-autosend-initials) with error could not determine data type of parameter $1 (7.95ms):\n  error: could not determine data type
5:02:03 PM server.1         |  >  of parameter $1\n      at Parser.parseErrorMessage (/Users/bchrobot/rewired/oss/spoke/node_modules/pg-protocol/src/parser.ts:369:69)\n      at Parser.handlePacket (/Users/bchrobot/
5:02:03 PM server.1         |  >  rewired/oss/spoke/node_modules/pg-protocol/src/parser.ts:188:21)\n      at Parser.parse (/Users/bchrobot/rewired/oss/spoke/node_modules/pg-protocol/src/parser.ts:103:30)\n      at …
```
> fix: fix autosending query parameter type error

- src/server/tasks/ngp-van/sync-campaign-contact-to-van.ts
This truncates the day in the contact's timezone rather than UTC.
Truncating to the day in UTC means it will always sync as the day before (e.g. 8:00pm the day before in ET).
It may be worth releasing this as an intermediate to #1442. Or it may not!
N/A
N/A
> fix: truncate day based on contact's timezone

- src/containers/AdminIncomingMessageList/components/IncomingMessageFilter.tsx
GraphQL queries take a bit of time to finish, and Autocomplete doesn't auto select the value when the options change after the value has been set. So set the value after we've pulled in the options for the first time. 
Fixes #1303 
Tested Locally
> fix: fix UI states for campaign and texter

- src/containers/AdminAutosending/index.tsx
This hides the "no campaigns found" message if the query to fetch campaigns is loading.
Closes #1274.
This has been tested locally with:
```diff
diff --git a/src/server/api/organization.js b/src/server/api/organization.js
index 7d3af8f2..8eafab8a 100644
--- a/src/server/api/organization.js
+++ b/src/server/api/organization.js
@@ -37,6 +37,9 @@ export const resolvers = {
settings: (organization) => organization,
campaigns: async (organization, { cursor, campaignsFilter }, { user }) => {
await accessRequired(user, organization.id, "SUPERVOLUNTEER");
+      await new Promise((resolve) => {
+        setTimeout(resolve, 3000);
+      });
return getCampaigns(organization.id, cursor, campaignsFilter);
},
campaignsRelay: async (
```
N/A
---
- To see the specific tasks where the Asana app for …
> fix: show no campaigns message only when not loading

- src/server/api/campaign.js
- src/server/memoredis.ts
Add caching for campaign deliverability stats.
getDeliverabilityStats was responsible for ~24% of CPU time on large clients.
This has been tested locally and in production.
N/A
N/A
> perf: memoize deliverability stats

- src/client/offline.html
Add a link to the Spoke Rewired status page on the offline page.
Closes #1476.
See screenshot below.
N/A
---
- https://app.asana.com/0/0/1203170942924118
> fix(offline): add a link to the status page

- src/server/api/organization.js
This restricts campaign templates returned to the requested organization.
Closes #1471.
N/A
N/A
---
- https://app.asana.com/0/0/1203166788760492
> fix: restrict campaign templates to organization

- src/server/tasks/queue-autosend-initials.ts
Skip queuing organizations with MPS = 0.
Checking for `null` is not enough. Queueing 0 MPS orgs floods logs with:
```
Failed task 824046982 (queue-autosend-organization-initials) with error queueAutoSendInitials was queued for organization 858 but autosending_mps is 0 (1.81ms):
Error: queueAutoSendInitials was queued for organization 858 but autosending_mps is 0
at _callee2$ (/usr/Spoke/build/src/server/tasks/queue-autosend-initials.js:83:19)
at tryCatch (/usr/Spoke/node_modules/@babel/runtime-corejs3/node_modules/regenerator-runtime/runtime.js:45:40)
at Generator.invoke [as _invoke] (/usr/Spoke/node_modules/@babel/runtime-corejs3/node_modules/regenerator-runtime/runtime.js:274:22)
at Generator.prototype.<computed> [as next] (/usr/Spoke/node_modules/@babel/runtime-corejs3/node_modules/rege …
```
> fix: skip queuing organizations with 0 mps

- src/server/api/lib/autosend-initials.spec.ts
- src/server/api/schema.js
Prevent queuing autosending for an organization that does not have an assigned autosending MPS.
Cleaner logs.
This is a safety for the UI-only fix in #1479.
N/A
> fix(autosending): prevent "Queue" user action for orgs without mps

- migrations/20221023123523_update-fillfactors.js
- schema-dump.sql
This sets the to a more reasonable value for our workloads.
From the [manual](https://www.postgresql.org/docs/14/sql-createtable.html#SQL-CREATETABLE-STORAGE-PARAMETERS):
> `fillfactor` (integer)
>
> The fillfactor for a table is a percentage between 10 and 100. 100 (complete packing) is the default. When a smaller fillfactor is specified, INSERT operations pack table pages only to the indicated percentage; the remaining space on each page is reserved for updating rows on that page. This gives UPDATE a chance to place the updated copy of a row on the same page as the original, which is more efficient than placing it on a different page. For a table whose entries are never updated, complete packing is the best choice, but in heavily updated tables smaller fillfactors are appropriate. This …
> perf: update fillfactor to reasonable value

- package.json
- yarn.lock
Upgrades `connect-datadog-graphql` to include calls to `datadog.distribution` for GraphQL requests.
This commit is the only change we're getting: https://github.com/politics-rewired/node-connect-datadog-graphql/commit/64a71e807a2d00dfb0c7b25b79380407fbba77b8
We'd rather have response time distributions than just histograms so we can measure specific long requests instead of the overall trend.
Not tested.
> feat: upgrade connect-datadog-graphql

- package.json
gql-schema can't be imported from libs during production build. 
```
node:internal/modules/cjs/loader:936
throw err;
^
Error: Cannot find module '../../../libs/gql-schema/schema'
Require stack:
- /usr/Spoke/build/src/server/routes/graphql.js
- /usr/Spoke/build/src/server/routes/index.js
- /usr/Spoke/build/src/server/app.js
- /usr/Spoke/build/src/server/index.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
at Function.Module._load (node:internal/modules/cjs/loader:778:27)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (/usr/Spoke/build/src/server/routes/graphql.js:29:16)
at Module._compile (node:internal/modules/cjs/loader:1103:14)
at Object.Module._extensions..js …
```
> fix(gql-schema): server can't import schema when it's in libs

- src/containers/AdminAutosending/components/AutosendingLimitField.tsx
This fixes edits to the autosend limit field, deferring enforcement of the minimum value until after the user has stopped typing.
If contacts have already been sent on a campaign then an autosend limit, if set, must be equal to or above the number of contacts already sent to. Enforcement of this minimum was being applied on every keystroke rather than after the user had finished typing.
N/A
N/A
> fix: debounce autosend limit min value check

- src/containers/AdminCampaignEdit/sections/CampaignContactsForm/index.tsx
This disables campaign overlap in the contact section for VAN integration source.
The backend only supports the `excludeCampaignIds` argument for SQL-source.
Closes #1498.
<table>
<tr><td>
</td><td>
</td></tr>
</table>
I do not believe there are any docs changes for this, but defer to @politics-rewired/organizing 
---
- https://app.asana.com/0/0/1203245301252998
> fix: disable campaign overlap deletion for van source

- src/containers/AdminAutosending/components/AutosendingBasicUnstartedTargetRow.tsx
- src/containers/AdminAutosending/components/AutosendingUnstartedTargetRow.tsx
This adds the autosend per-campaign limit field to autosending control rows for unstarted campaigns.
Closes #1494.
N/A
---
- https://app.asana.com/0/0/1203231684199477
> fix(autosend): add autosend limit field to unstarted rows

- src/containers/AdminCampaignEdit/sections/CampaignTextingHoursForm.tsx
This removes the limit on number of autocomplete results to show in the dropdown.
Closes #1492.
This has been tested locally; see screenshot.
N/A
---
- https://app.asana.com/0/0/1203231165295649
> fix: show all timezone options in dropdown

- src/containers/AdminOptOutList/index.tsx
This removes the collapse behavior from the "Export Opt Outs" card.
Closes #1457.
N/A
---
- https://app.asana.com/0/0/1203125662716844
> fix: remove opt-out collapse/expand behavior

- src/server/api/lib/assemble-numbers.ts
- src/server/app.ts
- src/server/statsd.ts
This adds a counter to send message calls for more granular monitoring and detection.
It appears to be a bit difficult to distinguish between HTTP level errors and 200 + GraphQL errors right now, so we can punt that for now. This accomplishes the main goal of enabling better alerting, and then we can turn to logs to further diagnose in the event of an alert.
TODO
> feat(assemble-numbers): add counter to sendMessage

- src/server/api/lib/send-message.ts
- src/server/tasks/queue-autosend-initials.ts
Change now initials are picked when autosending. 
Also if sending to a contact that is opted out, mark conversations as closed for that contact. Will help pause campaigns correctly for campaigns that have some opts out from other campaigns. 
Barnes autosending incident 
https://rewiredcoop.slack.com/archives/C02KUGE68UX/p1668758724530879
> fix(autosending): change how initials are picked

- Dockerfile
- README.md
Move platform architecture out of the Dockerfile.
This addresses Hadolint warning against this.
See also https://stackoverflow.com/a/66900911/3015709
This reverts #1437
GitHub Actions builds ran fine before #1437.
N/A
Readme has been updated.
> build: move platform choice out of Dockerfile

- src/server/api/conversations.js
This fixes Message Review filtering by specifying org specific opt outs where appropriate.
Contacts who had opted out in other organizations were hidden by default, leading to significant confusion for message review users.
> fix(message review): filter opt outs by organization

- src/containers/AdminBulkScriptEditor/ChangesDialog.tsx
This adjusts the bulk script editor preview so that:
1. Text replacement in the preview occurs correctly when the entire script version is being replaced
2. Color highlighting applies to the full script versions when the entire script version is being replaced
3. "Will replace with" color highlighting is displayed (in all cases)
This edge case which occurs often in production was confusing to bulk script editor users.
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/76596635/201497939-8a9b8659-eb2e-479f-8692-1def632e9e3b.png"/></td>
<td><img src="https://user-images.githubusercontent.com/76596635/201497889-0e347b6d-10cf-4d94-b6fb-4f73c0c17b06.png"/></td>
</tr>
</table>
Not necessary based on the …
> fix(bulk script editor): tidy full script version replacement preview

- libs/gql-schema/schema.ts
- libs/spoke-codegen/src/graphql/template-campaigns.graphql
- src/components/CreateCampaignFromTemplateDialog.tsx
- src/containers/AdminTemplateCampaigns/components/TemplateCampaignRow.tsx
- src/containers/AdminTemplateCampaigns/index.tsx
- src/schema.graphql
- src/server/api/lib/campaign.ts
- src/server/api/root-mutations.ts
allow cloning, and deleting template campaigns
also allow creating new campaigns from the templates list page
Fixes #1335 and #1497 
Tested locally
Deleting asks for confirmations:
Create from template opens the dialog, with the template preselected: 
This reuses the same dialog from the floating create from template button.
> feat: allow cloning, and deleting template campaigns

- src/containers/AdminCampaignList.jsx
Open the speed dial options when you click on the + button, or hover over it, and don't hide it on removing focus, closing it requires clicking the X button.
Fixes #1477
> feat: don't hide campaign create options on removing focus

- migrations/20221117021725_remove-duplicate-opt-outs.js
- package.json
- schema-dump.sql
- src/server/api/lib/fakeservice.js
- src/server/api/lib/interaction-steps.ts
- src/server/api/lib/nexmo.js
- src/server/models/cacheable_queries/opt-out.js
- src/server/tasks/queue-action-external-sync.ts
- yarn.lock
This resolves all knex dependencies to v2.3.0
Follow up to #1324 that allows us to use v2 methods when knex is called through `rethink-knex-adapter`
Changes to src files were found via failing tests in #1532
> chore(knex): resolve to v.2.3.0

- src/server/api/root-mutations.ts
This adds a default fakeservice insert when an organization is created.
In a dev environment (or when creating a [demo production instance](https://github.com/politics-rewired/spoke-rewired-k8s/blob/main/leviathans/demo/deployment.yaml#L241)), we expect that a real messaging service will not be configured for each organization. This PR helps skip a manual step for getting Spoke set up in these cases.
---
- https://app.asana.com/0/0/1203981312852110
> fix(messaging services): add fakeservice default

- src/containers/AssignmentTexterContact/components/ApplyTagDialog.tsx
This replaces a useless `map()` with a useful copy via array destructuring (to avoid accidentally mutating source array).
Comment in #1573.
See https://medium.com/@abdulrasheed.formal/different-ways-to-clone-copy-an-array-in-javascript-be0f5a2ec24e#7963 for more info about destructuring/spreading arrays to copy them.
N/A
N/A
> chore: replace useless map with copy-on-destructure

- src/containers/AssignmentTexterContact/index.jsx
Remove dead code.
`pendingNewTags` was removed from state in #1567 and thus there is no value anymore to calculating it.
N/A
N/A
> chore: remove dead code

- src/containers/AdminCampaignStats/components/SyncConfigurationModal/index.tsx
Fix VAN sync modal reading the wrong query.
Bug report by support in Slack
Tested locally
> fix: van configuration reading the wrong query

- README.md
This PR revises README.md to include an example connection string for `.env` setup.
Configuring the connection string with credentials is required, since later steps require authentication while connecting to the database. It's unlikely that the user will use the default `postgres`/`postgres` credentials, so explicitly specifying credentials in the connection string is imo good practice.
Locally, while going through the onboarding instructions
N/A
No, only for contributors to Spoke. Documentation included in the PR.
> docs(readme): update .env instructions to specify connection string format

- src/server/api/root-resolvers.ts
This fixes an error in the `trollAlarms` GraphQL query encountered in production Docker builds.
After transpilation during the Docker build process (but not locally on my workstation), the `map()` was being called on the knex query object before the `await` executed the actual query. This fixes the issue and improves readability by separating the data fetching from the data transformation.
Closes #1597
This has been tested with local Docker builds.
N/A
N/A
> fix: fix trollAlarms query

- src/server/api/root-mutations.ts
This fetches a campaign ID for the `unqueueAutosending` function.
Without fetching the campaign ID here, admins were unable to pause autosending after launching a campaign.
> fix(autosending): fetch campaign id when pausing

- src/components/Registration10DLCWarningText.tsx
- src/config.js
- src/containers/AdminDashboard/components/NotificationCard.tsx
- src/containers/Settings/components/Review10DlcInfo.tsx
- src/global.d.ts
- src/server/lib/notices/register-10dlc-brand.ts
This PR:
1. Updates Spoke's 10DLC warnings to reflect our intended 2023 timeline. 
2. Adds an envvar for hiding the warning that appears throughout the Admin pages. This envvar should be set to true for "leviathan" clients who manage their registrations directly with TCR, who will not find the warning useful.
Closes #1586 
@politics-rewired/spoke-client is already aware, but dates + screenshots in our 10DLC articles need to be updated.
> chore(10dlc): update notifications

- conventions.md
First pass of a conventions doc
https://github.com/politics-rewired/Spoke/issues/1146
`conventions.md`
> feat: first draft of conventions doc

- src/containers/AdminDashboard/components/NotificationCard.tsx
- src/server/lib/notices/register-10dlc-brand.ts
Use new APIs to check if organization has a 10dlc service before showing registration notices
Tested locally with multiple random messaging service ids
NA
NA
> feat: use new API to check if organization has a 10dlc service

- src/server/api/root-mutations.ts
This clarifies within the email copy that organization shutdown requests are not necessarily instance shutdown requests.
We had tickets opened on consecutive weekends because of org shutdown emails interpreted as instance shutdowns.
N/A
> chore: clarify shutdown email copy

- src/containers/AdminPeople/components/Dialogs.tsx
This updates the Remove Users dialog to specify that Owners will not be removed from the target organization.
Closes #1604 
N/A
@politics-rewired/spoke-client based on a quick review, documentation for the "Remove Users" button is not currently available and will need to be added
> chore(people): update remove users warning

- src/containers/AdminCampaignEdit/sections/CampaignCannedResponsesForm/index.tsx
Changed subtitle on campaign edit page to clarify instructional copy for canned responses
Fixes #984 
No tests ran
No documentation change needed
> feat(canned responses): clarify instructional copy

- src/server/api/root-mutations.ts
This appends the organization id for a new organization to the `messaging_service_sid` for the default fakeservice.
`messaging_service_sid` is the primary key for the `messaging_service` table, and so multiple organizations using a fakeservice could not be created previously.
> fix(messaging services): add org id to fakeservice sid

- src/lib/telco-error-codes.ts
This updates the list of telco errors to account for recent changes to our understanding of certain error codes.
Combination of references to https://dev.bandwidth.com/docs/messaging/errors/ and recent responses to tickets
4750s - can be sending to prepaid AT&T numbers out of credit, but is more often a spam block when seen at high volume
4770s - blocks have been lifted when we open tickets, so we want this to be reflected
4781s - can be exceeding AT&T throughput or a spam block. Once switchboard is handling 10DLC throttling, we can update this to indicate a spam block that can be contested
N/A
> chore(telco errors): update with latest known descriptions

- src/containers/AssignmentTexterContact/index.jsx
This rename makes it clear that the objects being passed around are CampaignContactTags and not Tags.
Without type checking it is easy to make a mistake if variable names are misleading.
N/A
N/A
> chore: use more accurate variable naming

- dev-tools/clone_campaign_sproc.sql
- src/server/api/lib/campaign.ts
This alters the SQL for copying canned responses, to add the `display_order` field when canned responses are copied to a new campaign.
The changes in #1551 require us to pass this field to avoid violating the unique constraint on `display_order`. This error was seen on a beta instance.
```
Postgres error: 
insert into canned_response (campaign_id, title, text)
select
$1 as campaign_id,
title,
text
from canned_response
where campaign_id = $2
- duplicate key value violates unique constraint "canned_response_campaign_id_display_order_unique"
```
> fix(copy campaign): copy display order for canned responses

- src/containers/AdminCampaignEdit/sections/CampaignCannedResponsesForm/index.tsx
This updates types on the canned responses form to keep TypeScript happy.
Less IDE distractions for devs
N/A
> chore(canned responses): update form types

- src/containers/AdminCampaignEdit/sections/CampaignCannedResponsesForm/index.tsx
- src/containers/AdminCampaignEdit/sections/CampaignContactsForm/components/ConfigureColumnMappingDialog.tsx
This changes the handling for dragging canned responses to better accomodate the case where a canned response is dragged up in the list instead of down.
The case where a canned response is dragged up in the list doesn't consistently work with the current handling.
https://github.com/politics-rewired/Spoke/assets/76596635/b2b528a0-ecae-498d-9ec3-8e8e177a878e
> fix(canned responses): handle canned response moving up in the list

- src/containers/AdminCampaignEdit/sections/CampaignContactsForm/components/ConfigureColumnMappingDialog.tsx
This alters the csv mapping dialog to rerender whenever a new file is uploaded.
The mapping columns wouldn't reset when a new file was uploaded previously.
This has been tested locally. Went through a few different versions of this `useEffect` before getting the rerender behavior right.
> fix(csv mapping): rerender on file upload

- src/containers/UserEdit/index.jsx
- src/server/local-auth-helpers.ts
This pr fixes a bug where the desired notification frequency that a user indicated during signup wasn't being set in the database, resulting in users getting the default value `ALL` on signup. 
It refactors the notification frequency field in the signup form to use the `SpokeFormField` `Select` component, ensuring that the value the user enters is included in the `formData` sent to the backend. 
It also sets the `notification_frequency` value inserted into the user table to the value in the `reqBody`. 
It closes #1612 
Locally.
> fix(users): set preferred notification frequency on signup

- src/components/CreateCampaignFromTemplateDialog.tsx
- src/containers/AdminCampaignList.jsx
- removed all hover-related behavior from the create campaign button
- on "toggle", "focus", the action buttons show up
- on "blur","toggle", "escapeKeyDown". the action buttons hide
- updated action buttons to say "Create New Campaign", "Create Campaign from Template" and have the tooltips remain
Completed one of the stretch goals of the ticket:
- Made it say “+ Create a campaign” when the actions are not showing and keep the “X” when the actions are showing
Design ticket created: https://app.asana.com/0/1202110006089866/1204849793973501
Closes #1564 
locally
> fix: create campaign speed dial open/close behavior

- README.md
- docker-compose.yml
This PR builds on top of #1598. Merge that one first before merging this one. Can modify this PR to exclude those changes if you decline to merge #1598.
This PR tweaks `docker-compose.yml` to improve its suitability for local development, and adds instructions to README.md on using Docker to provide a local postgres server.
This PR provides another option for streamlining the developer environment setup for new contributors. In my opinion, we should move to a Docker-based setup for providing external services in a local development environment.
Locally, following README instructions
[Kooha-2023-05-09-19-47-51.webm](https://github.com/politics-rewired/Spoke/assets/1077648/68e875aa-c986-4f6e-9a7d-473f801f286c)
No user facing changes. Contributor facing changes included in PR.
> chore: add docker-compose instructions for local postgres

- src/components/NoticeText/PricingTollFreeNoticeText.tsx
This adds a link for toll free pricing 
Make it easier for users to understand what toll free pricing looks like
> fix: link toll free pricing

- src/lib/telco-error-codes.ts
This updates the list of telco errors to add 4785s
This error code was seen in production for the first time recently
N/A
> chore(telco errors): add 4785 error code

- src/containers/AdminCampaignList.jsx
In snackbar alert, when creating campaigns from templates. Give correct link to the edit campaign page. 
NA 
Tested locally
> fix: take campaign to edit link for create from template

- src/components/NoticeText/ShutdownNoticeText.tsx
- src/containers/AdminDashboard/components/NotificationCard.tsx
- src/containers/AdminDashboard/components/ShutdownNoticeCard.tsx
This adds a notification for Spoke Rewired users about upcoming shutdown
thank you @politics-rewired ❤️ 
> feat: add shutdown notification

- src/server/lib/notices/register-10dlc-brand.ts
This adds a timeout and error handling for times when Spoke Portal is unreachable.
Spoke Portal being unreachable caused fetching notices to fail with an error every time.
N/A
N/A
> fix: handle Spoke Portal being unreachable

- libs/gql-schema/notice.ts
- libs/spoke-codegen/src/graphql/notifications.graphql
- src/api/notice.ts
- src/containers/AdminDashboard/components/NotificationCard.tsx
- src/containers/AdminDashboard/components/TitleContentNoticeCard.tsx
- src/schema.graphql
- src/server/api/notice.ts
This adds a generic notice type with a title and markdown content.
Many notices are just informational and this covers those.
Part 1 of 2.
See forthcoming part 2.
N/A
> feat: add generic title/content notice type
